### ISSUE TITLE
NullReferenceException when logging as Trace and an argument is null

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#1005]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.AspNetCore.SignalR.Client.Internal.SignalRClientLoggerExtensions.<>c.<IssueInvocation>b__33_0(Object a)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.AspNetCore.SignalR.Client.Internal.SignalRClientLoggerExtensions.IssueInvocation(ILogger logger, String invocationId, String returnType, String methodName, Object[] args)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCore(String methodName, InvocationRequest irq, Object[] args, Boolean nonBlocking)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendAsyncCore(String methodName, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<SendAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChatClient.ChatClient.<SendMessage>d__6.MoveNext() in C:\source\SignalR-Samples\ChatSample\ChatClient\ChatClient.cs:line 56
```
[here](https://github.com/aspnet/SignalR/blob/786980bc3fc806c0c457d4500f209d52dba4ea09/src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/SignalRClientLoggerExtensions.cs#L125).

**Comment by BrennanConroy** [comment]
Nice, so we should probably handle null arguments

**Comment by moozzyk** [comment]
Yes. I did not notice but when I pressed Ctrl+C Console.ReadLine() returned null which I tried to send and got the exception. I think we should review logging since I think I saw the same pattern in at least one more place.

**Comment by moozzyk** [comment]
Fixed in 8f770e
