### ISSUE TITLE
Asp.Net Core 2.0 SignalR and signalr-client-sdk-android.jar

### ISSUE THREAD

**Issue by jagathprasanga** [aspnet/SignalR#1017]
I'm trying to connect Asp.Net Core 2.0 SignalR hub from Android client. 
Server side : - Microsoft.AspNetCore.SignalR.Client -Version 1.0.0-alpha2-final
Android side : signalr-client-sdk-android.jar', signalr-client-sdk.jar

But it says "microsoft.aspnet.signalr.client.transport.NegotiationException" always.
The request from Android side is 
 http://192.168.137.1:31525/BreakdownAssistAndroidHub/negotiate?clientProtocol=1.3&connectionData=%5B%7B%22name%22%3A%22breakdownassistandroidhub%22%7D%5D
How can I fix this.
Thanks.

**Comment by BrennanConroy** [comment]
**ASP.NET Core SignalR** is not compatible with previous versions of SignalR. 
https://github.com/aspnet/SignalR/issues/883#issuecomment-329801935

**Comment by Gurgen** [comment]
This is android lib for SignalR .net core version
[https://github.com/Gurgen/SignalR-.net-core-android-client](https://github.com/Gurgen/SignalR-.net-core-android-client)

**Comment by farzinp7** [comment]
@Gurgen 
I Cant Connect To Signalr With This plugin.
**Server Side**
`    
 public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddMvc();
            services.AddSignalR();
          

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();
            app.UseWebSockets();
            app.UseCors(builder =>
                builder.AllowAnyHeader()
          );
           
            app.UseSignalR(routes =>
            {
                routes.MapHub<TestHub>("/TestHub1");
            });
            app.UseMvcWithDefaultRoute();
        }
    }
`
` public class TestHub : Hub
    {
        public async Task Send(string nick, string message)
        {
            await Clients.All.SendAsync("Send", nick, message);
        }
        public override Task OnConnectedAsync()
        {
            Clients.All.SendAsync("Send", "Client", "Conected");
            return base.OnConnectedAsync();

        }
        public override Task OnDisconnectedAsync(Exception exception)
        {
            Clients.All.SendAsync("Send", "Client", "DisConected");
            return base.OnDisconnectedAsync(exception);
        }


    }`
Client Android
`       HubConnection connection = new WebSocketHubConnectionP2("http://signalrtest.petchap.com/TestHub1",null);
        connection.addListener(new HubConnectionListener() {
            @Override
            public void onConnected() {
                Log.i(TAG,"onConnected");
            }

            @Override
            public void onDisconnected() {
                Log.i(TAG,"onDisconnected");
            }

            @Override
            public void onMessage(HubMessage message) {
                Log.i(TAG,"onMessage");
            }

            @Override
            public void onError(Exception exception) {
                Log.i(TAG, "onError: "+exception.getMessage());
            }
        });
        connection.subscribeToEvent("Send", new HubEventListener() {
            @Override
            public void onEventMessage(HubMessage message) {
                Log.i(TAG,"onEventMessage");
            }
        });
        connection.connect();`
SignalR On Server Works Fine.
http://signalrtest.petchap.com/

**Comment by anurse** [comment]
@farzinp7 If you're reporting an issue with @Gurgen 's client, please file it on that repository. This tracker is for issues with the official ASP.NET Core SignalR client/server packages only.

**Comment by shkwaleed** [comment]
@anurse Exception Details
java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/base.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.microsoft.signalr.HubConnection.<init>(HubConnection.java:50) 
        at com.microsoft.signalr.HttpHubConnectionBuilder.build(HttpHubConnectionBuilder.java:64) 
        at com.microsoft.aspnet.signalr.samples.androidjavaclient.MainActivity.onCreate(MainActivity.java:27) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.microsoft.aspnet.signalr.samples.androidjavaclient-1/split_lib_slice_5_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:295)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexFile.<init>(DexFile.java:59)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
        at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
        at dalvik.system.DexPathList.<init>(DexPathList.java:120)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:84)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:45)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:434)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:659)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6289)



On Android api below 26 we are unable to run signalr client
