### ISSUE TITLE
Connection with the server was terminated abnormally

### ISSUE THREAD

**Issue by ppumkin** [aspnet/SignalR#1052]
I am using the SignalR console application client and sometimes, due to the Hub website being updated the signalR .NET client will throw this error.

The connection with the server was terminated abnormally

Stack
```
 at System.Net.WebSockets.WinHttpWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport.<SendMessages>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<SendAsyncCore>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<SendAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<SendInvocation>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<InvokeAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at POEUtility.Workers.SignalRChangeHubWorker.<DoWorkAsync>d__8.MoveNext() in C:\Projects\Other\POEUtility\POEUtility.Workers\SignalRChangeHubWorker.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at POEUtility.Console.Program.<WorkerLoop>d__5.MoveNext() in C:\Projects\Other\POEUtility\POEUtility.Console\Program.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at POEUtility.Console.Program.<MainAsync>d__4.MoveNext() in 
```

When this happens, the Closed event does **NOT** fire. So the connection variable still thinks it is connected and the next time I send a message I get the following **infamous** error.

Object reference not set to an instance of an object.

stack

```
at Microsoft.AspNetCore.SignalR.Client.HubConnection.<SendInvocation>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<InvokeAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at POEUtility.Workers.SignalRChangeHubWorker.<DoWorkAsync>d__8.MoveNext() in C:\Projects\Other\POEUtility\POEUtility.Workers\SignalRChangeHubWorker.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at POEUtility.Console.Program.<WorkerLoop>d__5.MoveNext() in C:\Projects\Other\POEUtility\POEUtility.Console\Program.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at POEUtility.Console.Program.<MainAsync>d__4.MoveNext() in 
```

At this point I do not know if the connection is active or not active? There are no properties available to tell me what state the connection is in.

Workaround:

I suppose I can catch all exceptions, dump the connection and try to recreate it for next use.

**Comment by moozzyk** [comment]
Are you running behind IIS or you are using just Kestrel? Do you just stop Kestrel or how is the server being shut down?

Can you turn on logging at the .Trace level and paste logs here?

Generally the closed event should be invoked. Also the NullReferenceException should not happen.

**Comment by moozzyk** [comment]
The webSocket should get disconnected if sending fails, which should result in closing the connection. Without repro steps and/or logs it's hard to tell why it is not happening. Likely, KeepAlive feature (https://github.com/aspnet/SignalR/issues/282) should help with the first issue. 
The NullReferenceException could have been fixed in https://github.com/aspnet/SignalR/commit/06475270ec845b5be95c46857d33599e41585e86 - impossible to confirm though since the stack trace for NRE was not included.
