### ISSUE TITLE
Intermittent error: Cannot access a disposed object

### ISSUE THREAD

**Issue by MisterAcoustic** [aspnet/SignalR#1094]
Hello,

Our application undergoes automated testing after each commit/build. Once every two or three hundred tests, the testing will fail due to an exception in SignalR. Here is a typical stack trace:

`Cannot access a disposed object.
Object name: \u0027LITEWORLD\u0027.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func2 send, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.\u003c\u003ec__DisplayClass6_0.\u003cBuildOutgoing\u003eb__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object\u0026 result)
   at CallSite.Target(Closure , CallSite , Object , String )
   at E2SSPro.Web.SignalR.DBUpdateHub.SendMessage(String msg, String signalToken) in D:\\TeamCity\\BuildAgent3\\work\\b28bc0f3a005363e\\E2SSPro.Web\\SignalR\\DBUpdateHub.cs:line 25
   at E2SSPro.Web.Controllers.DBUpdateController.AddProgressMsg(String message) in D:\\TeamCity\\BuildAgent3\\work\\b28bc0f3a005363e\\E2SSPro.Web\\Controllers\\DBUpdateController.cs:line 103
   at E2SSPro.Web.Controllers.DBUpdateController.UpdateStatusDelegate(String message, Boolean messageBox, Boolean logFile) in D:\\TeamCity\\BuildAgent3\\work\\b28bc0f3a005363e\\E2SSPro.Web\\Controllers\\DBUpdateController.cs:line 113
   ...`

Background: I have a single server vm running 10 copies of our application in IIS. To run a test, a site is chosen, the app pool is shut down, new files are copied in, and the app pool restarted. The system uses a Redis cluster on the back end which handles the SignalR messaging. (I wrote the testing system, not the application, so I will have to ask if more details are needed.) A database update process normally uses SignalR to report status to the user in their browser. However, in the automated testing case, there is no actual browser (only a different app sending requests), and therefore there is no client that is actually listening to any of the messages.

As I mentioned, we see this error very infrequently, but it's there, and it never stops happening :). Any ideas what might be going on?

Thanks for your help.

**Comment by moozzyk** [comment]
Please file this issue in the https://github.com/SignalR/SignalR repo. Also, what version of SignalR are you using?
