### ISSUE TITLE
The 'Connection' header value '' is invalid

### ISSUE THREAD

**Issue by bigswede74** [aspnet/SignalR#1125]
I'm trying to connect to to the signalr hub using the .net client and I'm getting this error when connecting. I see the request come through the http pipeline but then the conneciton fails. I'm passing an extra item in the querystring.

Request starting HTTP/1.1 GET http://localhost/WebHost/myhub?clientId=MyClientId&id=a657f3fa-b28d-49b9-a6d5-cb056bc52df4  

Connection Id a657f3fa-b28d-49b9-a6d5-cb056bc52df4: Socket opened.

System.Net.WebSockets.WebSocketException (0x80004005): The 'Connection' header value '' is invalid.
   at System.Net.WebSockets.ClientWebSocket.ValidateResponse(HttpWebRequest request, HttpWebResponse response)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport.<Connect>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport.<StartAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<StartTransport>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<StartAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<DisposeAsyncCore>d__53.MoveNext()

**Comment by BrennanConroy** [comment]
Do you happen to be on Win7?

**Comment by bigswede74** [comment]
@BrennanConroy its running on Windows Server 2012 R2

**Comment by BrennanConroy** [comment]
Is the server hosted in IIS?

**Comment by bigswede74** [comment]
@BrennanConroy yes, it is hosted in IIS

**Comment by BrennanConroy** [comment]
Have you enabled WebSockets in IIS via the Windows Features settings?

**Comment by bigswede74** [comment]
@BrennanConroy that fixed the issue, thanks so much for the quick response.
