### ISSUE TITLE
Connection closes (almost) immediately behind IIS

### ISSUE THREAD

**Issue by mn-ba** [aspnet/SignalR#1180]
Hi all,

**Short Description**

We are facing a major issue on our staging systems. (SignalR connections are closed almost immediately after they are opened when IIS is used as reverse proxy.) UPDATE1: SignalR connection is closed after the first Hub method is called. I can find no errors, warnings or any other logs that would point to the problem. This issue can not be observed when accesing the application directily via Kestrel.

**Environment**

- Windows Server 2012, IIS 8.5, SignalR 1.0.0-alpha2-final on server and client side

**Detailed Description**

The log file of the backend:

```
NOT WORKING (IIS):
14:30:20 [Debug] [Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport] 12/05/2017 14:30:20: Connection Id "6b1ebec8-7293-4019-b7de-1b7c329e8cbe": Sending payload: 101 bytes.
14:30:24 [Debug] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] Connection id ""0HL9RSH8QSKR9"" reset.
14:30:24 [Debug] [Microsoft.AspNetCore.Server.Kestrel] Connection id ""0HL9RSH8QSKR9"" disconnecting.
14:30:24 [Debug] [Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport] 12/05/2017 14:30:24: Connection Id "6b1ebec8-7293-4019-b7de-1b7c329e8cbe": Waiting for the application to finish sending data.
14:30:24 [Debug] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] Connection id ""0HL9RSH8QSKR9"" sending FIN.
14:30:24 [Information] [Our.Application.Server.Hubs.ToolHub] Disconnected WS connection with id $6b1ebec8-7293-4019-b7de-1b7c329e8cbe
14:30:24 [Information] [Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport] 12/05/2017 14:30:24: Connection Id "6b1ebec8-7293-4019-b7de-1b7c329e8cbe": Socket closed.

WORKING (Kestrel w/o IIS)
14:31:50 [Debug] [Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport] 12/05/2017 14:31:50: Connection Id "1c63505e-081c-48d5-b1e8-a24411755bc2": Sending payload: 101 bytes.
14:31:52 [Debug] [Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport] 12/05/2017 14:31:52: Connection Id "1c63505e-081c-48d5-b1e8-a24411755bc2": Message received. Type: Text, size: 98, EndOfMessage: True.
14:31:52 [Debug] [Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport] 12/05/2017 14:31:52: Connection Id "1c63505e-081c-48d5-b1e8-a24411755bc2": Passing message to application. Payload size: 98.
```

In case this is of any help, this exception is thrown on verbose level *after* the last "Socket closed" statement:

```
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ConnectionResetException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.<ReadAsyncInternal>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<StartReceiving>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<ProcessSocketAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<ProcessRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()
14:55:08 [Verbose] [Microsoft.AspNetCore.Sockets.ConnectionManager] 12/05/2017 14:55:08: ConnectionId "f08d6d40-809a-4f11-85df-5a0912621441": Connection was reset.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ConnectionResetException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.<ReadAsyncInternal>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<StartReceiving>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<ProcessSocketAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<ProcessRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()
```

The logs in the frontend:

```
Information: WebSocket connected to ws://our.application.com/signalr?id=...
Information: Using HubProtocol 'json'.
HubService: {"__zone_symbol__currentTask":null}
Error: Websocket closed with status code: 1006 ()

OR

Information: WebSocket connected to ws://our.application.com/signalr?id=...
Information: Using HubProtocol 'json'.
HubService: {"__zone_symbol__currentTask":null}
Cannot send data if the connection is not in the 'Connected' State
```

There are no logs visible in Event Viewer which indicate anything in that direction.

WebSockets feature for IIS is activated. 

Also, I tried *one* reference environment with Win10 / IIS 10. Here, I could not reproduce the problem.

----------

Does anyone here have a slightest hint on how I could proceed/debug or is even aware of similar issues? I am really lost here...

Thanks!!

**Comment by anurse** [comment]
Just to make sure I understand, this issue repros on Windows Server 2012/IIS 8.5, but not when running on Windows 10/IIS 10? And it doesn't repro at all when running directly behind Kestrel? (I believe that's what you've explained but I want to make absolutely sure I'm not missing something ;))

@pan-wang are you familiar with a reason why IIS 8.5 might have different handling of WebSockets than IIS 10.0? I'm not sure if there's an issue there but it's something to explore.

@mn-ba are you able to narrow this down a little to a simpler repro that you could share with us? That would help us immensely in figuring out what is wrong. Similarly, could you try a simple WebSocket application (no SignalR) and see if the issue reproduces in that application? The sample application here (https://github.com/aspnet/WebSockets/tree/dev/samples/EchoApp) is relatively easy to extract and run (it includes a browser-based client as well).

**Comment by anurse** [comment]
Also, do you have any anti-virus or network monitoring tools on the machine? Since it doesn't repro in a different environment, that could be causing problems.

**Comment by pan-wang** [comment]
I don't think IIS10 handles WebSocket differently from IIS8.5. @mn-ba could you please double check whether you have IIS WebSocket sub-feature enabled on your server 2012 box and please collect iDNA trace and FREB log to help us diagnose the root cause.

**Comment by mn-ba** [comment]
Thanks for your fast feedback!

> Just to make sure I understand, this issue repros on Windows Server 2012/IIS 8.5, but not when running on Windows 10/IIS 10? And it doesn't repro at all when running directly behind Kestrel?

Yeah, that is right. But again, I'd like to point out that I tested the Win10/IIS10 combination only on one system, while I can produce the failure on Win Server 2012/IIS 8.5 on at least three machines.

> are you able to narrow this down a little to a simpler repro that you could share with us? 

Shouldn't be a problem - will do that!

> Also, do you have any anti-virus or network monitoring tools on the machine?

I already found this hint and checked, but going to double-check again. Reason: It seems to work properly when the app is requested from localhost, while it always fails when accessing it from a remote host. I guess this could be +1 for the firewall...? On the other hand, the fact that it works when served from Kestrel directly, probably does not...

> could you please double check whether you have IIS WebSocket sub-feature enabled on your server 2012

Done that again, its enabled!

>  please collect iDNA trace and FREB log to help us diagnose the root cause.

Never done both of those, at least for FREB it seems I figured out how to do that --> I am trying to collect those and provide them here.

**Comment by anurse** [comment]
iDNA is an internal name for [Time Travel Debugging](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview) which is a pretty complicated set of traces to collect. Let's hang on before we dive too deep there. If WebSocket handling shouldn't have changed between IIS 8.5 and 10.0, then let's keep investigating some other machine-level stuff before we open that can of worms :)

**Comment by mn-ba** [comment]
Okay, here's the current state:

* I'm pretty certain it's not an anti-virus issue
* the [plain WS application](https://github.com/aspnet/WebSockets/tree/dev/samples/EchoApp) works just fine
* For testing SignalR, I took the liberty of using [this sample](https://github.com/aspnet/SignalR/tree/rel/1.0.0-alpha2/samples/SocketsSample) (Branch rel/1.0.0-alpha2). This results in the following behavior:

- [X] Works just fine when using it directly via Kestrel
- [X] Works just fine when running on Win10/IIS10
- [X] Works just fine when running on WinServer2012/IIS8.5 *and accessing it from localhost*
- [ ] Does not work when running on WinServer2012/IIS8.5 *and accessing it from remote*

This behavior, I can also reproduce with our application --> works fine when accessing from localhost

```
SUCCESS (Access from localhost)
Connected successfully
3d01f7d0-e96a-477c-8b21-6b3c81343e29 joined
3d01f7d0-e96a-477c-8b21-6b3c81343e29: sd
3d01f7d0-e96a-477c-8b21-6b3c81343e29: sd
3d01f7d0-e96a-477c-8b21-6b3c81343e29: sd
3d01f7d0-e96a-477c-8b21-6b3c81343e29: sd
3d01f7d0-e96a-477c-8b21-6b3c81343e29: sd
3d01f7d0-e96a-477c-8b21-6b3c81343e29: sd
...
...

FAILURE (Access from remote)
Connected successfully
7fdaab1c-ce40-4baf-abbe-0ba1588d4ea5 joined
7fdaab1c-ce40-4baf-abbe-0ba1588d4ea5: as
7fdaab1c-ce40-4baf-abbe-0ba1588d4ea5: as
7fdaab1c-ce40-4baf-abbe-0ba1588d4ea5: as
Connection closed with error: Error: Websocket closed with status code: 1006 ()
Error: Websocket closed with status code: 1006 ()
Error: Cannot send data if the connection is not in the 'Connected' State
Error: Cannot send data if the connection is not in the 'Connected' State
```

This holds true to all three protocols that are available from the SocketsSample app: Long polling, Server sent events and Web Sockets. Depending on fast you click, you can get through with a few calls, but the the connection is closed.

Hint for reproducing this: I "hacked" the URI (virt dir) to the app when deployed on IIS directly into the SignalR JS client (resolveUrl method in signalr-client-1.0.0-alpha2-final.js) so the connection basically works.

**Comment by anurse** [comment]
> Works just fine when running on WinServer2012/IIS8.5 and accessing it from localhost
> Does not work when running on WinServer2012/IIS8.5 and accessing it from remote

This seems very odd to me.

> Hint for reproducing this: I "hacked" the URI (virt dir) to the app when deployed on IIS directly into the SignalR JS client (resolveUrl method in signalr-client-1.0.0-alpha2-final.js) so the connection basically works.

Why did you need to change the SignalR JS client at all?

One thing that may help us debug is if you could collect a network trace of some kind. [Fiddler](https://www.telerik.com/fiddler) should be sufficient for that. Getting an idea of what HTTP requests are going where and how the app is being disconnected would be useful. The WebSocket status code `1006` indicates that the underlying connection was terminated abnormally, so something is terminating the TCP connection.

**Comment by pan-wang** [comment]
If it works with localhost but not remote,  it is usually an issue with machine firewall setting which does not allow the port opened.  Please try open the tcp port manually first to see whether it helps.

**Comment by anurse** [comment]
@pan-wang If that were the case the connection would fail to establish in the first place though, right? This is terminating mid-connection. That's why a network trace will be useful for investigation.

**Comment by mn-ba** [comment]
> Why did you need to change the SignalR JS client at all?

Without further investigating it, I didn't find a quick(er) solution to configure the target URL of the WS backend. To me it seems like it is expected to be running under root ('/'), which in my IIS deployment was not the case.

> If it works with localhost but not remote, it is usually an issue with machine firewall setting which does not allow the port opened

Firewall has completely been disabled, just to be sure. But as @anurse was mentioning, if this was the issue I would not expect a successful connection in the first place.

> One thing that may help us debug is if you could collect a network trace of some kind. 

I'm struggling a little bit with that. With Fiddler, I don't seem to be able to capture the traffic at all. Using Wireshark, it results in huge output, in which at least I can not find any relevant hints, and more important which I am not yet sure whether or not I am allowed to share it - I come back to you when I figured it out...

Nevertheless, I found that this issue does not reproduce on a clean, non-corporate managed VM which I have set up by myself, which leads me to the assumption that it might be a local misconfiguration after all. Next I will line by line compare the
a) installed IIS features
b) the IIS configuration
to find differences between those machines...

Also, if that holds true, it would most likely mean that SignalR is off the hook here.... :)

**Comment by anurse** [comment]
> Without further investigating it, I didn't find a quick(er) solution to configure the target URL of the WS backend.

It should use the URL that you provide in the `HubConnection` constructor. So if you create a `HubConnection` using `http://localhost:1234/mysite/myhub`, then the WebSocket URL would be `ws://localhost:1234/mysite/myhub`.

**Comment by mn-ba** [comment]
I did not explicitly create any HubConnection - I just took the code as-is and executed it on my machines.

Anyhow, here is the current state:
* I assume that it is an issue with the specific setup on the three machines where we encounter this error, still I have not found it yet.
* Nevertheless, *something* seems to have changed in SignalR between the 2.0 and the previous, unofficial (I am aware of that..) version we found [here](https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR.Server), because that worked flawlessly on all of our machines.

But I guess this issue can be closed - in case I ever will find the root cause of the problem, I will post it here for future reference..

Thanks for your help!

**Comment by anurse** [comment]
> I did not explicitly create any HubConnection

This seems odd to me. There is no official version of the SignalR Core that works that way, you always have to create a `HubConnection` object.

> Nevertheless, something seems to have changed in SignalR between the 2.0 and the previous, unofficial (I am aware of that..) version we found here,

What SignalR packages (ID and version) are you using? The `0.2.0` packages you referenced are from an early unsupported/unofficial prototype effort and the new framework is completely rewritten from that.

**Comment by mn-ba** [comment]
>This seems odd to me. There is no official version of the SignalR Core that works that way, you always have to create a HubConnection object.

Hm, I guess I have not made it clear enough. All I did was really just to take the SocketsSample project as linked above and execute it. It obviously creates a HubConnection itsself, but I did not touch that and for me it did not work when deployed on non-root-path ("/"), because it did not find the Hub then :)

> What SignalR packages (ID and version) are you using? The 0.2.0 packages you referenced are from an early unsupported/unofficial prototype effort and the new framework is completely rewritten from that.

As stated above, its v`1.0.0-alpha2-final` and the ID is `Microsoft.AspNetCore.SignalR`. I am aware that `0.2.0` was never officially supported, but nevertheless we used it to get started and with that version, everything worked smooth.

Btw: I still could not figure out what the issue is...

**Comment by anurse** [comment]
Ok, I was just a little confused with what you were referring to :). It definitely sounds like some kind of machine configuration issue if you were able to run it on a clean machine without the issue.

**Comment by mn-ba** [comment]
Just FYI: We gave up and completely re-installed our defective systems. After we have done that, we can not reproduce this issue anymore. 

So I guess there has been done some weird manual configuration at some point in time (probably in IIS?) which caused this.

Thanks for your support!

**Comment by anurse** [comment]
Glad to hear you got it sorted out! Let us know if it reoccurs!
