### ISSUE TITLE
Object Disposed Exception on OnReceived callback

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1199]
```
fail: Microsoft.AspNetCore.Sockets.Client.HttpConnection[19]
      12/11/2017 10:30:05: Connection Id (null): An exception was thrown from the 'OnReceived' callback
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ResetTimeoutTimer() in C:\Github\SignalR\src\Microsoft.AspNetCore.SignalR.Client.Core\HubConnection.cs:line 104
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<OnDataReceivedAsync>d__40.MoveNext() in C:\Github\SignalR\src\Microsoft.AspNetCore.SignalR.Client.Core\HubConnection.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<>c__DisplayClass45_0.<<ReceiveAsync>b__0>d.MoveNext() in C:\Github\SignalR\src\Microsoft.AspNetCore.Sockets.Client.Http\HttpConnection.cs:line 377
```

@anurse

**Comment by anurse** [comment]
Context for anyone else: It's an easy fix but it doesn't break behavior, it just spams the logs and I want to get #1147 in before messing with that code again, since there are conflicts there and I spent a bunch of time resolving them :). Also want to write a test.

**Comment by muratg** [comment]
Moving to preview2, but if you feel like this can (and should) be done quickly in preview1, feel free to bring it back!
