### ISSUE TITLE
Flaky Test: Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#1214]
```
[xUnit.net 00:00:21.4563431]     Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent [FAIL]
[xUnit.net 00:00:21.4621106]       System.TimeoutException : Operation in CanStartConnectionFromClosedEvent timed out at /home/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:166
[xUnit.net 00:00:21.4638151]       Stack Trace:
[xUnit.net 00:00:21.4655115]         /home/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs(26,0): at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext()
[xUnit.net 00:00:21.4656292]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:21.4657117]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:21.4658963]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:21.4661460]         /home/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs(179,0): at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CanStartConnectionFromClosedEvent>d__5.MoveNext()
[xUnit.net 00:00:21.4662213]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:21.4663120]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:21.4663864]            at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CanStartConnectionFromClosedEvent>d__5.MoveNext()
[xUnit.net 00:00:21.4664616]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:21.4665267]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:21.4665903]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:21.4667627]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:21.4668469]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:21.4670609]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:21.4671555]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:21.4672194]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:21.4673056]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:21.4709931]       Output:
[xUnit.net 00:00:21.4733149]         | TestLifetime Information: Starting test CanStartConnectionFromClosedEvent
[xUnit.net 00:00:21.4734250]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id (null): Connection state changed from Disconnected to Connecting.
[xUnit.net 00:00:21.4734853]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Starting connection.
[xUnit.net 00:00:21.4735254]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Establishing Connection at: http://127.0.0.1:40337/default.
[xUnit.net 00:00:21.4735677]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Starting transport 'WebSocketsTransport' with Url: http://127.0.0.1:40337/default?id=b41eb094-760d-40fd-8f17-58a415767c15.
[xUnit.net 00:00:21.4736170]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Starting transport. Transfer mode: Text.
[xUnit.net 00:00:21.4736643]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Starting the send loop.
[xUnit.net 00:00:21.4737097]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Starting receive loop.
[xUnit.net 00:00:21.4737500]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Connection state changed from Connecting to Connected.
[xUnit.net 00:00:21.4738043]         | Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json'.
[xUnit.net 00:00:21.4738495]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Sending message.
[xUnit.net 00:00:21.4738848]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Received message from application. Payload size: 20.
[xUnit.net 00:00:21.4739370]         | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering Invocation ID '1' for tracking.
[xUnit.net 00:00:21.4739821]         | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Invocation '1'.
[xUnit.net 00:00:21.4740228]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Sending message.
[xUnit.net 00:00:21.4740711]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Received message from application. Payload size: 70.
[xUnit.net 00:00:21.4741931]         | Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Invocation '1' completed.
[xUnit.net 00:00:21.4743152]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Message received. Type: Text, size: 49, EndOfMessage: True.
[xUnit.net 00:00:21.4745606]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Passing message to application. Payload size: 49.
[xUnit.net 00:00:21.4746548]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Scheduling raising Received event.
[xUnit.net 00:00:21.4747704]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Raising Received event.
[xUnit.net 00:00:21.4749655]         | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Stopping connection
[xUnit.net 00:00:21.4751465]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Stopping client.
[xUnit.net 00:00:21.4752048]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Send loop stopped.
[xUnit.net 00:00:21.4753469]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Transport is stopping.
[xUnit.net 00:00:21.4755820]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Closing WebSocket.
[xUnit.net 00:00:21.4756362]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Websocket closed by the server. Close status NormalClosure.
[xUnit.net 00:00:21.4758071]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Ensuring all outstanding messages are processed.
[xUnit.net 00:00:21.4758724]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Receive loop stopped.
[xUnit.net 00:00:21.4760626]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Draining event queue.
[xUnit.net 00:00:21.4761229]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Transport stopped.
[xUnit.net 00:00:21.4761727]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Completing Closed task.
[xUnit.net 00:00:21.4762153]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Connection state changed from Connected to Disconnected.
[xUnit.net 00:00:21.4762610]         | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Closed event triggered
[xUnit.net 00:00:21.4762947]         | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Restarting connection
[xUnit.net 00:00:21.4763315]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id b41eb094-760d-40fd-8f17-58a415767c15: Connection state changed from Disconnected to Connecting.
[xUnit.net 00:00:21.4763780]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Starting connection.
[xUnit.net 00:00:21.4765726]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Establishing Connection at: http://127.0.0.1:40337/default.
[xUnit.net 00:00:21.4768088]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Starting transport 'WebSocketsTransport' with Url: http://127.0.0.1:40337/default?id=55cebc98-fff6-4675-81fa-271fdee480f7.
[xUnit.net 00:00:21.4771179]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:40: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Starting transport. Transfer mode: Text.
[xUnit.net 00:00:21.4771782]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Starting the send loop.
[xUnit.net 00:00:21.4774179]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Starting receive loop.
[xUnit.net 00:00:21.4775345]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Connection state changed from Connecting to Connected.
[xUnit.net 00:00:21.4778025]         | Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json'.
[xUnit.net 00:00:21.4779840]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:40: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Sending message.
[xUnit.net 00:00:21.4781093]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:40: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Received message from application. Payload size: 20.
[xUnit.net 00:00:21.4781862]         | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Restarted connection
[xUnit.net 00:00:21.4783588]         | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: Exception from test
[xUnit.net 00:00:21.4784788]         |    at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext() in /home/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 26
[xUnit.net 00:00:21.4785739]         | --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:21.4787719]         |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:21.4788256]         |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:21.4788854]         |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CanStartConnectionFromClosedEvent>d__5.MoveNext() in /home/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 168
[xUnit.net 00:00:21.4790665]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Stopping client.
[xUnit.net 00:00:21.4792265]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Transport is stopping.
[xUnit.net 00:00:21.4793401]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Closing WebSocket.
[xUnit.net 00:00:21.4793972]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Send loop stopped.
[xUnit.net 00:00:21.4795201]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Information: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Websocket closed by the server. Close status NormalClosure.
[xUnit.net 00:00:21.4797222]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Receive loop stopped.
[xUnit.net 00:00:21.4799392]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Ensuring all outstanding messages are processed.
[xUnit.net 00:00:21.4800035]         | Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Transport stopped.
[xUnit.net 00:00:21.4801330]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Draining event queue.
[xUnit.net 00:00:21.4803054]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Completing Closed task.
[xUnit.net 00:00:21.4803644]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Connection state changed from Connected to Disconnected.
[xUnit.net 00:00:21.4804617]         | Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Closed event triggered
[xUnit.net 00:00:21.4806682]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Debug: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Connection state changed from Disconnected to Disposed.
[xUnit.net 00:00:21.4807287]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: 12/13/2017 23:37:45: Connection Id 55cebc98-fff6-4675-81fa-271fdee480f7: Disposing client.
[xUnit.net 00:00:21.4807970]         | TestLifetime Information: Finished test CanStartConnectionFromClosedEvent in 5.0535474s
```

**Comment by davidfowl** [comment]
Closing this as we have another flaky test bug
