### ISSUE TITLE
Flaky test: CanCloseStreamMethodEarly

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#1225]
As seen [here](http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=369371&_focus=362828).
```
[Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanCloseStreamMethodEarly(protocol: JsonHubProtocol { Name = "json", Type = Text }, transportType: ServerSentEvents, path: "/dynamic")] [Test Output]
| TestLifetime Information: Starting test CanCloseStreamMethodEarly_json_ServerSentEvents_dynamic
| Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport Information: 12/15/2017 16:15:39: Connection Id 0d4c6f8b-2b23-41f7-8710-da196c550579: Starting transport. Transfer mode: Text.
| Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json'.
| Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: 12/15/2017 16:15:39: Connection Id 0d4c6f8b-2b23-41f7-8710-da196c550579: Stopping client.
| Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport Information: 12/15/2017 16:15:39: Connection Id 0d4c6f8b-2b23-41f7-8710-da196c550579: Transport is stopping.
| Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: 12/15/2017 16:15:39: Connection Id 0d4c6f8b-2b23-41f7-8710-da196c550579: Disposing client.
| Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Sending Invocation '1' failed.
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<SendAsyncCore>d__50.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<SendAsync>d__49.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.SignalR.Client.HubConnection.<SendHubMessage>d__39.MoveNext()
| TestLifetime Information: Finished test CanCloseStreamMethodEarly_json_ServerSentEvents_dynamic in 0.0113406s
```

This is not specific to the Hub, Transport or Protocol.

**Comment by davidfowl** [comment]
We made a bunch of fixes to improve this, let us know if it happens again
