### ISSUE TITLE
Unable to receive complex object

### ISSUE THREAD

**Issue by jbb352** [aspnet/SignalR#1229]
I just upgraded from alpha2 to 2.1.0-preview1-27819 and am no longer able to receive complex messages using the C# client.   The message I am sending is a simple dto class with some strings, dates and related classes.  

when sending the message I now get an error on my client "Error receiving message".  This code was working with alpha2.  I did a test of sending a simple string message and this worked as expected.

fail: Microsoft.AspNetCore.Sockets.Client.HttpConnection[15]
      12/18/2017 16:07:03: Connection Id 75b23664-3a2d-45ea-87b8-714b2900cab6: Error receiving message.
System.InvalidOperationException: Websocket closed with error: InternalServerError.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<ReceiveAsync>d__48.MoveNext()
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[11]
      Connection is shutting down due to an error.
System.InvalidOperationException: Websocket closed with error: InternalServerError.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<ReceiveAsync>d__48.MoveNext()

**Comment by jbb352** [comment]
The issue was the self-referencing object.  Not sure why this worked before. I fixed it by creating a new downstream DTO.
