### ISSUE TITLE
Flaky test: EndToEndTests.ConnectionCanSendAndReceiveMessages

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#1485]
This test has a [poor pass rate](http://aspnetci/project.html?tab=testDetails&testNameId=-192649964883647388&projectId=XPlat&buildTypeId=XPlat_Windows_Win2008r2_Universe) on Win2008 universe. It's unclear exactly what the problem is because the logging isn't informative (despite the fact that Log.Error takes an exception parameter, it doesn't use it by default). If instances like [this](http://aspnetci/viewLog.html?buildId=411473&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe#testNameId-192649964883647388) told us exactly what error occurred while sending we would know more.

CC @muratg for a flaky test.

An example failing test:
```
System.Net.WebException : The request was aborted: The request was canceled.
   at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Sockets.Client.SendUtils.<SendMessages>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.System.Threading.IAwaiter<System.IO.Pipelines.ReadResult>.GetResult()
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<ReceiveAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<ConnectionCanSendAndReceiveMessages>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<ConnectionCanSendAndReceiveMessages>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| TestLifetime Information: Starting test ConnectionCanSendAndReceiveMessages_LongPolling
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Starting connection to http://127.0.0.1:55125/echo
| Microsoft.AspNetCore.Sockets.Client.LongPollingTransport Information: Starting transport. Transfer mode: Text.
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Started connection to http://127.0.0.1:55125/echo
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Sending 9 byte message
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Sent message
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Receiving message
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Received 9 byte message
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Completed receive
| Microsoft.AspNetCore.Sockets.Client.LongPollingTransport Error: Error while sending to 'http://127.0.0.1:55125/echo?id=c2b76665-3d3f-44c5-b1da-01b8161fd667'.
|    at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
|    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
|    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
|    at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
|    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
|    at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
|    at Microsoft.AspNetCore.Sockets.Client.SendUtils.<SendMessages>d__0.MoveNext()
| Microsoft.AspNetCore.Sockets.Client.HttpConnection Error: Error receiving message.
|    at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
|    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
|    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
|    at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
|    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
|    at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
|    at Microsoft.AspNetCore.Sockets.Client.SendUtils.<SendMessages>d__0.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.IO.Pipelines.PipeCompletion.ThrowFailed()
|    at System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.System.Threading.IAwaiter<System.IO.Pipelines.ReadResult>.GetResult()
|    at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<ReceiveAsync>d__50.MoveNext()
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Test threw exception
|    at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
|    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
|    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
|    at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
|    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
|    at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
|    at Microsoft.AspNetCore.Sockets.Client.SendUtils.<SendMessages>d__0.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.IO.Pipelines.PipeCompletion.ThrowFailed()
|    at System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.System.Threading.IAwaiter<System.IO.Pipelines.ReadResult>.GetResult()
|    at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<ReceiveAsync>d__50.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__4`1.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
|    at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<ConnectionCanSendAndReceiveMessages>d__6.MoveNext()
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Disposing Connection
| Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: Disposing client.
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Disposed Connection
| TestLifetime Information: Finished test ConnectionCanSendAndReceiveMessages_LongPolling in 1.1218127s
```

**Comment by JamesNK** [comment]
I'm unable to repo the bug, even with 100 iterations. What I can cause with that is the xunit test running to break. Is signalr's use of sockets interfering?

```
The active test run was aborted. Reason: Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: state
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuat
ion(Action`1 continuation, Object state, Boolean forceAsync)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketErr
or, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.HandleCompletionPortCallbackError(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.ccto
r>b__175_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by anurse** [comment]
Yep, that's fixed in https://github.com/dotnet/corefx/pull/28637

**Comment by JamesNK** [comment]
The test has been re-enabled. Re-evaluate post preview2 to see if it is still an issue.
