### ISSUE TITLE
Cannot access a disposed object 

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#161]
After rebasing my PR on latest changes I occasionally see this failure:
```
=== TEST EXECUTION SUMMARY ===
   Microsoft.AspNetCore.SignalR.Client.FunctionalTests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 1.055s
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Microsoft.AspNetCore.SignalR.Client.FunctionalTests
  Discovered:  Microsoft.AspNetCore.SignalR.Client.FunctionalTests
  Starting:    Microsoft.AspNetCore.SignalR.Client.FunctionalTests
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.Scan() in C:\source\SignalR-Core\src\Microsoft.AspNetCore.Sockets\ConnectionManager.cs:line 81
   at Microsoft.AspNetCore.Sockets.ConnectionManager.Scan(Object state) in C:\source\SignalR-Core\src\Microsoft.AspNetCore.Sockets\ConnectionManager.cs:line 75
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Objectstate, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
SUMMARY: Total: 2 targets, Passed: 1, Failed: 1.
```

**Comment by moozzyk** [comment]
Thanks!
