### ISSUE TITLE
SignalR managed  client crash while reconnecting to server

### ISSUE THREAD

**Issue by alexiordan** [aspnet/SignalR#1612]
It happened when server was down for a 30 minutes already, and client (1.0.0-preview1-final) was trying to reconnect being configured as stated here: [What is the proper way to reconnect?](https://github.com/aspnet/SignalR/issues/1611)

Crash out of the blue with following output:

```
some messages before
...
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
WinRT information: A connection with the server could not be established

Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Net.WebSockets.Client.dll
WinRT information: A connection with the server could not be established

Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
WinRT information: A connection with the server could not be established

Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.Client.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.SignalR.Client.Core.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.Client.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in Microsoft.AspNetCore.Sockets.Client.Http.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in Microsoft.AspNetCore.Sockets.Client.Http.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
An unhandled exception of type 'System.Runtime.InteropServices.SEHException' occurred in System.Private.CoreLib.dll
External component has thrown an exception.

The program '[1768] test.exe' has exited with code -1073741795 (0xc000001d) 'Illegal Instruction'.```

**Comment by anurse** [comment]
Are these exceptions occurring on a background thread? I'm not seeing any messages, which makes it hard to tell what's going on. Are you able to catch the exceptions in the debugger (perhaps by turning on first-chance exceptions) to get more information about what is failing?

**Comment by alexiordan** [comment]
OK, I'll try do this, but is kind of nasty since even if I uncheck some exceptions types, they still are getting caught by debugger.
For the first one:
```
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
WinRT information: A connection with the server could not be established
```

I have something like this:
```
Stack:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WinRTWebSocket.<ConnectAsync>d__31.MoveNext()

Message: 
The text associated with this error code could not be found.

A connection with the server could not be established
```

I'll try catch the others also and let you know. But the crashing of the app is only encountered after some hours... 
However, let's see what can I provide.

**Comment by anurse** [comment]
Can you help me understand the issue? You mentioned that the server is down, so the exceptions you're seeing would be expected in that case, you'll need to build some logic into your application to handle cases where the server is offline (either temporarily or for a long period of time).

**Comment by alexiordan** [comment]
By crash I mean it took down the entire application. But this issue is by itself a duplicate of the one here: https://github.com/aspnet/SignalR/issues/1611 
I hoped on a simple reply on that one. But things got complicated and got to paste exceptions there too. 
So this one can be closed and only let that one. It is up to you.

**Comment by anurse** [comment]
Ok, I'll close this issue and move discussion to there.
