### ISSUE TITLE
Error when executing functional test in quick succession

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1636]
Test:
`hubConnection using json over LongPolling transport throws an exception when invoking streaming method with invoke`

Error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.AspNetCore.Sockets.ConnectionMetadata.System.Collections.Generic.IDictionary<System.Object,System.Object>.get_Item(Object key) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Abstractions\ConnectionMetadata.cs:line 29
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.ProcessSend(HttpContext context, HttpSocketOptions options) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionDispatcher.cs:line 443
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, HttpSocketOptions options, ConnectionDelegate connectionDelegate) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionDispatcher.cs:line 52
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

`DefaultConnectionContext.Items` is shared between calls and can be modified by each. Replace Dictionary with ConcurrentDictionary?

**Comment by anurse** [comment]
Yeah, we need to make sure all the data structures in `ConnectionContext` are thread-safe. Unlike `HttpContext` we expect multiple threads to use it because we dispatch invocations in parallel.
