### ISSUE TITLE
Failed disposing connection errors

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1638]
To repo:
1. Launch functional tests app via `dotnet run`
2. Run functional tests inside browser multiple times in quick succession
3. Ctrl+C functional test app
4. Multiple "Failed disposing connection" errors suddenly show up in console after "Application is shutting down..." message.

```
Failed disposing connection MYj5IW8UtWcHjqopiSSS8Q.
System.InvalidOperationException: Unable to resolve service for type 'System.Object' while attempting to activate 'FunctionalTests.UncreatableHub'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.AspNetCore.SignalR.DefaultHubActivator`1.Create() in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\DefaultHubActivator.cs:line 28
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\Internal\DefaultHubDispatcher.cs:line 41
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.RunHubAsync(HubConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\HubEndPoint.cs:line 81
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.RunHubAsync(HubConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\HubEndPoint.cs:line 88
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.OnConnectedAsync(ConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\HubEndPoint.cs:line 69
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.OnConnectedAsync(ConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\HubEndPoint.cs:line 74
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.ExecuteApplication(ConnectionDelegate connectionDelegate, ConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionDispatcher.cs:line 356
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Abstractions\DefaultConnectionContext.cs:line 185
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.DisposeAsync() in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Abstractions\DefaultConnectionContext.cs:line 169
   at Microsoft.AspNetCore.Sockets.ConnectionManager.DisposeAndRemoveAsync(DefaultConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\ConnectionManager.cs:line 228
```

I think that the error is coming from `WaitOnTasks`. Something is causing dispose to never complete until the app starts shutting down.

**Comment by anurse** [comment]
These are "expected" errors, from tests that yield an error (the tests expect the error).

**Comment by JamesNK** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Sockets.HttpConnectionContext.DisposeAsync() in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionContext.cs:line 152
   at Microsoft.AspNetCore.Sockets.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionManager.cs:line 228
```

Repo:
1. Run browser function tests multiple times from different browser windows
2. Attach a debugger to the server
3. Break points in all the `HttpConnectionManager.DisposeAndRemoveAsync` catches
4. Ctrl+C to kill the server process
5. Error is raised to breakpoint

The actual `NullReferenceException` is line 152 because `Transport` is null. `Application` is also null. See screenshot below.

Question is why does this `HttpConnectionContext` instance hang around until the server is killed? Memory leak caused by waiting forever on a lock?

If having connection contexts hang around is intentional, need to make `DisposeAsync` check for null.

![image](https://user-images.githubusercontent.com/303201/38065498-1e818922-3360-11e8-9099-84df354e13b0.png)

**Comment by BrennanConroy** [comment]
This can happen if `/negotiate` was called but then the connection didn't start the handshake and 5 seconds later the connection gets cleaned up

**Comment by anurse** [comment]
Still, we shouldn't really be null-refing :)

**Comment by davidfowl** [comment]
I'm investigating js flaky tests and looking at this as a result.

**Comment by davidfowl** [comment]
Fixed
