### ISSUE TITLE
Flaky tests: HubConnectionCanSendAndReceiveGroupMessages et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#1648]
These tests [fail](http://aspnetci/viewLog.html?buildId=422519&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) with the following message:
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Connection refused)) (The following constructor parameters did not have matching fixture data: RedisServerFixture`1 serverFixture)
---- System.AggregateException : One or more errors occurred. (Connection refused)
-------- System.Net.Sockets.SocketException : Connection refused
---- The following constructor parameters did not have matching fixture data: RedisServerFixture`1 serverFixture

----- Inner Stack Trace #1 (System.AggregateException) -----
   at Microsoft.AspNetCore.SignalR.Tests.ServerFixture`1.StartServer() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs:line 75
   at Microsoft.AspNetCore.SignalR.Tests.ServerFixture`1..ctor() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs:line 45
   at Microsoft.AspNetCore.SignalR.Redis.Tests.RedisServerFixture`1.StartServer() in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisServerFixture.cs:line 44
   at Microsoft.AspNetCore.SignalR.Redis.Tests.RedisServerFixture`1..ctor() in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisServerFixture.cs:line 36
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at StackExchange.Redis.SocketManager.BeginConnect(EndPoint endpoint, ISocketCallback callback, ConnectionMultiplexer multiplexer, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\SocketManager.cs:line 217
   at StackExchange.Redis.PhysicalConnection.BeginConnect(TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 121
   at StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalBridge.cs:line 699
   at StackExchange.Redis.ServerEndPoint.GetBridge(ConnectionType type, Boolean create, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ServerEndPoint.cs:line 184
   at StackExchange.Redis.ConnectionMultiplexer.ReconfigureAsync(Boolean first, Boolean reconfigureAll, TextWriter log, EndPoint blame, String cause, Boolean publishReconfigure, CommandFlags publishReconfigureFlags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1298
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

Future instances of this failure will be tracked [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:RedisFixture,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by anurse** [comment]
@BrennanConroy skip this and we'll review

**Comment by BrennanConroy** [comment]
I think this was because a new redis image was downloaded and took longer than 10 seconds. We should consider a less flaky way of getting new images than waiting 10 seconds and hoping or until the next build when the image will have already been downloaded by the failing build

**Comment by anurse** [comment]
We could pull the image in a separate command in the test, with a larger timeout. `docker pull redis` should no-op if we already have the latest. Also, we could pin to a specific tag/hash to ensure we don't have to update.

**Comment by anurse** [comment]
Also, could we catch this error case and throw a more meaningful error? Something like `Redis container took longer than 10 seconds to start.` (or if we `docker pull` separately: `Redis image to longer than 10 seconds to pull`)

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/e889175c0ed1c1862ef1b4f8587e5861dd5a1358
