### ISSUE TITLE
npm install from myget failing (as per readme)

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/SignalR#1661]
Is this a transient failure due to dailys moving?

https://github.com/aspnet/Announcements/issues/293

I am trying to use 28189 as it is in the aspnetboilerplate template.

```
>npm -v
5.7.1
```

```
>npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/
npm ERR! code E404
npm ERR! 404 Feed does not exist.: @aspnet/signalr@^1.0.0-preview1-28189
```
However npm view shows its there???

```
>npm view @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore-dev/npm/

{ name: '@aspnet/signalr',
  description: 'ASP.NET Core SignalR Client',
  'dist-tags': { latest: '1.0.0-preview3-30384' },
  time:
   { modified: '2018-03-20T07:42:44.44Z',
     created: '2018-01-20T02:43:22.22Z',
     '1.0.0-preview1-28129': '2018-01-20T02:43:22.22Z',
     '1.0.0-preview1-28132': '2018-01-20T04:23:08.8Z',
     '1.0.0-preview1-28133': '2018-01-21T05:13:06.6Z',
     '1.0.0-preview1-28134': '2018-01-21T18:19:24.24Z',
     '1.0.0-preview1-28135': '2018-01-21T20:34:14.14Z',
     '1.0.0-preview1-28136': '2018-01-21T22:11:49.49Z',
     '1.0.0-preview1-28137': '2018-01-22T07:41:13.13Z',
     '1.0.0-preview1-28138': '2018-01-22T19:34:20.20Z',
     '1.0.0-preview1-28139': '2018-01-22T21:19:31.31Z',
     '1.0.0-preview1-28140': '2018-01-22T22:28:22.22Z',
     '1.0.0-preview1-28143': '2018-01-23T01:38:13.13Z',
     '1.0.0-preview1-28146': '2018-01-23T05:56:14.14Z',
     '1.0.0-preview1-28148': '2018-01-23T08:35:37.37Z',
     '1.0.0-preview1-28150': '2018-01-23T18:08:42.42Z',
     '1.0.0-preview1-28151': '2018-01-23T19:59:11.11Z',
     '1.0.0-preview1-28152': '2018-01-23T20:58:31.31Z',
     '1.0.0-preview1-28153': '2018-01-23T22:06:52.52Z',
     '1.0.0-preview1-28154': '2018-01-24T00:28:34.34Z',
     '1.0.0-preview1-28155': '2018-01-24T01:15:53.53Z',
     '1.0.0-preview1-28156': '2018-01-24T02:17:52.52Z',
     '1.0.0-preview1-28158': '2018-01-24T05:17:34.34Z',
     '1.0.0-preview1-28162': '2018-01-24T18:20:12.12Z',
     '1.0.0-preview1-28166': '2018-01-24T21:29:06.6Z',
     '1.0.0-preview1-28167': '2018-01-24T23:23:15.15Z',
     '1.0.0-preview1-28168': '2018-01-25T00:20:36.36Z',
     '1.0.0-preview1-28169': '2018-01-25T02:08:48.48Z',
     '1.0.0-preview1-28177': '2018-01-25T21:42:31.31Z',
     '1.0.0-preview1-28178': '2018-01-25T22:31:05.5Z',
     '1.0.0-preview1-28179': '2018-01-26T00:15:27.27Z',
     '1.0.0-preview1-28180': '2018-01-26T02:42:25.25Z',
     '1.0.0-preview1-28183': '2018-01-26T18:04:43.43Z',
     '1.0.0-preview1-28184': '2018-01-26T19:05:44.44Z',
     '1.0.0-preview1-28185': '2018-01-26T21:06:00.0Z',
     '1.0.0-preview1-28186': '2018-01-26T22:33:21.21Z',
     '1.0.0-preview1-28189': '2018-01-27T01:13:32.32Z',
     '1.0.0-preview1-28212': '2018-01-31T19:17:45.45Z',
     '1.0.0-preview1-28213': '2018-01-31T21:31:54.54Z',
     '1.0.0-preview1-28214': '2018-01-31T22:18:56.56Z',
     '1.0.0-preview1-28215': '2018-02-01T00:19:02.2Z',
     '1.0.0-preview1-30000': '2018-02-01T03:58:08.8Z',
     '1.0.0-preview1-30001': '2018-02-01T07:45:37.37Z',
     '1.0.0-preview1-30002': '2018-02-01T09:37:08.8Z',
     '1.0.0-preview1-30003': '2018-02-01T18:05:36.36Z',
     '1.0.0-preview1-30004': '2018-02-01T19:02:21.21Z',
     '1.0.0-preview1-30005': '2018-02-01T19:49:11.11Z',
     '1.0.0-preview1-30006': '2018-02-01T20:49:28.28Z',
     '1.0.0-preview1-30007': '2018-02-01T22:56:12.12Z',
     '1.0.0-preview1-30008': '2018-02-02T00:28:13.13Z',
     '1.0.0-preview1-30011': '2018-02-02T03:09:10.10Z',
     '1.0.0-preview1-30013': '2018-02-02T04:38:14.14Z',
     '1.0.0-preview1-30014': '2018-02-02T05:38:49.49Z',
     '1.0.0-preview1-30015': '2018-02-02T08:51:10.10Z',
     '1.0.0-preview1-30017': '2018-02-02T20:48:31.31Z',
     '1.0.0-preview1-30018': '2018-02-02T22:22:11.11Z',
     '1.0.0-preview1-30019': '2018-02-03T00:09:11.11Z',
     '1.0.0-preview1-30020': '2018-02-03T01:21:19.19Z',
     '1.0.0-preview1-30024': '2018-02-03T06:31:43.43Z',
     '1.0.0-preview1-30025': '2018-02-04T06:20:15.15Z',
     '1.0.0-preview1-30026': '2018-02-04T20:39:01.1Z',
     '1.0.0-preview1-30027': '2018-02-05T06:52:25.25Z',
     '1.0.0-preview1-30028': '2018-02-05T08:59:31.31Z',
     '1.0.0-preview1-30029': '2018-02-05T18:44:55.55Z',
     '1.0.0-preview1-30030': '2018-02-05T20:01:58.58Z',
     '1.0.0-preview1-30031': '2018-02-05T21:08:40.40Z',
     '1.0.0-preview1-30032': '2018-02-05T22:31:07.7Z',
     '1.0.0-preview1-30033': '2018-02-06T00:48:18.18Z',
     '1.0.0-preview1-30037': '2018-02-06T22:13:12.12Z',
     '1.0.0-preview2-30038': '2018-02-07T00:54:55.55Z',
     '1.0.0-preview2-30039': '2018-02-07T01:26:45.45Z',
     '1.0.0-preview2-30040': '2018-02-07T02:47:45.45Z',
     '1.0.0-preview2-30041': '2018-02-07T03:37:46.46Z',
     '1.0.0-preview2-30042': '2018-02-07T04:32:12.12Z',
     '1.0.0-preview2-30043': '2018-02-07T08:04:12.12Z',
     '1.0.0-preview2-30045': '2018-02-07T09:07:59.59Z',
     '1.0.0-preview2-30046': '2018-02-07T18:52:26.26Z',
     '1.0.0-preview2-30047': '2018-02-07T20:13:04.4Z',
     '1.0.0-preview2-30048': '2018-02-07T21:29:41.41Z',
     '1.0.0-preview2-30049': '2018-02-07T22:45:57.57Z',
     '1.0.0-preview2-30057': '2018-02-08T17:10:05.5Z',
     '1.0.0-preview2-30058': '2018-02-08T18:46:12.12Z',
     '1.0.0-preview2-30059': '2018-02-09T00:24:32.32Z',
     '1.0.0-preview2-30063': '2018-02-09T03:22:14.14Z',
     '1.0.0-preview2-30064': '2018-02-09T03:45:37.37Z',
     '1.0.0-preview2-30065': '2018-02-09T04:36:12.12Z',
     '1.0.0-preview2-30066': '2018-02-09T18:51:15.15Z',
     '1.0.0-preview2-30069': '2018-02-10T00:51:57.57Z',
     '1.0.0-preview2-30070': '2018-02-10T02:48:25.25Z',
     '1.0.0-preview2-30072': '2018-02-10T23:07:25.25Z',
     '1.0.0-preview2-30073': '2018-02-11T00:57:52.52Z',
     '1.0.0-preview2-30074': '2018-02-11T04:42:50.50Z',
     '1.0.0-preview2-30075': '2018-02-11T07:27:07.7Z',
     '1.0.0-preview2-30076': '2018-02-11T08:51:39.39Z',
     '1.0.0-preview2-30077': '2018-02-11T10:23:04.4Z',
     '1.0.0-preview2-30078': '2018-02-11T23:23:11.11Z',
     '1.0.0-preview2-30079': '2018-02-12T00:50:14.14Z',
     '1.0.0-preview2-30082': '2018-02-12T23:51:56.56Z',
     '1.0.0-preview2-30083': '2018-02-13T01:44:21.21Z',
     '1.0.0-preview2-30084': '2018-02-13T03:32:10.10Z',
     '1.0.0-preview2-30085': '2018-02-13T03:55:55.55Z',
     '1.0.0-preview2-30086': '2018-02-13T04:44:33.33Z',
     '1.0.0-preview2-30087': '2018-02-13T09:11:18.18Z',
     '1.0.0-preview2-30089': '2018-02-13T20:30:09.9Z',
     '1.0.0-preview2-30092': '2018-02-13T23:11:14.14Z',
     '1.0.0-preview2-30093': '2018-02-14T00:29:45.45Z',
     '1.0.0-preview2-30099': '2018-02-14T20:33:58.58Z',
     '1.0.0-preview2-30101': '2018-02-14T22:23:49.49Z',
     '1.0.0-preview2-30102': '2018-02-14T23:49:19.19Z',
     '1.0.0-preview2-30103': '2018-02-15T00:07:53.53Z',
     '1.0.0-preview2-30105': '2018-02-15T02:34:41.41Z',
     '1.0.0-preview2-30106': '2018-02-15T16:51:19.19Z',
     '1.0.0-preview2-30113': '2018-02-16T03:51:30.30Z',
     '1.0.0-preview2-30119': '2018-02-16T22:47:00.0Z',
     '1.0.0-preview2-30120': '2018-02-16T23:32:31.31Z',
     '1.0.0-preview2-30121': '2018-02-17T00:20:27.27Z',
     '1.0.0-preview2-30122': '2018-02-17T01:28:17.17Z',
     '1.0.0-preview2-30123': '2018-02-17T02:41:34.34Z',
     '1.0.0-preview2-30124': '2018-02-17T03:06:01.1Z',
     '1.0.0-preview2-30125': '2018-02-17T04:27:13.13Z',
     '1.0.0-preview2-30126': '2018-02-17T05:22:38.38Z',
     '1.0.0-preview2-30127': '2018-02-17T05:46:42.42Z',
     '1.0.0-preview2-30129': '2018-02-18T02:07:54.54Z',
     '1.0.0-preview2-30131': '2018-02-18T02:34:30.30Z',
     '1.0.0-preview2-30132': '2018-02-19T14:03:20.20Z',
     '1.0.0-preview2-30133': '2018-02-19T17:12:18.18Z',
     '1.0.0-preview2-30136': '2018-02-19T17:22:58.58Z',
     '1.0.0-preview2-30137': '2018-02-19T19:07:18.18Z',
     '1.0.0-preview2-30138': '2018-02-19T21:24:13.13Z',
     '1.0.0-preview2-30139': '2018-02-20T02:09:24.24Z',
     '1.0.0-preview2-30141': '2018-02-20T09:52:38.38Z',
     '1.0.0-preview2-30142': '2018-02-20T10:43:45.45Z',
     '1.0.0-preview2-30143': '2018-02-20T10:54:07.7Z',
     '1.0.0-preview2-30148': '2018-02-20T23:41:55.55Z',
     '1.0.0-preview2-30149': '2018-02-21T00:10:48.48Z',
     '1.0.0-preview2-30152': '2018-02-21T01:29:29.29Z',
     '1.0.0-preview2-30153': '2018-02-21T02:29:14.14Z',
     '1.0.0-preview2-30154': '2018-02-21T03:31:36.36Z',
     '1.0.0-preview2-30155': '2018-02-21T10:35:40.40Z',
     '1.0.0-preview2-30156': '2018-02-21T16:34:01.1Z',
     '1.0.0-preview2-30157': '2018-02-21T17:44:57.57Z',
     '1.0.0-preview2-30159': '2018-02-21T21:05:35.35Z',
     '1.0.0-preview2-30161': '2018-02-22T00:47:37.37Z',
     '1.0.0-preview2-30165': '2018-02-22T04:48:25.25Z',
     '1.0.0-preview2-30166': '2018-02-22T05:36:04.4Z',
     '1.0.0-preview2-30167': '2018-02-22T06:34:18.18Z',
     '1.0.0-preview2-30168': '2018-02-22T08:45:33.33Z',
     '1.0.0-preview2-30169': '2018-02-22T11:47:53.53Z',
     '1.0.0-preview2-30171': '2018-02-22T19:16:16.16Z',
     '1.0.0-preview2-30182': '2018-02-24T00:56:12.12Z',
     '1.0.0-preview2-30183': '2018-02-24T02:17:04.4Z',
     '1.0.0-preview2-30186': '2018-02-25T19:08:29.29Z',
     '1.0.0-preview2-30187': '2018-02-26T03:38:17.17Z',
     '1.0.0-preview2-30188': '2018-02-26T20:59:11.11Z',
     '1.0.0-preview2-30189': '2018-02-26T21:56:57.57Z',
     '1.0.0-preview2-30190': '2018-02-27T02:35:35.35Z',
     '1.0.0-preview2-30192': '2018-02-27T03:28:32.32Z',
     '1.0.0-preview2-30226': '2018-03-02T23:14:56.56Z',
     '1.0.0-preview2-30229': '2018-03-03T00:53:07.7Z',
     '1.0.0-preview2-30230': '2018-03-03T02:17:41.41Z',
     '1.0.0-preview2-30232': '2018-03-05T21:29:49.49Z',
     '1.0.0-preview2-30233': '2018-03-05T22:27:23.23Z',
     '1.0.0-preview2-30236': '2018-03-06T00:55:38.38Z',
     '1.0.0-preview2-30237': '2018-03-06T01:16:57.57Z',
     '1.0.0-preview2-30238': '2018-03-06T02:10:25.25Z',
     '1.0.0-preview2-30239': '2018-03-06T02:36:12.12Z',
     '1.0.0-preview2-30240': '2018-03-06T03:06:19.19Z',
     '1.0.0-preview2-30242': '2018-03-06T03:52:09.9Z',
     '1.0.0-preview2-30245': '2018-03-06T12:17:32.32Z',
     '1.0.0-preview2-30246': '2018-03-06T19:50:08.8Z',
     '1.0.0-preview2-30247': '2018-03-06T20:56:54.54Z',
     '1.0.0-preview2-30248': '2018-03-06T21:01:14.14Z',
     '1.0.0-preview2-30252': '2018-03-07T00:28:16.16Z',
     '1.0.0-preview2-30253': '2018-03-07T02:56:45.45Z',
     '1.0.0-preview2-30254': '2018-03-07T04:07:40.40Z',
     '1.0.0-preview2-30255': '2018-03-07T04:39:01.1Z',
     '1.0.0-preview2-30257': '2018-03-07T12:11:34.34Z',
     '1.0.0-preview2-30258': '2018-03-07T14:16:02.2Z',
     '1.0.0-preview2-30259': '2018-03-07T21:06:38.38Z',
     '1.0.0-preview2-30260': '2018-03-07T21:42:58.58Z',
     '1.0.0-preview2-30261': '2018-03-07T23:00:35.35Z',
     '1.0.0-preview2-30262': '2018-03-07T23:26:21.21Z',
     '1.0.0-preview2-30263': '2018-03-08T00:40:21.21Z',
     '1.0.0-preview2-30265': '2018-03-08T02:03:28.28Z',
     '1.0.0-preview2-30266': '2018-03-08T03:13:56.56Z',
     '1.0.0-preview2-30267': '2018-03-08T04:14:46.46Z',
     '1.0.0-preview2-30268': '2018-03-08T05:04:15.15Z',
     '1.0.0-preview2-30271': '2018-03-08T19:39:49.49Z',
     '1.0.0-preview2-30272': '2018-03-08T20:30:43.43Z',
     '1.0.0-preview2-30274': '2018-03-08T21:37:13.13Z',
     '1.0.0-preview2-30277': '2018-03-09T02:47:31.31Z',
     '1.0.0-preview2-30281': '2018-03-09T18:31:37.37Z',
     '1.0.0-preview2-30282': '2018-03-09T23:30:28.28Z',
     '1.0.0-preview2-30283': '2018-03-10T01:13:26.26Z',
     '1.0.0-preview2-30284': '2018-03-10T01:26:18.18Z',
     '1.0.0-preview2-30285': '2018-03-10T02:47:31.31Z',
     '1.0.0-preview2-30296': '2018-03-12T22:30:31.31Z',
     '1.0.0-preview2-30297': '2018-03-12T23:02:33.33Z',
     '1.0.0-preview2-30299': '2018-03-13T00:09:45.45Z',
     '1.0.0-preview2-30300': '2018-03-13T01:21:05.5Z',
     '1.0.0-preview2-30301': '2018-03-13T02:04:17.17Z',
     '1.0.0-preview2-30311': '2018-03-13T20:57:10.10Z',
     '1.0.0-preview2-30319': '2018-03-14T03:01:34.34Z',
     '1.0.0-preview2-30324': '2018-03-14T16:30:52.52Z',
     '1.0.0-preview2-30325': '2018-03-14T18:14:42.42Z',
     '1.0.0-preview2-30326': '2018-03-14T18:43:23.23Z',
     '1.0.0-preview2-30327': '2018-03-14T19:37:44.44Z',
     '1.0.0-preview2-30328': '2018-03-14T21:42:01.1Z',
     '1.0.0-preview2-30331': '2018-03-14T23:16:16.16Z',
     '1.0.0-preview2-30332': '2018-03-15T00:04:20.20Z',
     '1.0.0-preview2-30333': '2018-03-15T01:04:25.25Z',
     '1.0.0-preview2-30334': '2018-03-15T01:28:35.35Z',
     '1.0.0-preview2-30335': '2018-03-15T02:26:00.0Z',
     '1.0.0-preview2-30338': '2018-03-15T20:10:56.56Z',
     '1.0.0-preview2-30349': '2018-03-16T01:49:34.34Z',
     '1.0.0-preview2-30354': '2018-03-16T04:31:40.40Z',
     '1.0.0-preview2-30355': '2018-03-16T05:24:22.22Z',
     '1.0.0-preview2-30364': '2018-03-16T20:24:47.47Z',
     '1.0.0-preview2-30365': '2018-03-16T21:03:15.15Z',
     '1.0.0-preview2-30366': '2018-03-16T21:51:16.16Z',
     '1.0.0-preview3-30379': '2018-03-20T02:14:50.50Z',
     '1.0.0-preview3-30381': '2018-03-20T04:27:05.5Z',
     '1.0.0-preview3-30382': '2018-03-20T05:12:21.21Z',
     '1.0.0-preview3-30383': '2018-03-20T06:32:36.36Z',
     '1.0.0-preview3-30384': '2018-03-20T07:42:44.44Z' },
  versions:
   [ '1.0.0-preview1-28129',
     '1.0.0-preview1-28132',
     '1.0.0-preview1-28133',
     '1.0.0-preview1-28134',
     '1.0.0-preview1-28135',
     '1.0.0-preview1-28136',
     '1.0.0-preview1-28137',
     '1.0.0-preview1-28138',
     '1.0.0-preview1-28139',
     '1.0.0-preview1-28140',
     '1.0.0-preview1-28143',
     '1.0.0-preview1-28146',
     '1.0.0-preview1-28148',
     '1.0.0-preview1-28150',
     '1.0.0-preview1-28151',
     '1.0.0-preview1-28152',
     '1.0.0-preview1-28153',
     '1.0.0-preview1-28154',
     '1.0.0-preview1-28155',
     '1.0.0-preview1-28156',
     '1.0.0-preview1-28158',
     '1.0.0-preview1-28162',
     '1.0.0-preview1-28166',
     '1.0.0-preview1-28167',
     '1.0.0-preview1-28168',
     '1.0.0-preview1-28169',
     '1.0.0-preview1-28177',
     '1.0.0-preview1-28178',
     '1.0.0-preview1-28179',
     '1.0.0-preview1-28180',
     '1.0.0-preview1-28183',
     '1.0.0-preview1-28184',
     '1.0.0-preview1-28185',
     '1.0.0-preview1-28186',
     '1.0.0-preview1-28189',
     '1.0.0-preview1-28212',
     '1.0.0-preview1-28213',
     '1.0.0-preview1-28214',
     '1.0.0-preview1-28215',
     '1.0.0-preview1-30000',
     '1.0.0-preview1-30001',
     '1.0.0-preview1-30002',
     '1.0.0-preview1-30003',
     '1.0.0-preview1-30004',
     '1.0.0-preview1-30005',
     '1.0.0-preview1-30006',
     '1.0.0-preview1-30007',
     '1.0.0-preview1-30008',
     '1.0.0-preview1-30011',
     '1.0.0-preview1-30013',
     '1.0.0-preview1-30014',
     '1.0.0-preview1-30015',
     '1.0.0-preview1-30017',
     '1.0.0-preview1-30018',
     '1.0.0-preview1-30019',
     '1.0.0-preview1-30020',
     '1.0.0-preview1-30024',
     '1.0.0-preview1-30025',
     '1.0.0-preview1-30026',
     '1.0.0-preview1-30027',
     '1.0.0-preview1-30028',
     '1.0.0-preview1-30029',
     '1.0.0-preview1-30030',
     '1.0.0-preview1-30031',
     '1.0.0-preview1-30032',
     '1.0.0-preview1-30033',
     '1.0.0-preview1-30037',
     '1.0.0-preview2-30038',
     '1.0.0-preview2-30039',
     '1.0.0-preview2-30040',
     '1.0.0-preview2-30041',
     '1.0.0-preview2-30042',
     '1.0.0-preview2-30043',
     '1.0.0-preview2-30045',
     '1.0.0-preview2-30046',
     '1.0.0-preview2-30047',
     '1.0.0-preview2-30048',
     '1.0.0-preview2-30049',
     '1.0.0-preview2-30057',
     '1.0.0-preview2-30058',
     '1.0.0-preview2-30059',
     '1.0.0-preview2-30063',
     '1.0.0-preview2-30064',
     '1.0.0-preview2-30065',
     '1.0.0-preview2-30066',
     '1.0.0-preview2-30069',
     '1.0.0-preview2-30070',
     '1.0.0-preview2-30072',
     '1.0.0-preview2-30073',
     '1.0.0-preview2-30074',
     '1.0.0-preview2-30075',
     '1.0.0-preview2-30076',
     '1.0.0-preview2-30077',
     '1.0.0-preview2-30078',
     '1.0.0-preview2-30079',
     '1.0.0-preview2-30082',
     '1.0.0-preview2-30083',
     '1.0.0-preview2-30084',
     '1.0.0-preview2-30085',
     '1.0.0-preview2-30086',
     '1.0.0-preview2-30087',
     '1.0.0-preview2-30089',
     '1.0.0-preview2-30092',
     '1.0.0-preview2-30093',
     '1.0.0-preview2-30099',
     '1.0.0-preview2-30101',
     '1.0.0-preview2-30102',
     '1.0.0-preview2-30103',
     '1.0.0-preview2-30105',
     '1.0.0-preview2-30106',
     '1.0.0-preview2-30113',
     '1.0.0-preview2-30119',
     '1.0.0-preview2-30120',
     '1.0.0-preview2-30121',
     '1.0.0-preview2-30122',
     '1.0.0-preview2-30123',
     '1.0.0-preview2-30124',
     '1.0.0-preview2-30125',
     '1.0.0-preview2-30126',
     '1.0.0-preview2-30127',
     '1.0.0-preview2-30129',
     '1.0.0-preview2-30131',
     '1.0.0-preview2-30132',
     '1.0.0-preview2-30133',
     '1.0.0-preview2-30136',
     '1.0.0-preview2-30137',
     '1.0.0-preview2-30138',
     '1.0.0-preview2-30139',
     '1.0.0-preview2-30141',
     '1.0.0-preview2-30142',
     '1.0.0-preview2-30143',
     '1.0.0-preview2-30148',
     '1.0.0-preview2-30149',
     '1.0.0-preview2-30152',
     '1.0.0-preview2-30153',
     '1.0.0-preview2-30154',
     '1.0.0-preview2-30155',
     '1.0.0-preview2-30156',
     '1.0.0-preview2-30157',
     '1.0.0-preview2-30159',
     '1.0.0-preview2-30161',
     '1.0.0-preview2-30165',
     '1.0.0-preview2-30166',
     '1.0.0-preview2-30167',
     '1.0.0-preview2-30168',
     '1.0.0-preview2-30169',
     '1.0.0-preview2-30171',
     '1.0.0-preview2-30182',
     '1.0.0-preview2-30183',
     '1.0.0-preview2-30186',
     '1.0.0-preview2-30187',
     '1.0.0-preview2-30188',
     '1.0.0-preview2-30189',
     '1.0.0-preview2-30190',
     '1.0.0-preview2-30192',
     '1.0.0-preview2-30226',
     '1.0.0-preview2-30229',
     '1.0.0-preview2-30230',
     '1.0.0-preview2-30232',
     '1.0.0-preview2-30233',
     '1.0.0-preview2-30236',
     '1.0.0-preview2-30237',
     '1.0.0-preview2-30238',
     '1.0.0-preview2-30239',
     '1.0.0-preview2-30240',
     '1.0.0-preview2-30242',
     '1.0.0-preview2-30245',
     '1.0.0-preview2-30246',
     '1.0.0-preview2-30247',
     '1.0.0-preview2-30248',
     '1.0.0-preview2-30252',
     '1.0.0-preview2-30253',
     '1.0.0-preview2-30254',
     '1.0.0-preview2-30255',
     '1.0.0-preview2-30257',
     '1.0.0-preview2-30258',
     '1.0.0-preview2-30259',
     '1.0.0-preview2-30260',
     '1.0.0-preview2-30261',
     '1.0.0-preview2-30262',
     '1.0.0-preview2-30263',
     '1.0.0-preview2-30265',
     '1.0.0-preview2-30266',
     '1.0.0-preview2-30267',
     '1.0.0-preview2-30268',
     '1.0.0-preview2-30271',
     '1.0.0-preview2-30272',
     '1.0.0-preview2-30274',
     '1.0.0-preview2-30277',
     '1.0.0-preview2-30281',
     '1.0.0-preview2-30282',
     '1.0.0-preview2-30283',
     '1.0.0-preview2-30284',
     '1.0.0-preview2-30285',
     '1.0.0-preview2-30296',
     '1.0.0-preview2-30297',
     '1.0.0-preview2-30299',
     '1.0.0-preview2-30300',
     '1.0.0-preview2-30301',
     '1.0.0-preview2-30311',
     '1.0.0-preview2-30319',
     '1.0.0-preview2-30324',
     '1.0.0-preview2-30325',
     '1.0.0-preview2-30326',
     '1.0.0-preview2-30327',
     '1.0.0-preview2-30328',
     '1.0.0-preview2-30331',
     '1.0.0-preview2-30332',
     '1.0.0-preview2-30333',
     '1.0.0-preview2-30334',
     '1.0.0-preview2-30335',
     '1.0.0-preview2-30338',
     '1.0.0-preview2-30349',
     '1.0.0-preview2-30354',
     '1.0.0-preview2-30355',
     '1.0.0-preview2-30364',
     '1.0.0-preview2-30365',
     '1.0.0-preview2-30366',
     '1.0.0-preview3-30379',
     '1.0.0-preview3-30381',
     '1.0.0-preview3-30382',
     '1.0.0-preview3-30383',
     '1.0.0-preview3-30384' ],
  version: '1.0.0-preview3-30384',
  main: './dist/cjs/index.js',
  module: './dist/esm/index.js',
  typings: './dist/esm/index.d.ts',
  umd: './dist/browser/signalr.js',
  umd_name: 'signalR',
  directories: { test: 'spec' },
  scripts:
   { clean: 'node ../node_modules/rimraf/bin.js ./dist ./.rpt2_cache',
     build: 'npm run clean && npm run build:lint && npm run build:esm && npm run build:cjs && npm run build:browser && npm run build:uglify',
     'build:lint': 'node ../node_modules/tslint/bin/tslint -c ../tslint.json -p ./tsconfig.json',
     'build:esm': 'node ../node_modules/typescript/bin/tsc --project ./tsconfig.json --module es2015 --outDir ./dist/esm --target ES2015 -d && node ./build/process-dts.js',
     'build:cjs': 'node ../node_modules/typescript/bin/tsc --project ./tsconfig.json --module commonjs --outDir ./dist/cjs --target ES5',
     'build:browser': 'node ../node_modules/rollup/bin/rollup -c',
     'build:uglify': 'node ../node_modules/uglify-js/bin/uglifyjs --source-map "url=\'signalr.min.js.map\',content=\'./dist/browser/signalr.js.map\'" --comments -o ./dist/browser/signalr.min.js ./dist/browser/signalr.js',
     pretest: 'node ../node_modules/rimraf/bin.js ./spec/obj && node ../node_modules/typescript/bin/tsc --project ./spec/tsconfig.json',
     test: 'node ../node_modules/jasmine/bin/jasmine.js ./spec/obj/spec/**/*.spec.js' },
  repository:
   { type: 'git',
     url: 'git+https://github.com/aspnet/SignalR.git' },
  author: 'Microsoft',
  license: 'Apache-2.0',
  bugs: { url: 'https://github.com/aspnet/SignalR/issues' },
  homepage: 'https://github.com/aspnet/SignalR#readme',
  files: [ 'dist/**/*', 'src/**/*' ],
  devDependencies: { 'es6-promise': '^4.2.2' },
  dist:
   { shasum: '952c084c3e71acba74f8413dbb658eec3ed838e1',
     tarball: 'https://dotnet.myget.org/F/aspnetcore-dev/npm/@aspnet/signalr/-/@aspnet/signalr-1.0.0-preview3-30384.tgz' } }
```

**Comment by anurse** [comment]
I'm not able to reproduce this. It's possible there's a network issue on your end or with the MyGet registry. It could be that the services needed to download the package are/were not available, but the services needed to `npm view` are working.

**Comment by mikes-gh** [comment]
Well I have checked proxy wireshark etc it all appears to be as it should.

Would you mind posting your output from

````
>npm install @aspnet/signalr --registry https://dotnet.myget.org/f/aspnetcore--dev/npm/ --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\mikes\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '@aspnet/signalr',
npm verb cli   '--registry',
npm verb cli   'https://dotnet.myget.org/f/aspnetcore--dev/npm/',
npm verb cli   '--verbose' ]
npm info using npm@5.7.1
npm info using node@v8.10.0
npm verb npm-session 26180231c976e8d7
npm http fetch GET 404 https://dotnet.myget.org/f/aspnetcore--dev/npm/@aspnet%2fsignalr 918ms
npm verb stack Error: 404 Feed does not exist.: @aspnet/signalr@1.0.0-preview1-28189
npm verb stack     at fetch.then.res (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (C:\Users\mikes\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:794:20)
npm verb stack     at tryOnImmediate (timers.js:752:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
npm verb cwd C:\Users\mikes\Repos\boiler\angular
npm verb Windows_NT 6.1.7601
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mikes\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@aspnet/signalr" "--registry" "https://dotnet.myget.org/f/aspnetcore--dev/npm/" "--verbose"
npm verb node v8.10.0
npm verb npm  v5.7.1
npm ERR! code E404
npm ERR! 404 Feed does not exist.: @aspnet/signalr@1.0.0-preview1-28189
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mikes\AppData\Roaming\npm-cache\_logs\2018-03-20T15_17_28_795Z-debug.log
```

Thanks

**Comment by mikes-gh** [comment]
Sorry due to 
1.  package.lock.json and 
2,  a typo in the registry anme (2 dashes)
