### ISSUE TITLE
Flaky test: hubConnection using messagepack over LongPolling transport can be restarted

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1717]
Seeing this javascript test flake out in the last 3 PR runs.

**Comment by davidfowl** [comment]
Happened again:

```
     - message: Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    ...
  not ok 74 hubConnection using messagepack over LongPolling transport can be restarted
    ---
      - message: Expected Error: Server returned handshake error: Handshake was canceled. to be undefined.
        operator: toBe
        actual: Error: Server returned handshake error: Handshake was canceled.
      - message: Failed: Server returned handshake error: Handshake was canceled.
```

**Comment by anurse** [comment]
> Error: Server returned handshake error: Handshake was canceled.

This indicates that the server canceled the handshake. It's possible the client simply failed to send the request, but it could also mean the server failed to send it in time. Also, as I mentioned in #1737 , this error breaks the pipe because of the (now fixed) corefx bug.

**Comment by davidfowl** [comment]
Are we passing the token into WriteAsync here? Lets just remove it and see if it works then.

**Comment by anurse** [comment]
I'll just do a pass yanking tokens our then.

**Comment by anurse** [comment]
I was wrong, it uses the token in `ReadAsync`, not `WriteAsync`.

**Comment by anurse** [comment]
Though the odd thing there is that if we sent "Handshake was canceled" it's because we timed out on that `ReadAsync` which means we've never processed a Handshak request.

**Comment by davidfowl** [comment]
I just saw this error and something occurred to me:

```
Failed   Microsoft.AspNetCore.SignalR.Redis.Tests.RedisEndToEndTests.HubConnectionCanSendAndReceiveGroupMessages(transportType: LongPolling, protocol: MessagePackHubProtocol { Name = "messagepack", SerializationContext = SerializationContext { CompatibilityOptions = SerializationCompatibilityOptions { ... }, DefaultCollectionTypes = DefaultConcreteTypeRepository { ... }, DefaultDateTimeConversionMethod = Timestamp, DictionarySerlaizationOptions = DictionarySerlaizationOptions { ... }, EnumSerializationMethod = ByName, ... }, TransferFormat = Binary, Version = 1 })
Error Message:
 System.TimeoutException : Operation in HubConnectionCanSendAndReceiveGroupMessages timed out at /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs:76
Stack Trace:
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext() in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Redis.Tests.RedisEndToEndTests.<HubConnectionCanSendAndReceiveGroupMessages>d__3.MoveNext() in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Standard Output Messages:
 | [2018-03-31T05:33:42] TestLifetime Information: Starting test HubConnectionCanSendAndReceiveGroupMessages_LongPolling_messagepack
 | [2018-03-31T05:33:42] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Starting transport. Transfer mode: Binary.
 | [2018-03-31T05:33:42] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
 | [2018-03-31T05:33:42] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'messagepack v1'.
 | [2018-03-31T05:33:42] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
 | [2018-03-31T05:33:42] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Starting transport. Transfer mode: Binary.
 | [2018-03-31T05:33:42] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
 | [2018-03-31T05:33:42] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'messagepack v1'.
 | [2018-03-31T05:33:47] TestLifetime Information: Finished test HubConnectionCanSendAndReceiveGroupMessages_LongPolling_messagepack in 5.005922s
 | [2018-03-31T05:33:47] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Server returned handshake error: Handshake was canceled.
```

We start waiting for the handshake when the poll is sent (first poll), that kicks off the HubConnectionHandler, https://github.com/aspnet/SignalR/blob/90aa48c09f79fe7c0f3c0e8aeb420816ec15c7f0/src/Microsoft.AspNetCore.Http.Connections/HttpConnectionDispatcher.cs#L226. We schedule that to execute on the thread pool which will set the countdown for the handshake and wait for data. The request hasn't returned yet BTW and time is ticking down. The client now has to send the handshake before the server cancels. 

Maybe we can flush the response on the first request before waiting on the handshake request so the the client and send it as soon as possible. I think we should try to fix this for preview2.

/cc @muratg

**Comment by anurse** [comment]
Maybe it's also worth increasing the default timeout a bit. It's configurable too, right?

**Comment by anurse** [comment]
I see you already did that ;)

**Comment by davidfowl** [comment]
I'm going to close this until we see errors popup again after the timeout increase.

**Comment by JamesNK** [comment]
It's back:

https://travis-ci.org/aspnet/SignalR/jobs/364911071#L1234

https://travis-ci.org/aspnet/SignalR/jobs/364910777#L1422

**Comment by davidfowl** [comment]
I don’t think this is the same thing?

**Comment by JamesNK** [comment]
I'll create a new one https://github.com/aspnet/SignalR/issues/1944
