### ISSUE TITLE
Flaky tests: TransportThatFailsToStartOnceFallsBack

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#1726]
[This test](http://aspnetci/viewLog.html?buildId=430868&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId4523811534513378872) started to fail recently:
```
System.InvalidOperationException : Unable to connect to the server with any of the available transports.
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<StartAsyncInternal>d__46.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\SignalR\src\Microsoft.AspNetCore.Sockets.Client.Http\HttpConnection.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<StartAsync>d__43.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\SignalR\src\Microsoft.AspNetCore.Sockets.Client.Http\HttpConnection.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.Tests.HttpConnectionTests.ConnectionLifecycle.<>c__DisplayClass5_1.<<TransportThatFailsToStartOnceFallsBack>b__1>d.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\SignalR\test\Microsoft.AspNetCore.SignalR.Client.Tests\HttpConnectionTests.ConnectionLifecycle.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.Tests.HttpConnectionTests.<WithConnectionAsync>d__11.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\SignalR\test\Microsoft.AspNetCore.SignalR.Client.Tests\HttpConnectionTests.Helpers.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.Client.Tests.HttpConnectionTests.<WithConnectionAsync>d__11.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\SignalR\test\Microsoft.AspNetCore.SignalR.Client.Tests\HttpConnectionTests.Helpers.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.Tests.HttpConnectionTests.ConnectionLifecycle.<TransportThatFailsToStartOnceFallsBack>d__5.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\SignalR\test\Microsoft.AspNetCore.SignalR.Client.Tests\HttpConnectionTests.ConnectionLifecycle.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Future instances of this failure will appear [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:AvailableTransports,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

I believe that the failure of `StartThrowsAfterAllTransportsFail` with
```
Assert.Equal() Failure
Expected: 3
Actual:   2
```
is caused by the same issue, so I'm not filing a separate bug for it, but if it's not we'll have to create one.

**Comment by davidfowl** [comment]
@mikaelm12 looks like your changes

**Comment by mikaelm12** [comment]
Yeah, I'll take a lot at these

**Comment by mikaelm12** [comment]
This should fix these failures: c631b87c6d4f2c1e9a4f06d97a1a6693e48d8242
I'll wait to close this till I see them pass on Win7 and Win2008 tomorrow.

**Comment by mikaelm12** [comment]
Just added this commit: eb2fa9bacd35359728bee6963e584e1fa81c993a
which is also related. Gonna close this issue since I'm pretty confident those changes should solve it.
I'll reopen this if the problem persists.

**Comment by ryanbrandenburg** [comment]
Saw this failure [this](http://aspnetci/viewLog.html?buildId=435269&buildTypeId=XPlat_Windows_Win2008r2_Universe) morning.

**Comment by mikaelm12** [comment]
That's a different test. It's being tracked here https://github.com/aspnet/SignalR/issues/1629
Working on a fix for that now 😄
