### ISSUE TITLE
Flaky test: Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1752]
```
[xUnit.net 00:00:10.4282750]     Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled(protocolName: "messagepack", transportType: LongPolling, path: "/default") [FAIL]
[xUnit.net 00:00:10.4299760]       System.ObjectDisposedException : Cannot access a disposed object.
[xUnit.net 00:00:10.4300950]       Object name: 'HttpConnection'.
[xUnit.net 00:00:10.4313110]       Stack Trace:
[xUnit.net 00:00:10.4326830]         /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs(428,0): at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.CheckDisposed()
[xUnit.net 00:00:10.4328270]         /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs(54,0): at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.get_Transport()
[xUnit.net 00:00:10.4329110]         /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs(923,0): at Microsoft.AspNetCore.SignalR.Client.HubConnection.ConnectionState.StopAsyncCore(TimeSpan timeout)
[xUnit.net 00:00:10.4329800]         /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs(202,0): at Microsoft.AspNetCore.SignalR.Client.HubConnection.StopAsyncCore(Boolean disposing)
[xUnit.net 00:00:10.4330400]         /Users/dfowler/dev/SignalR/src/Common/ForceAsyncAwaiter.cs(40,0): at Microsoft.AspNetCore.Sockets.Internal.ForceAsyncAwaiter.GetResult()
[xUnit.net 00:00:10.4331150]         /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs(82,0): at Microsoft.AspNetCore.SignalR.Client.HubConnection.DisposeAsync()
[xUnit.net 00:00:10.4332130]         /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs(35,0): at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber)
[xUnit.net 00:00:10.4334160]         /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs(399,0): at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled(String protocolName, TransportType transportType, String path)
[xUnit.net 00:00:10.4334800]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.4353490]       Output:
[xUnit.net 00:00:10.4354610]         | [2018-03-28T13:27:02] TestLifetime Information: Starting test StreamDoesNotStartIfTokenAlreadyCanceled_messagepack_LongPolling_default
[xUnit.net 00:00:10.4355000]         | [2018-03-28T13:27:02] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:120).
[xUnit.net 00:00:10.4355470]         | [2018-03-28T13:27:02] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
[xUnit.net 00:00:10.4355790]         | [2018-03-28T13:27:02] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Starting HttpConnection.
[xUnit.net 00:00:10.4356130]         | [2018-03-28T13:27:02] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:61606/default'.
[xUnit.net 00:00:10.4356450]         | [2018-03-28T13:27:02] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default/negotiate'.
[xUnit.net 00:00:10.4356840]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Established connection '7lRyC0_jGdf5uuRxSE4ZZQ' with the server.
[xUnit.net 00:00:10.4357200]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Skipping transport WebSockets because it was disabled by the client.
[xUnit.net 00:00:10.4357540]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Skipping transport ServerSentEvents because it was disabled by the client.
[xUnit.net 00:00:10.4357890]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Starting transport 'LongPolling' with Url: http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ.
[xUnit.net 00:00:10.4358260]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Information: Starting transport. Transfer mode: Binary.
[xUnit.net 00:00:10.4358610]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Starting receive loop.
[xUnit.net 00:00:10.4358950]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ'.
[xUnit.net 00:00:10.4359310]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Starting the send loop.
[xUnit.net 00:00:10.4359640]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Information: HttpConnection Started.
[xUnit.net 00:00:10.4360010]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'messagepack v1'.
[xUnit.net 00:00:10.4360410]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
[xUnit.net 00:00:10.4360750]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Sending 39 bytes to the server using url: http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ.
[xUnit.net 00:00:10.4361110]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ'.
[xUnit.net 00:00:10.4361460]         | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Message(s) sent successfully.
[xUnit.net 00:00:10.4361800]         | [2018-03-28T13:27:07] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: System.TimeoutException from test
[xUnit.net 00:00:10.4362160]         |    at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 33
[xUnit.net 00:00:10.4362570]         |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled(String protocolName, TransportType transportType, String path) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 382
[xUnit.net 00:00:10.4362950]         | [2018-03-28T13:27:07] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StopAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:170).
[xUnit.net 00:00:10.4363330]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Trace: Poll response with status code 200 received from server. Content length: 36.
[xUnit.net 00:00:10.4363740]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Received messages from the server.
[xUnit.net 00:00:10.4364120]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ'.
[xUnit.net 00:00:10.4364580]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Trace: Poll response with status code 204 received from server. Content length: 0.
[xUnit.net 00:00:10.4364950]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: The server is closing the connection.
[xUnit.net 00:00:10.4365280]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Receive loop stopped.
[xUnit.net 00:00:10.4365640]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Send loop canceled.
[xUnit.net 00:00:10.4365990]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Send loop stopped.
[xUnit.net 00:00:10.4366310]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Transport stopped.
[xUnit.net 00:00:10.4366650]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Server returned handshake error: Handshake was canceled.
[xUnit.net 00:00:10.4366990]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Error processing the handshake response.
[xUnit.net 00:00:10.4367330]         |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 533
[xUnit.net 00:00:10.4367700]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Error starting connection.
[xUnit.net 00:00:10.4368020]         |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 533
[xUnit.net 00:00:10.4368380]         |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 143
[xUnit.net 00:00:10.4368740]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Disposing HttpConnection.
[xUnit.net 00:00:10.4369120]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Information: Transport is stopping.
[xUnit.net 00:00:10.4369470]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Information: HttpConnection Disposed.
[xUnit.net 00:00:10.4369790]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StartAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:159).
[xUnit.net 00:00:10.4370160]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StopAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:196).
[xUnit.net 00:00:10.4370570]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Stopping HubConnection.
[xUnit.net 00:00:10.4370900]         | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Terminating receive loop.
[xUnit.net 00:00:10.4371250]         | [2018-03-28T13:27:08] TestLifetime Information: Finished test StreamDoesNotStartIfTokenAlreadyCanceled_messagepack_LongPolling_default in 5.834269s
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled(protocolName: "messagepack", transportType: LongPolling, path: "/default")
Error Message:
 System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'HttpConnection'.
Stack Trace:
   at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.CheckDisposed() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs:line 428
   at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.get_Transport() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.Sockets.Client.Http/HttpConnection.cs:line 54
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ConnectionState.StopAsyncCore(TimeSpan timeout) in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 923
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StopAsyncCore(Boolean disposing) in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 202
   at Microsoft.AspNetCore.Sockets.Internal.ForceAsyncAwaiter.GetResult() in /Users/dfowler/dev/SignalR/src/Common/ForceAsyncAwaiter.cs:line 40
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.DisposeAsync() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 82
   at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 35
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled(String protocolName, TransportType transportType, String path) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 399
--- End of stack trace from previous location where exception was thrown ---
Standard Output Messages:
 | [2018-03-28T13:27:02] TestLifetime Information: Starting test StreamDoesNotStartIfTokenAlreadyCanceled_messagepack_LongPolling_default
 | [2018-03-28T13:27:02] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:120).
 | [2018-03-28T13:27:02] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
 | [2018-03-28T13:27:02] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Starting HttpConnection.
 | [2018-03-28T13:27:02] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:61606/default'.
 | [2018-03-28T13:27:02] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default/negotiate'.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Established connection '7lRyC0_jGdf5uuRxSE4ZZQ' with the server.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Skipping transport WebSockets because it was disabled by the client.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Skipping transport ServerSentEvents because it was disabled by the client.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Starting transport 'LongPolling' with Url: http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Information: Starting transport. Transfer mode: Binary.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Starting receive loop.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ'.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Starting the send loop.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Information: HttpConnection Started.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'messagepack v1'.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Sending 39 bytes to the server using url: http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ'.
 | [2018-03-28T13:27:03] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Message(s) sent successfully.
 | [2018-03-28T13:27:07] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: System.TimeoutException from test
 |    at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 33
 |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled(String protocolName, TransportType transportType, String path) in /Users/dfowler/dev/SignalR/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 382
 | [2018-03-28T13:27:07] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StopAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:170).
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Trace: Poll response with status code 200 received from server. Content length: 36.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Received messages from the server.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Http.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request to 'http://127.0.0.1:61606/default?id=7lRyC0_jGdf5uuRxSE4ZZQ'.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Trace: Poll response with status code 204 received from server. Content length: 0.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: The server is closing the connection.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Receive loop stopped.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Send loop canceled.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Send loop stopped.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Debug: Transport stopped.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Server returned handshake error: Handshake was canceled.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Error processing the handshake response.
 |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 533
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Error starting connection.
 |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 533
 |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore() in /Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 143
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Debug: Disposing HttpConnection.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Internal.LongPollingTransport Information: Transport is stopping.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection Information: HttpConnection Disposed.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StartAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:159).
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StopAsyncCore (/Users/dfowler/dev/SignalR/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:196).
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Stopping HubConnection.
 | [2018-03-28T13:27:08] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Terminating receive loop.
 | [2018-03-28T13:27:08] TestLifetime Information: Finished test StreamDoesNotStartIfTokenAlreadyCanceled_messagepack_LongPolling_default in 5.834269s
```

**Comment by ryanbrandenburg** [comment]
@davidfowl thanks for creating this, can you add flaky test issues to the Infrastructure project when you create them so I can keep track?

**Comment by davidfowl** [comment]
@ryanbrandenburg will do

**Comment by BrennanConroy** [comment]
We increased the Jasmine test timeouts because LongPolling can take sometime to do the whole handshake process, closing for now, we can reopen if the test fails again
