### ISSUE TITLE
Writing is not allowed after writer was completed

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1758]
```
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.EnsureBuffer() in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Common\Internal\Protocol\Utf8BufferTextWriter.cs:line 140
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.GetBuffer() in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Common\Internal\Protocol\Utf8BufferTextWriter.cs:line 125
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.Utf8BufferTextWriter.Write(Char value) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Common\Internal\Protocol\Utf8BufferTextWriter.cs:line 90
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HandshakeProtocol.WriteResponseMessage(HandshakeResponseMessage responseMessage, IBufferWriter`1 output) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Common\Internal\Protocol\HandshakeProtocol.cs:line 52
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteHandshakeResponseAsync(HandshakeResponseMessage message) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\HubConnectionContext.cs:line 204
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.HandshakeAsync(TimeSpan timeout, IList`1 supportedProtocols, IHubProtocolResolver protocolResolver, IUserIdProvider userIdProvider) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\HubConnectionContext.cs:line 329
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.SignalR.Core\HubConnectionHandler.cs:line 62
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.ExecuteApplication(ConnectionDelegate connectionDelegate, ConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionDispatcher.cs:line 377
   at Microsoft.AspNetCore.Sockets.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionContext.cs:line 200
   at Microsoft.AspNetCore.Sockets.HttpConnectionContext.DisposeAsync() in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionContext.cs:line 178
   at Microsoft.AspNetCore.Sockets.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionManager.cs:line 228
```

Repo:
1. Run browser function tests
2. Attach debugger to server
3. Break points in all the `HttpConnectionManager.DisposeAndRemoveAsync` catches

This error isn't causing the tests to fail but should it even be thrown?

**Comment by davidfowl** [comment]
I need to rework this code to be more like the client each side owns their side of the connection. We should only dispose the other side after a timeout or something similar. I’ll take this one

**Comment by davidfowl** [comment]
I'll take this one.
