### ISSUE TITLE
Failed disposing connection

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1759]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Sockets.HttpConnectionContext.DisposeAsync() in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionContext.cs:line 152
   at Microsoft.AspNetCore.Sockets.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection) in C:\Development\Source\SignalR\src\Microsoft.AspNetCore.Sockets.Http\HttpConnectionManager.cs:line 228
```

Repo:
1. Run browser function tests multiple times from different browser windows
2. Attach a debugger to the server
3. Break points in all the `HttpConnectionManager.DisposeAndRemoveAsync` catches
4. Ctrl+C to kill the server process
5. Error is raised to breakpoint

The actual `NullReferenceException` is line 152 because `Transport` is null. `Application` is also null. See screenshot below.

Question is why does this `HttpConnectionContext` instance hang around until the server is killed? Memory leak caused by waiting forever on a lock?

If having connection contexts hang around is intentional, need to make `DisposeAsync` check for null.

![image](https://user-images.githubusercontent.com/303201/38065498-1e818922-3360-11e8-9099-84df354e13b0.png)

**Comment by JamesNK** [comment]
Dupe of https://github.com/aspnet/SignalR/issues/1638 (also by me...)
