### ISSUE TITLE
NullRef in StartTransport (C# Client)

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#1826]
This happens occasionally when I spin up many connections.

Looking at the code, this doesn't even seem possible...
```
[09:00:55.958] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.Log.ErrorStartingTransport(ILogger logger, ITransport transport, Exception exception)
   at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.<StartTransport>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.<SelectAndStartTransport>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.<StartAsyncCore>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.Http.HttpConnection.<StartAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BenchmarksClient.Workers.SignalRWorker.<StartAsync>d__17.MoveNext() in /home/brecon/benchmarks/src/BenchmarksClient/Workers/SignalRWorker.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BenchmarkClient.Startup.<ProcessJobs>d__8.MoveNext() in /home/brecon/benchmarks/src/BenchmarksClient/Startup.cs:line 125

```

**Comment by anurse** [comment]
Are you still seeing this? I thought it went away when you updated the code?

**Comment by BrennanConroy** [comment]
Can't repro after updating to latest client, there were changes in the HttpConnection code that looks like it could have resolved it.
