### ISSUE TITLE
Websocket closed with status code: 1011 () by Could not load type 'System.SpanExtensions'

### ISSUE THREAD

**Issue by topnguyen** [aspnet/SignalR#1847]
I face the issue cannot connect by server throw exception when the client start connection.

I use Socket Javascript client (`signalr-clientES5-1.0.0-alpha2-final.js`)

The stack trade is below.

Thank for your support time.

```csharp
Microsoft.AspNetCore.Sockets.ConnectionManager:Error: 04/04/2018 23:50:09: ConnectionId b3fa3d40-7549-4fb4-bc5d-0fbc17dd70b8: Failed disposing connection.

System.TypeLoadException: Could not load type 'System.SpanExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Microsoft.AspNetCore.SignalR.Internal.Formatters.TextMessageParser.TryParseMessage(ReadOnlyBuffer`1& buffer, ReadOnlyBuffer`1& payload)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.NegotiationProtocol.TryParseMessage(ReadOnlyBuffer`1 input, NegotiationMessage& negotiationMessage)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<ProcessNegotiate>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteApplication>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()
```

**Comment by anurse** [comment]
What versions of the server packages are you using? Also, what framework are you targeting (.NET Core 2.1?).

Please note that the `alpha1` release is out-of-date and no longer supported. You should upgrade the server to ASP.NET Core 2.1-preview1 and change the client to use the `@aspnet/signalr` package in the JavaScript client (Note the package has been **renamed**; it was `@aspnet/signalr-client` in alpha1 but is `@aspnet/signalr` in preview 1)

**Comment by topnguyen** [comment]
Thank @anurse,
I'm use .Net Core 2.0.  I will try to upgrade to .Net Core 2.1-preview 1 and use the new client `@aspnet/signalr-client` as you mention. If the issue is gone I will close this issue.

**Comment by topnguyen** [comment]
It's work like a charm when I upgrade project to `2.1.0-preview1-final` and SignalR version `1.0.0-preview1-final`. I see more consistency between client and server SDK - Send Message by method named `SendAsync` in both side.

Thank for you support again @anurse

**Comment by xoapit** [comment]
I have the same issue when I host a signalR server. In my case, I build the server by .net core 2.0 and host the server by dotnet hosting 2.1. That's the reason I have this error. I tried to uninstall dotnet hosting 2.1 and reinstall 2.0.9. It works for me.
