### ISSUE TITLE
CanStartConnectionFromClosedEvent 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1858]
A timeout was observed in this PR https://travis-ci.org/aspnet/SignalR/jobs/362365310. Related to the C# client. We can wait to see if we see it more than once before declaring it flaky but we might need to start looking at the .NET client for flaky tests.

The strange thing here is that the test run was aborted, which usually means something is throwing on a background thread (it might not be related to this test).

```
The active test run was aborted. Reason: Unhandled Exception: System.TimeoutException: Operation in CanStartConnectionFromClosedEvent timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:176
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<>c__DisplayClass7_0.<<CanStartConnectionFromClosedEvent>b__0>d.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Total tests: Unknown. Passed: 1110. Failed: 0. Skipped: 2.
```

**Comment by BrennanConroy** [comment]
Just got it again https://travis-ci.org/aspnet/SignalR/jobs/362723877

**Comment by davidfowl** [comment]
```
[xUnit.net 00:00:15.4180940]     Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(protocolName: "json", transportType: WebSockets, path: "/default") [FAIL]
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(protocolName: "json", transportType: WebSockets, path: "/default")
Error Message:
 System.TimeoutException : Operation in CanStartConnectionFromClosedEvent timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:195
Stack Trace:
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CanStartConnectionFromClosedEvent>d__7.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CanStartConnectionFromClosedEvent>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Standard Output Messages:
 | [2018-04-05T16:57:52] TestLifetime Information: Starting test CanStartConnectionFromClosedEvent_json_WebSockets_default
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:115).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'WebSockets' with Url: http://127.0.0.1:50990/default.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:50990/default'.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Transport 'WebSocketsTransport' started.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json v1'.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 32.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 3, EndOfMessage: True.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Handshake with server complete.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Receive loop starting.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting server timeout timer. Duration: 30000.00ms
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:158).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in InvokeAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:264).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 created.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Preparing blocking invocation '1' of 'Echo', with return type 'System.String' and 1 argument(s).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering Invocation ID '1' for tracking.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Issuing Invocation '1': System.String Echo(System.String).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending InvocationMessage message '1'.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending InvocationMessage message '1' completed.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 70.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in InvokeAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:277).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 49, EndOfMessage: True.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Resetting keep-alive timer, received a message from the server.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Processing 49 byte message from server.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Received Completion for Invocation 1.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 marked as completed.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 disposed.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Stopping connection
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:169).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:196).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Stopping HubConnection.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Terminating receive loop.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Waiting for the receive loop to terminate.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:648).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:657).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Disposing HttpConnection.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Transport is stopping.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Send loop stopped.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Transport stopped.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Disposed.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Canceling all outstanding invocations.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Shutting down connection.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: HubConnection stopped.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Waiting for reconnect
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Invoking the Closed event handler.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Closed event triggered
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Restarting connection
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:115).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'WebSockets' with Url: http://127.0.0.1:50990/default.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:50990/default'.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Receive loop canceled.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Receive loop stopped.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Transport 'WebSocketsTransport' started.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json v1'.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 32.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 3, EndOfMessage: True.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Handshake with server complete.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Receive loop starting.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting server timeout timer. Duration: 30000.00ms
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:158).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Restarted connection
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Reconnection complete
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in InvokeAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:264).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 created.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Preparing blocking invocation '1' of 'Echo', with return type 'System.String' and 1 argument(s).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering Invocation ID '1' for tracking.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Issuing Invocation '1': System.String Echo(System.String).
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending InvocationMessage message '1'.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending InvocationMessage message '1' completed.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 70.
 | [2018-04-05T16:57:52] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in InvokeAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:277).
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: System.TimeoutException from test
 |    at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__6`1.MoveNext()
 | --- End of stack trace from previous location where exception was thrown ---
 |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CanStartConnectionFromClosedEvent>d__7.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 195
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:169).
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:196).
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Stopping HubConnection.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Terminating receive loop.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Waiting for the receive loop to terminate.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:648).
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:657).
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Disposing HttpConnection.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Transport is stopping.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Send loop stopped.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Transport stopped.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Disposed.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Canceling all outstanding invocations.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Removing pending invocation 1.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Receive loop canceled.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.InvocationRequest.NonStreaming Trace: Invocation 1 disposed.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Receive loop stopped.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Shutting down connection.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: HubConnection stopped.
 | [2018-04-05T16:57:57] TestLifetime Information: Finished test CanStartConnectionFromClosedEvent_json_WebSockets_default in 5.19243s
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Invoking the Closed event handler.
 | [2018-04-05T16:57:57] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Closed event triggered
```

**Comment by JamesNK** [comment]
Boop https://travis-ci.org/aspnet/SignalR/jobs/362856279

**Comment by davidfowl** [comment]
The crash was fixed here https://github.com/aspnet/SignalR/commit/39f693b9ed9b6869c57af291b4ecaaf15b889e3b

**Comment by anurse** [comment]
So can this be closed then?

**Comment by BrennanConroy** [comment]
But @JamesNK link was after that change

**Comment by muratg** [comment]
Triage: Add logging on client and server and keep running. Costing updated based on this.

**Comment by JamesNK** [comment]
I haven't seen this test fail in a long time. Close?

**Comment by davidfowl** [comment]
Yep
