### ISSUE TITLE
NullReferenceException thrown when unable to connect to a SignalR Hub

### ISSUE THREAD

**Issue by conniey** [aspnet/SignalR#1887]
## Issue
I am benchmarking my chatroom application by first, joining all the users to the same chatroom, then sending a message and seeing how long it takes for that message to come back. It works fine until I get to 750 - 1000 users.  This is when I start seeing the `NullReferenceException` exception as the client tries to start the HubConnection and join the same room (which is a "Group").

## Server Side diagnostic logs
https://1drv.ms/u/s!AlGDh95zLvCeiJwITe9WH3RExEB78w

## Client-Side Server Side
```
2018-04-06 19:12:21.029 +00:00 [Fatal] Failed while running test.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ThrowIfConnectionTerminated(String invocationId)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCore(String methodName, InvocationRequest irq, Object[] args)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsyncCore>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

## Information
* Server-Side NuGet: 
  * Microsoft.AspNetCore.SignalR, Version=1.0.0-preview1-final
* Client-Side Information:
   * Microsoft.AspNetCore.SignalR.Client, Version=1.0.0-preview1-final
   * Microsoft.AspNetCore.SignalR.Redis, Version=1.0.0-preview1-final
   * C# Client
* The Server you are using: Azure App Service
* The Operating System on the Server (Windows): Windows, and whichever Azure App Service gives us.
* The Operating System on the Client: Windows 10 Enterprise
* If possible, please collect Network Traces and attach them (please do not post them inline, use a service like [Gist](https://gist.github.com) to upload them and link them in the issue)

**Comment by anurse** [comment]
A lot of this code has changed dramatically since Preview 1 and a new preview release is coming very soon. Would you be able to try the latest development build and see if your issue is resolved there? Just add the NuGet.config described here: https://github.com/aspnet/Home#daily-builds . Then upgrade your ASP.NET packages to the latest build there.

I'm hoping your issue is already fixed! :)

**Comment by davidfowl** [comment]
If you can reproduce this on demand you might be possible to use remote debugging with our symbols to figure out where it’s coming from

**Comment by conniey** [comment]
@davidfowl Where do I get the symbols for your preview build? I can reliably reproduce this error.
@anurse Thanks, i started looking into updating my chatroom solution to use preview2, but there are many conflicting dependencies. I got it to build but now I have runtime exceptions about missing methods (presumably from the conflicting dependencies) that I need to fix.

**Comment by davidfowl** [comment]
> @davidfowl Where do I get the symbols for your preview build? I can reliably reproduce this error.

They are on the Microsoft Symbol Servers.

**Comment by anurse** [comment]
> but there are many conflicting dependencies

What version of ASP.NET Core are you using? Preview 1 **requires** ASP.NET Core **2.1-preview1** because SignalR is part of ASP.NET Core.
