### ISSUE TITLE
flaky test: Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.SendToOthersInGroup

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1927]
Seen this fail a couple of times now. Never in isolation, always as part of a random ci run.

```
Failed   Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.SendToOthersInGroup(hubType: typeof(Microsoft.AspNetCore.SignalR.Tests.HubT))
Error Message:
 System.TimeoutException : Operation in SendToOthersInGroup timed out at C:\projects\signalr\test\Microsoft.AspNetCore.SignalR.Tests\HubConnectionHandlerTests.cs:1199
Stack Trace:
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__6`1.MoveNext() in C:\projects\signalr\test\Microsoft.AspNetCore.SignalR.Tests.Utils\TaskExtensions.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.<SendToOthersInGroup>d__42.MoveNext() in C:\projects\signalr\test\Microsoft.AspNetCore.SignalR.Tests\HubConnectionHandlerTests.cs:line 1199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:13.3133086]     Microsoft.AspNetCore.SignalR.Tests.WebSocketsTransportTests.WebSocketsTransportSendsUserAgent [SKIP]
Skipped  Microsoft.AspNetCore.SignalR.Tests.WebSocketsTransportTests.WebSocketsTransportSendsUserAgent
Total tests: 1211. Passed: 1199. Failed: 1. Skipped: 11.
```

**Comment by davidfowl** [comment]
Happened here again:
https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.3965

**Comment by davidfowl** [comment]
https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.3954

**Comment by davidfowl** [comment]
https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.4059

**Comment by davidfowl** [comment]
This might be a test client bug.
