### ISSUE TITLE
flaky test: ServerThrowsHubExceptionIfHubMethodCannotBeResolved

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1937]
Failed on our internal CI:

```
System.TimeoutException : Operation in ServerThrowsHubExceptionIfHubMethodCannotBeResolved timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:466
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<ServerThrowsHubExceptionIfHubMethodCannotBeResolved>d__15.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 474
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<ServerThrowsHubExceptionIfHubMethodCannotBeResolved>d__15.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 478
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [2018-04-09T18:09:22] TestLifetime Information: Starting test ServerThrowsHubExceptionIfHubMethodCannotBeResolved_json_WebSockets_dynamic
| [2018-04-09T18:09:22] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:53033/dynamic'.
| [2018-04-09T18:09:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
| [2018-04-09T18:09:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json v1'.
| [2018-04-09T18:09:28] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
| [2018-04-09T18:09:27] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: System.TimeoutException from test
|    at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<ServerThrowsHubExceptionIfHubMethodCannotBeResolved>d__15.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 468
| [2018-04-09T18:09:28] TestLifetime Information: Finished test ServerThrowsHubExceptionIfHubMethodCannotBeResolved_json_WebSockets_dynamic in 6.400074s
```

**Comment by anurse** [comment]
Seems to be resolved
