### ISSUE TITLE
Flaky test: RedisEndToEndTests.HubConnectionCanSendAndReceiveGroupMessages

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#1944]
https://travis-ci.org/aspnet/SignalR/jobs/364910777#L1422

```
[xUnit.net 00:00:23.0712597]     Microsoft.AspNetCore.SignalR.Redis.Tests.RedisEndToEndTests.HubConnectionCanSendAndReceiveGroupMessages(transportType: WebSockets, protocolName: "messagepack") [FAIL]
Failed   Microsoft.AspNetCore.SignalR.Redis.Tests.RedisEndToEndTests.HubConnectionCanSendAndReceiveGroupMessages(transportType: WebSockets, protocolName: "messagepack")
Error Message:
 System.TimeoutException : Operation in HubConnectionCanSendAndReceiveGroupMessages timed out at /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs:86
Stack Trace:
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Redis.Tests.RedisEndToEndTests.<HubConnectionCanSendAndReceiveGroupMessages>d__3.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Redis.Tests/RedisEndToEnd.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Standard Output Messages:
 | [2018-04-11T02:20:09] TestLifetime Information: Starting test HubConnectionCanSendAndReceiveGroupMessages_WebSockets_messagepack
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Binary. Url: 'ws://127.0.0.1:35654/echo'.
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'messagepack v1'.
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Binary. Url: 'ws://127.0.0.1:42777/echo'.
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'messagepack v1'.
 | [2018-04-11T02:20:09] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
 | [2018-04-11T02:20:14] TestLifetime Information: Finished test HubConnectionCanSendAndReceiveGroupMessages_WebSockets_messagepack in 5.0492456s
```

**Comment by davidfowl** [comment]
This is a regression caused by https://github.com/aspnet/SignalR/commit/e2169ceda636797ebe76ba1a26abd0ae59a0802e (is my guess). @mikaelm12 can you take a look ASAP

**Comment by davidfowl** [comment]
Fixed
