### ISSUE TITLE
Flaky PendingInvocationsAreTerminatedIfServerTimeoutIntervalElapsesWithNoMessages

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2018]
https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.4155

```
Microsoft.AspNetCore.SignalR.Client.Tests.HubConnectionTests.PendingInvocationsAreTerminatedIfServerTimeoutIntervalElapsesWithNoMessages
Error Message:
 Assert.Throws() Failure
Expected: typeof(System.TimeoutException)
Actual:   typeof(System.InvalidOperationException): The 'InvokeAsync' method cannot be called if the connection is not active
Stack Trace:
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.CheckConnectionActive(String methodName) in C:\projects\signalr\src\Microsoft.AspNetCore.SignalR.Client.Core\HubConnection.cs:line 748
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsyncCore>d__34.MoveNext() in C:\projects\signalr\src\Microsoft.AspNetCore.SignalR.Client.Core\HubConnection.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsync>d__28.MoveNext() in C:\projects\signalr\src\Microsoft.AspNetCore.SignalR.Client.Core\HubConnection.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__2.MoveNext() in C:\projects\signalr\test\Microsoft.AspNetCore.SignalR.Tests.Utils\TaskExtensions.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.8477561]     
```

**Comment by JamesNK** [comment]
Probably the cause - https://github.com/aspnet/SignalR/issues/1997
