### ISSUE TITLE
flaky test: Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.CanStartAndStopConnectionUsingGivenTransport

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2031]
```
dotnet.exe : [xUnit.net 00:00:08.1859729]     Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.CanStartAndStopConnectionUsingGivenTransport(transportType: LongPolling) [FAIL]
At C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview3-17002\scripts\common.psm1:7 char:5
+     & $_cmd @args
+     ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([xUnit.net 00:0...Polling) [FAIL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Failed   Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.CanStartAndStopConnectionUsingGivenTransport(transportType: LongPolling)
Error Message:
 System.Exception : 1 error(s) logged.
Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport - ErrorSendingDeleteRequest - Error sending DELETE request to 'http://127.0.0.1:3224/echo?id=IES88WFl2FJN1VfJPzCxJQ'.
===================
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.<SendDeleteRequest>d__20.MoveNext() in C:\projects\signalr\src\Microsoft.AspNetCore.Http.Connections.Client\Internal\LongPollingTransport.cs:line 211
===================
Stack Trace:
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in C:\projects\signalr\test\Microsoft.AspNetCore.SignalR.Tests.Utils\VerifyNoErrorsScope.cs:line 63
   at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<CanStartAndStopConnectionUsingGivenTransport>d__4.MoveNext() in C:\projects\signalr\test\Microsoft.AspNetCore.SignalR.Tests\EndToEndTests.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Standard Output Messages:
 | [2018-04-14T16:19:02] TestLifetime Information: Starting test CanStartAndStopConnectionUsingGivenTransport
 | [2018-04-14T16:19:02] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Starting transport. Transfer mode: Text.
 | [2018-04-14T16:19:02] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
 | [2018-04-14T16:19:02] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Transport is stopping.
 | [2018-04-14T16:19:02] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Warning: Unsuccessful HTTP response status code of BadRequest return from DELETE 'http://127.0.0.1:3224/echo?id=IES88WFl2FJN1VfJPzCxJQ'.
 | [2018-04-14T16:19:03] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Error: Error sending DELETE request to 'http://127.0.0.1:3224/echo?id=IES88WFl2FJN1VfJPzCxJQ'.
 |    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 |    at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.<SendDeleteRequest>d__20.MoveNext() in C:\projects\signalr\src\Microsoft.AspNetCore.Http.Connections.Client\Internal\LongPollingTransport.cs:line 211
 | [2018-04-14T16:19:03] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Disposed.
 | [2018-04-14T16:19:03] TestLifetime Information: Finished test CanStartAndStopConnectionUsingGivenTransport in 0.3250259s
```

**Comment by davidfowl** [comment]
This is the only case we return a 400:

https://github.com/aspnet/SignalR/blob/ddc905c219d19f28445bfaf68a15d84b10b6646c/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs#L504-L511

So it seems like the server forgot this is a long polling connection?

**Comment by davidfowl** [comment]
Fixed
