### ISSUE TITLE
flaky test: Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2069]
```
[xUnit.net 00:00:14.4555490]     Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport(message: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"...) [FAIL]

  Failed   Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport(message: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"...)

[39;49m[31mRUNDOTNET : error Message:  [/Users/travis/.dotnet/buildtools/korebuild/2.1.0-preview3-17018/KoreBuild.proj]

[39;49m   System.Exception : 1 error(s) logged.

  Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager - FailedDispose - Failed disposing connection yTeG2nC1VbY0hQOwC6ydHA.

  ===================

  System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('CloseReceived') for this operation. Valid states are: 'Open, CloseSent'

     at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)

     at System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)

  --- End of stack trace from previous location where exception was thrown ---

     at System.Net.WebSockets.WebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken)

     at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.StartReceiving(WebSocket socket) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/Transports/WebSocketsTransport.cs:line 147

     at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()

     at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)

     at System.IO.Pipelines.Pipe.GetReadAsyncResult()

     at Microsoft.AspNetCore.SignalR.Tests.EchoConnectionHandler.OnConnectedAsync(ConnectionContext connection) in /_/test/Microsoft.AspNetCore.SignalR.Tests/EchoConnectionHandler.cs:line 16

     at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteApplication(ConnectionDelegate connectionDelegate, HttpConnectionContext connection) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs:line 385

     at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionContext.cs:line 255

     at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionContext.cs:line 207

     at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.cs:line 205

  ===================

  Stack Trace:

     at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifyNoErrorsScope.cs:line 63

     at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport(String message) in /_/test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs:line 319

  --- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidfowl** [comment]
I am disappointed in this error, I swore that this time, we would get our websocket loop right and shutdown is *always * a problem. We may want to look at this:

https://github.com/aspnet/SignalR/blob/679225c241b32c8e2af8c84fa693d3f8232d1085/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.cs#L190

I'm not even sure it would help...

**Comment by davidfowl** [comment]
@stephentoub the internal websocket state doesn't change unless the state is observed by the caller right? What I mean is, you wouldn't change the state to `CloseReceived` unless a close frame was returned from ReadAsync right?

Looking at the code, I can't tell why it would do a read after receiving a close frame, we exit the entire method after a close frame is received.

**Comment by stephentoub** [comment]
> What I mean is, you wouldn't change the state to CloseReceived unless a close frame was returned from ReadAsync right?

The only place the state is set to CloseReceived is in HandleReceivedCloseAsync.
https://github.com/dotnet/corefx/blob/ab8e81453fa869556821c464bd5824b588d679cd/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L771

And the only place HandleReceivedCloseAsync is called is in ReceiveAsync (well, in ReceiveAsyncPrivate, but that's only called from ReceiveAsync as the bulk of its implementation):
https://github.com/dotnet/corefx/blob/ab8e81453fa869556821c464bd5824b588d679cd/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L664-L668
at which point it immediately returns the read close frame.

The error that's being thrown is coming at the beginning of ReceiveAsync, before any of this logic is hit:
https://github.com/dotnet/corefx/blob/ab8e81453fa869556821c464bd5824b588d679cd/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L286
which would mean it would have been a previous call to ReceiveAsync that caused the transition.

**Comment by davidfowl** [comment]
@BrennanConroy can you look at this? Maybe the change to zero byte reads introduced this? Looking at the code nothing stuck out to me. I'll keep looking as well.

**Comment by anurse** [comment]
We think we know where this might be. We're doing a zero-byte read, checking for close and then doing a non-zero read. However, we don't check that second read to see if it has a close result. If it does return a close status, the next zero-byte read could fail with this.

The customer impact of this is minimal because we've already shut down, so we're going to look at it in 2.2.0.

**Comment by davidfowl** [comment]
Again https://api.travis-ci.org/v3/job/368421348/log.txt

**Comment by JamesNK** [comment]
The error should now be suppressed on dev and release/2.1. That build was from before I merged.
