### ISSUE TITLE
Calling start with no arguments throw arg null exception

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#213]
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: transport
   at Microsoft.AspNetCore.Sockets.Client.Connection.<StartAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.Program.<ExecuteAsync>d__1.MoveNext() in c:\Users\dfowler\Documents\Visual Studio 2017\Projects\WebApplication22\ConsoleApp1\Program.cs:line 22
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp1.Program.Main(String[] args) in c:\Users\dfowler\Documents\Visual Studio 2017\Projects\WebApplication22\ConsoleApp1\Program.cs:line 17
```

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client/Connection.cs#L52

I actually fixed it locally yesterday.
