### ISSUE TITLE
Flaky test: CanCloseStreamMethodEarly

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2177]
This test [fails](http://aspnetci/viewLog.html?buildId=458545&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.Exception : 1 error(s) logged.
SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets - 0 - Unexpected exception in SocketConnection.StartAsync.
===================
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<DoSend>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<StartAsync>d__16.MoveNext()
===================
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CanCloseStreamMethodEarly>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [2018-05-01T02:21:04] TestLifetime Information: Starting test CanCloseStreamMethodEarly_messagepack_LongPolling_hubT
| [2018-05-01T02:21:04] ServerLogScope Information: Server log scope started.
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50142/hubT/negotiate  0
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6536ms 200 application/json
| [2018-05-01T02:21:04] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Starting transport. Transfer mode: Binary.
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5243ms 200 application/octet-stream
| [2018-05-01T02:21:04] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
| [2018-05-01T02:21:04] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'messagepack v1'.
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  39
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Information: 83Cbneh0AQWVOmvZ79C-KA - Completed connection handshake. Using HubProtocol 'messagepack'.
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6551ms 200 text/plain
| [2018-05-01T02:21:04] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.7801ms 200 application/octet-stream
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  17
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.0798ms 200 text/plain
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.2656ms 200 application/octet-stream
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  6
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  
| [2018-05-01T02:21:04] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Transport is stopping.
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.8878ms 200 text/plain
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.911ms 200 application/octet-stream
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Error: Unexpected exception in SocketConnection.StartAsync.
| System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
|    at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<DoSend>d__19.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<StartAsync>d__16.MoveNext()
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 DELETE http://127.0.0.1:50142/hubT?id=83Cbneh0AQWVOmvZ79C-KA  0
| [2018-05-01T02:21:04] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.4437ms 202 text/plain
| [2018-05-01T02:21:04] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Disposed.
| [2018-05-01T02:21:04] ServerLogScope Information: Server log scope stopped.
| [2018-05-01T02:21:04] TestLifetime Information: Finished test CanCloseStreamMethodEarly_messagepack_LongPolling_hubT in 0.0100921s
```

**Comment by anurse** [comment]
This error might actually just be expected and we need to update our test.

**Comment by anurse** [comment]
Actually we think this might be a combination of https://github.com/aspnet/KestrelHttpServer/issues/2536 and the fact that we should expect this error and not fail the test.

**Comment by JamesNK** [comment]
Is this error still occurring? I'm not able to reproduce it.

**Comment by ryanbrandenburg** [comment]
Looking at the history, it failed 100% of the time for a while but not at all in the last couple days. I'll close this out and re-open if we see it again.
