### ISSUE TITLE
flaky test: Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanCloseStreamMethodEarly(protocolName: "json", transportType: ServerSentEvents, path: "/dynamic")

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#2209]
@BrennanConroy looks like the netcoreapp2.0 bug, we should be able to stop testing netcoreapp2.0.

```
Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanCloseStreamMethodEarly(protocolName: "json", transportType: ServerSentEvents, path: "/dynamic") [FAIL]
  Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanCloseStreamMethodEarly(protocolName: "json", transportType: ServerSentEvents, path: "/dynamic")
RUNDOTNET : error Message:  [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.2.0-preview1-17042\KoreBuild.proj]
   System.Exception : 1 error(s) logged.
  Microsoft.AspNetCore.Http.Connections.Client.HttpConnection - TransportThrewExceptionOnStop - The transport threw an exception while stopping.
  ===================
  System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at System.Net.Http.WinHttpResponseStream.CancelPendingResponseStreamReadOperation()
     at System.Net.Http.WinHttpResponseStream.<>c.<CopyToAsyncCore>b__18_0(Object s)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
     --- End of inner exception stack trace ---
     at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
     at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport.<ProcessAsync>d__18.MoveNext() in /_/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ServerSentEventsTransport.cs:line 115
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport.<StopAsync>d__20.MoveNext() in /_/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ServerSentEventsTransport.cs:line 228
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<DisposeAsyncCore>d__43.MoveNext() in /_/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs:line 256
  ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
     at System.Net.Http.WinHttpResponseStream.CancelPendingResponseStreamReadOperation()
     at System.Net.Http.WinHttpResponseStream.<>c.<CopyToAsyncCore>b__18_0(Object s)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)<---
  
  ===================
```

**Comment by BrennanConroy** [comment]
Removed netcoreapp2.0 testing here https://github.com/aspnet/SignalR/pull/2221
