### ISSUE TITLE
HubConnectionBuilder.Build throws System.TypeLoadException: Could not resolve the signature of a virtual method

### ISSUE THREAD

**Issue by Immons** [aspnet/SignalR#2277]
### Please include as much of the following as you can in your bug report

* Versions of Client-Side NuGet/NPM Packages: 1.0.0-preview2-final
* Are you using the C# client or the JavaScript client: C#
* The Operating System on the Client (Windows/Linux/macOS): iOS

Using this version because latest one crashes on iOS with certificates. I am unable to build hubConnection because there is crash at:

`
new HubConnectionBuilder()
				.WithUrl(new Uri($"{ApiConfiguration.ApiUrl}/chat/message?signalRTokenHeader={Networking.Helpers.Settings.Authorization?.AccessToken}"))
                .Build();
`

and it throws System.TypeLoadException: Could not resolve the signature of a virtual method

Any idea?

**Comment by Immons** [comment]
@anurse 

`
2018-05-16 10:47:24.339 SomeProject.iOS[52868:1811430] Unhandled managed exception:
Could not resolve the signature of a virtual method (System.TypeLoadException)
  at SomeProject.iOS.Services.iOSChatService.CreateNewConnection () [0x00031] in /Users/immons/Projekty/SomeProject/SomeProject/SomeProject.iOS/Services/iOSChatService.cs:31 
  at SomeProject.iOS.Services.iOSChatService+<ConnectAsync>d__7.MoveNext () [0x00048] in /Users/immons/Projekty/SomeProject/SomeProject/SomeProject.iOS/Services/iOSChatService.cs:63 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at SomeProject.Core.ViewModels.Main.MainViewModel+<SubscribeToChat>d__12.MoveNext () [0x00026] in /Users/immons/Projekty/SomeProject/SomeProject/SomeProject.Core/ViewModels/Main/MainViewModel.cs:97 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at SomeProject.Core.ViewModels.Main.MainViewModel+<ViewAppeared>d__78.MoveNext () [0x00050] in /Users/immons/Projekty/SomeProject/SomeProject/SomeProject.Core/ViewModels/Main/MainViewModel.cs:425 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
  at UIKit.UIKitSynchronizationContext+<>c__DisplayClass1_0.<Post>b__0 () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/UIKit/UIKitSynchronizationContext.cs:24 
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/Foundation/NSAction.cs:125 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at SomeProject.iOS.Application.Main (System.String[] args) [0x00001] in /Users/immons/Projekty/SomeProject/SomeProject/SomeProject.iOS/Application.cs:12 
`

**Comment by anurse** [comment]
Can you provide an example of the code that throws the exception? We need to figure out what SignalR code is actually triggering the issue.

**Comment by Immons** [comment]
@anurse I have already provided that in opening issue post.

`
new HubConnectionBuilder() .WithUrl(new Uri($"{ApiConfiguration.ApiUrl}/chat/message?signalRTokenHeader={Networking.Helpers.Settings.Authorization?.AccessToken}")) .Build();
`

**Comment by anurse** [comment]
Ok, that wasn't on the call stack and you didn't mention where this code was so I wasn't clear on if this code was in `SomeProject.iOS.Services.iOSChatService.CreateNewConnection ()`.

**Comment by eopeter** [comment]
I am having the same issue getting the SignalR client for DotNetCore to work in Xamarin iOS. When I run my application I get "Could not resolve the signature of a virtual method" when building the connection:

`
Connection = new HubConnectionBuilder()
                            .WithUrl(url + "/Chat")
                            .Build();
`

**Comment by eopeter** [comment]
I am using the just released client version 1.0.0. Any help with be appreciated.

**Comment by greghoover** [comment]
Same here. On Android Oreo 8.1 x86 emulator. Using the latest VS 2017 15.8.0 preview 1.1 with .NET Core SDK 2.1.300, NETCore.App 2.1.0, SignalR Core 1.0.0, and Xamarin forms 3.1.0.469394-pre1 from a .NET Standard 2.0 dll.
Although version 4.5.0 of System.Memory is available via NuGet, still have to explicitly pin to version 4.5.0-preview1-26216-02 in the Android project file to get it to build. Exception is thrown when building the HubConnection:
_hub = new HubConnectionBuilder()
	.WithUrl($"http://{RelayUtil.RelayHostName}:5000/route", HttpTransportType.LongPolling)
        .Build();
Same code works fine on UWP.

System.TypeLoadException: Could not resolve the signature of a virtual method
Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x0001b] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x00035] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00072] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0001b] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00072] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x00000] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0003e] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope) [0x00032] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType) [0x00008] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00000] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T] (System.IServiceProvider provider) [0x0000e] in <0483c335f48f46709723603c1a3a0703>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder.Build () [0x00041] in <b0d1d37b5fba4e70bb8beedfba950c0d>:0

**Comment by greghoover** [comment]
It compiles with the preview version of System.Memory only. It does not compile with other versions. The form and controls operate as expected w the preview version. Where it fails is on build of the the hub connection.

**Comment by davidfowl** [comment]
> It compiles with the preview version of System.Memory only

What version is that? Did you downgrade to an older version that doesn't have the right methods? If so then the error makes total sense.

**Comment by greghoover** [comment]
@davidfowl Had to downgrade to System.Memory 4.5.0-preview1-26216-02 to compile. Tried 4.5.0-preview2-26406-04, 4.5.0-rc1, and 4.5.0, but doesn't compile using any of these.

Version info pasted here for convenience:
Android Oreo 8.1 x86 emulator. Using the latest VS 2017 15.8.0 preview 1.1. .NET Core SDK 2.1.300, NETCore.App 2.1.0, SignalR Core 1.0.0, and Xamarin forms 3.1.0.469394-pre1 from a .NET Standard 2.0 dll.

This is the compile error using System.Memory 4.5.0:
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Memory.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	hase.ClientUI.XFApp.Android

**Comment by davidfowl** [comment]
I'm going to close this issue and track this in the uber Xamarin issue here https://github.com/aspnet/SignalR/issues/1886. The bottom line is that Xamarin isn't supported in this version of SignalR. Luckily, the fix is coming in the first patch which should be weeks away. It's an issue in the System.Memory packaging that was caught too late.

**Comment by greghoover** [comment]
Perfect. Thanks.
