### ISSUE TITLE
Flaky test: CanInvokeClientMethodFromServer

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2302]
This test [fails](http://aspnetci/viewLog.html?buildId=470227&buildTypeId=Lite_SignalR) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (Value cannot be null.
Parameter name: path3) (The following constructor parameters did not have matching fixture data: ServerFixture`1 serverFixture)
---- System.ArgumentNullException : Value cannot be null.
Parameter name: path3
---- The following constructor parameters did not have matching fixture data: ServerFixture`1 serverFixture
----- Inner Stack Trace #1 (System.ArgumentNullException) -----
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Microsoft.Extensions.Logging.Testing.AssemblyTestLog.Create(Assembly assembly, String baseDirectory)
   at Microsoft.Extensions.Logging.Testing.AssemblyTestLog.ForAssembly(Assembly assembly)
   at Microsoft.AspNetCore.SignalR.Tests.ServerFixture`1..ctor(ILoggerFactory loggerFactory) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs:line 65
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

This happens on just regular builds of SignalR, so I assume it reproduces locally.

**Comment by anurse** [comment]
The call stack is within Logging.Testing. Anything look odd here @JunTaoLuo ?

**Comment by JunTaoLuo** [comment]
This is not flakiness, but it was fixed in https://github.com/aspnet/SignalR/commit/26e456fd25a56ef426d434583e874aec9c453115.
