### ISSUE TITLE
Flakey test: StreamDoesNotStartIfTokenAlreadyCanceled

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2310]
https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.4713

```
Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.StreamDoesNotStartIfTokenAlreadyCanceled(protocolName: "json", transportType: ServerSentEvents, path: "/hubT")
RUNDOTNET : error Message:  [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.2.0-preview1-17051\KoreBuild.proj]
   System.Exception : 1 error(s) logged.
  SERVER Microsoft.AspNetCore.Server.Kestrel - ApplicationError - Connection id "0HLDSAJQ34UGH", Request id "0HLDSAJQ34UGH:00000002": An unhandled exception was thrown by the application.
  ===================
  Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.<PumpAsync>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
     at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
     at System.IO.Pipelines.Pipe.GetReadAsyncResult()
     at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<CopyToAsync>d__22.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<CopyToAsyncInternal>d__23.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.<ProcessSend>d__16.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.<ExecuteAsync>d__7.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
     at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__186`1.MoveNext()
  ===================
  Stack Trace:
     at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose()
     at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose()
     at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<StreamDoesNotStartIfTokenAlreadyCanceled>d__13.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Standard Output Messages:
   | [2018-05-17T17:19:50] TestLifetime Information: Starting test StreamDoesNotStartIfTokenAlreadyCanceled-json-ServerSentEvents-/hubT
   | [2018-05-17T17:19:50] TestLifetime Information: Starting test StreamDoesNotStartIfTokenAlreadyCanceled_json_ServerSentEvents_hubT
   | [2018-05-17T17:19:50] ServerLogScope Information: Server log scope started.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:239).
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:2778/hubT'.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:2778/hubT/negotiate'.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLDSAJQ34UGG" started.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:2778/hubT/negotiate  0
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Debug: AuthenticationScheme: Bearer was not authenticated.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/hubT/negotiate'.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: New connection 1mmwnIrViLbKKG0N7BbDhQ created.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: 1mmwnIrViLbKKG0N7BbDhQ - Sending negotiation response.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLDSAJQ34UGG" completed keep alive response.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.8054ms 200 application/json
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Established connection '1mmwnIrViLbKKG0N7BbDhQ' with the server.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Skipping transport WebSockets because it was disabled by the client.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'ServerSentEvents' with Url: http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Information: Starting transport. Transfer mode: Text.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request GET 'http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ'.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ  
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Debug: AuthenticationScheme: Bearer was not authenticated.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/hubT'.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: 1mmwnIrViLbKKG0N7BbDhQ - Establishing new connection.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.SignalR.HubConnectionHandler Debug: 1mmwnIrViLbKKG0N7BbDhQ - OnConnectedAsync started.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Starting receive loop.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Received 3 bytes. Parsing SSE frame.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Starting the send loop.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Transport 'ServerSentEvents' started.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json v1'.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Sending 32 bytes to the server using url: http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ.
   | [2018-05-17T17:19:50] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ'.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLDSAJQ34UGH" started.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ  32
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Debug: AuthenticationScheme: Bearer was not authenticated.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/hubT'.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: 1mmwnIrViLbKKG0N7BbDhQ - Connection id "0HLDSAJQ34UGH", Request id "0HLDSAJQ34UGH:00000001": started reading request body.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: 1mmwnIrViLbKKG0N7BbDhQ - Connection id "0HLDSAJQ34UGH", Request id "0HLDSAJQ34UGH:00000001": done reading request body.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Trace: 1mmwnIrViLbKKG0N7BbDhQ - Received 32 bytes.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLDSAJQ34UGH" completed keep alive response.
   | [2018-05-17T17:19:50] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.878ms 200 text/plain
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver Debug: 1mmwnIrViLbKKG0N7BbDhQ - Found protocol implementation for requested protocol: json.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Information: 1mmwnIrViLbKKG0N7BbDhQ - Completed connection handshake. Using HubProtocol 'json'.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Message(s) sent successfully.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Trace: Scanning connections.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Trace: Scanned connections in 00:00:00.0000608.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Http.Connections.Internal.Transports.ServerSentEventsTransport Trace: 1mmwnIrViLbKKG0N7BbDhQ - Writing a 3 byte message.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Received 6 bytes. Parsing SSE frame.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Received 13 bytes. Parsing SSE frame.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Passing message to application. Payload size: 3.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Handshake with server complete.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Receive loop starting.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting server timeout timer. Duration: 30000.00ms
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:281).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StreamAsChannelCoreAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:364).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.Internal.InvocationRequest.Streaming Trace: Invocation 1 created.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Preparing streaming invocation '1' of 'Stream', with return type 'System.Int32' and 1 argument(s).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering Invocation ID '1' for tracking.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Issuing Invocation '1': System.Int32 Stream(System.Int32).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending StreamInvocationMessage message '1'.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending StreamInvocationMessage message '1' completed.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StreamAsChannelCoreAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:339).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StreamAsChannelCoreAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:382).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:297).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Cancellation for Invocation '1'.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending CancelInvocationMessage message '1'.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending CancelInvocationMessage message '1' completed.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StreamAsChannelCoreAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:356).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.Internal.InvocationRequest.Streaming Trace: Invocation 1 disposed.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:324).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Stopping HubConnection.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Terminating receive loop.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Waiting for the receive loop to terminate.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Sending 94 bytes to the server using url: http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ'.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:776).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:785).
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Disposing HttpConnection.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Information: Transport is stopping.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:2778/hubT?id=1mmwnIrViLbKKG0N7BbDhQ  94
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Debug: AuthenticationScheme: Bearer was not authenticated.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/hubT'.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: 1mmwnIrViLbKKG0N7BbDhQ - Connection id "0HLDSAJQ34UGH", Request id "0HLDSAJQ34UGH:00000002": started reading request body.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLDSAJQ34UGH" received FIN.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLDSAJQ34UGH" disconnecting.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLDSAJQ34UGH" sending FIN.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: 1mmwnIrViLbKKG0N7BbDhQ - Connection id "0HLDSAJQ34UGH", Request id "0HLDSAJQ34UGH:00000002": done reading request body.
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLDSAJQ34UGH" bad request data: "Unexpected end of request content."
   | Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.<PumpAsync>d__4.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   |    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<CopyToAsync>d__22.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<CopyToAsyncInternal>d__23.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.<ProcessSend>d__16.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.<ExecuteAsync>d__7.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__186`1.MoveNext()
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLDSAJQ34UGH", Request id "0HLDSAJQ34UGH:00000002": An unhandled exception was thrown by the application.
   | Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.<PumpAsync>d__4.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   |    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<CopyToAsync>d__22.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<CopyToAsyncInternal>d__23.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.<ProcessSend>d__16.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.<ExecuteAsync>d__7.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   | --- End of stack trace from previous location where exception was thrown ---
   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__186`1.MoveNext()
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 2.3377ms 400 
   | [2018-05-17T17:19:51] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLDSAJQ34UGH" stopped.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Send loop canceled.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Send loop stopped.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Receive loop canceled.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Receive loop stopped.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Debug: Transport stopped.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Disposed.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Canceling all outstanding invocations.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Removing pending invocation 1.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.Internal.InvocationRequest.Streaming Trace: Invocation 1 disposed.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Shutting down connection.
   | [2018-05-17T17:19:51] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: HubConnection stopped.
   | [2018-05-17T17:19:51] ServerLogScope Information: Server log scope stopped.
   | [2018-05-17T17:19:51] TestLifetime Information: Finished test StreamDoesNotStartIfTokenAlreadyCanceled_json_ServerSentEvents_hubT in 0.7541414s
   | [2018-05-17T17:19:51] TestLifetime Information: Finished test StreamDoesNotStartIfTokenAlreadyCanceled-json-ServerSentEvents-/hubT in 0.8606917s
```

**Comment by JamesNK** [comment]
The error is being logged in Kestrel. I suspect it comes from cancelling an HTTP request to Kestrel from `HttpClient.SendAsync`.

Should Kestrel be erroring for this situation? @davidfowl @halter73 @pakrym

**Comment by davidfowl** [comment]
This should be fixed already https://github.com/aspnet/KestrelHttpServer/commit/5c17bff55d018946572245c435a0361bde06ffd1

**Comment by davidfowl** [comment]
My bad this doesn't look  like an upgraded connection. It looks like this is just the expected exception when data is cut off while reading request content.

**Comment by JamesNK** [comment]
I don't know what an upgraded connection is. So in Kestrel getting errors logged is expected when the caller cancels the request?

If yes, is the solution in the SignalR project to ignore this exception?

**Comment by davidfowl** [comment]
> I don't know what an upgraded connection is. 

For this conversation it's a websocket connection.

> So in Kestrel getting errors logged is expected when the caller cancels the request?

Yes. I think we need to handle this here https://github.com/aspnet/SignalR/blob/b493f01b35a9810b7b0893cdf5719121ab5389c9/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs#L486

We should handle `IOException` as well.

**Comment by JamesNK** [comment]
Ah, the error is logged from Kestrel because the exception was unhandled and thrown to Kestrel.

I thought it was logged inside Kestrel on the FIN.

**Comment by anurse** [comment]
Reopening to track as a candidate for 2.1.1 patch.

**Comment by anurse** [comment]
Re-closing, we're going to open new issues for patch work.
