### ISSUE TITLE
Flakey test - HubConnection › keepAlive › does not terminate if messages are received

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2327]
https://travis-ci.org/aspnet/SignalR/jobs/380448372

```
  FAIL signalr/tests/HubConnection.test.ts (22.658s)
    ● HubConnection › keepAlive › does not terminate if messages are received
  
      expect(received).toBeUndefined()
      
      Expected value to be undefined, instead received
        [Error: Server timeout elapsed without receiving a message from the server.]
  
        921 |                 const error = await p.promise;
        922 | 
      > 923 |                 expect(error).toBeUndefined();
        924 |             } finally {
        925 |                 hubConnection.stop();
        926 |             }
        
        at Object.<anonymous> (signalr/tests/HubConnection.test.ts:923:31)
        at step (node_modules/tslib/tslib.js:133:27)
        at Object.next (node_modules/tslib/tslib.js:114:57)
        at fulfilled (node_modules/tslib/tslib.js:104:62)
```

**Comment by JamesNK** [comment]
Everything is in the test - no server involved.

My theory is on slow build environments the 100ms timeout is hit while the test is in the process of simulating a ping. I doubling the time to 200ms should be enough extra leeway.

**Comment by anurse** [comment]
We might want to consider this in #2309
