### ISSUE TITLE
DELETE request sometimes sent on DisposeAsync after failing to connect with long polling

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2362]
https://travis-ci.org/aspnet/SignalR/jobs/382889588

```
  Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubProtocolVersionTests.ClientWithUnsupportedProtocolVersionDoesNotConnect(transportType: LongPolling)
RUNDOTNET : error Message:  [/Users/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17060/KoreBuild.proj]
   System.Exception : 1 error(s) logged.
  Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport - ErrorSendingDeleteRequest - Error sending DELETE request to 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
  ===================
  System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
     at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.SendDeleteRequest(Uri url) in /_/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LongPollingTransport.cs:line 225
  ===================
  Stack Trace:
     at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifyNoErrorsScope.cs:line 63
     at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 66
     at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubProtocolVersionTests.ClientWithUnsupportedProtocolVersionDoesNotConnect(HttpTransportType transportType) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubProtocolVersionTests.cs:line 195
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   | [2018-05-23T21:29:27] TestLifetime Information: Starting test ClientWithUnsupportedProtocolVersionDoesNotConnect-LongPolling
   | [2018-05-23T21:29:27] TestLifetime Information: Starting test ClientWithUnsupportedProtocolVersionDoesNotConnect_LongPolling
   | [2018-05-23T21:29:27] ServerLogScope Information: Server log scope started.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:261).
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:53434/version'.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:53434/version/negotiate'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PN" started.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:53434/version/negotiate  0
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/version/negotiate'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: New connection 0pqupuUdz9-Ksz_4tfLVmA created.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: 0pqupuUdz9-Ksz_4tfLVmA - Sending negotiation response.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PN" completed keep alive response.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 2.396ms 200 application/json
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Established connection '0pqupuUdz9-Ksz_4tfLVmA' with the server.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Skipping transport WebSockets because it was disabled by the client.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Skipping transport ServerSentEvents because it was disabled by the client.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'LongPolling' with Url: http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Starting transport. Transfer mode: Text.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request GET 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA  
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/version'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: 0pqupuUdz9-Ksz_4tfLVmA - Establishing new connection.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PN" completed keep alive response.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.SignalR.HubConnectionHandler Debug: 0pqupuUdz9-Ksz_4tfLVmA - OnConnectedAsync started.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.997ms 200 application/octet-stream
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Starting receive loop.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request GET 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Starting the send loop.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA  
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Transport 'LongPolling' started.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/version'.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: 0pqupuUdz9-Ksz_4tfLVmA - Resuming existing connection.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json v2147483647'.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Sending 41 bytes to the server using url: http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PO" started.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA  41
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/version'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: 0pqupuUdz9-Ksz_4tfLVmA - Connection id "0HLE0UGEHD8PO", Request id "0HLE0UGEHD8PO:00000001": started reading request body.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: 0pqupuUdz9-Ksz_4tfLVmA - Connection id "0HLE0UGEHD8PO", Request id "0HLE0UGEHD8PO:00000001": done reading request body.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver Debug: 0pqupuUdz9-Ksz_4tfLVmA - Found protocol implementation for requested protocol: json.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Trace: 0pqupuUdz9-Ksz_4tfLVmA - Received 41 bytes.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PO" completed keep alive response.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.175ms 200 text/plain
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Warning: 0pqupuUdz9-Ksz_4tfLVmA - Server does not support version json of the 2147483647 protocol.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Message(s) sent successfully.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport Trace: 0pqupuUdz9-Ksz_4tfLVmA - Writing a 83 byte message to connection.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PN" completed keep alive response.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Trace: Poll response with status code 200 received from server. Content length: 83.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3.867ms 200 application/octet-stream
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Received messages from the server.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request GET 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Server returned handshake error: The server does not support version 2147483647 of the 'json' protocol.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA  
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/version'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: 0pqupuUdz9-Ksz_4tfLVmA - Resuming existing connection.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport Debug: 0pqupuUdz9-Ksz_4tfLVmA - Terminating Long Polling connection by sending 204 response.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext Trace: 0pqupuUdz9-Ksz_4tfLVmA - Disposing connection 0pqupuUdz9-Ksz_4tfLVmA.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext Trace: 0pqupuUdz9-Ksz_4tfLVmA - Shutting down both the application and the LongPolling transport.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext Trace: 0pqupuUdz9-Ksz_4tfLVmA - Waiting for both the application and LongPolling transport to complete.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Error starting connection.
| Microsoft.AspNetCore.SignalR.HubException : Unable to complete handshake with the server due to an error : The server does not support version 2147483647 of the 'json' protocol. [/Users/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17060/KoreBuild.proj]
   |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 691
   |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 285
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext Trace: 0pqupuUdz9-Ksz_4tfLVmA - The application and LongPolling transport are both complete.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Disposing HttpConnection.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: 0pqupuUdz9-Ksz_4tfLVmA - Removing connection 0pqupuUdz9-Ksz_4tfLVmA from the list of connections.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: Transport is stopping.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Send loop canceled.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PN" completed keep alive response.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Send loop stopped.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3.069ms 204 text/plain
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLE0UGEHD8PN" received FIN.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PN" disconnecting.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Receive loop stopped.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLE0UGEHD8PN" sending FIN.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Sending DELETE request to 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request DELETE 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PN" stopped.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 DELETE http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA  0
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/version'.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PO" completed keep alive response.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7ms 404 text/plain
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Warning: Unsuccessful HTTP response 404 return from DELETE 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Error: Error sending DELETE request to 'http://127.0.0.1:53434/version?id=0pqupuUdz9-Ksz_4tfLVmA'.
   | System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   |    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   |    at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.SendDeleteRequest(Uri url) in /_/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/LongPollingTransport.cs:line 225
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Debug: Transport stopped.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Disposed.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLE0UGEHD8PO" received FIN.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:304).
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PO" disconnecting.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLE0UGEHD8PO" sending FIN.
   | [2018-05-23T21:29:27] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE0UGEHD8PO" stopped.
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:320).
   | [2018-05-23T21:29:27] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:347).
   | [2018-05-23T21:29:27] ServerLogScope Information: Server log scope stopped.
   | [2018-05-23T21:29:27] TestLifetime Information: Finished test ClientWithUnsupportedProtocolVersionDoesNotConnect_LongPolling in 0.040794s
   | [2018-05-23T21:29:27] TestLifetime Information: Finished test ClientWithUnsupportedProtocolVersionDoesNotConnect-LongPolling in 0.181763s
```

**Comment by JamesNK** [comment]
So on handshake failure there is a race condition between the server telling the client that it is stopping - in which case no DELETE is sent - and the client telling the server it should clean up the connection - a DELETE is sent which fails because the connection is already stopped on the server.

The handshake happens in the `HubConnection` class and there is no way to tell the HttpConnection/ITransport where the DELETE request is made that they are closing because of the handshake failing.

I'm going to make 404 response from the long poll DELETE log as debug instead of error.

**Comment by JamesNK** [comment]
@anurse @davidfowl
