### ISSUE TITLE
Flakey ClientPingsMultipleTimes

### ISSUE THREAD

**Issue by JamesNK** [aspnet/SignalR#2367]
https://travis-ci.org/aspnet/SignalR/jobs/382984813

```
  Failed   Microsoft.AspNetCore.SignalR.Client.Tests.HubConnectionTests+Protocol.ClientPingsMultipleTimes
RUNDOTNET : error Message:  [/home/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17060/KoreBuild.proj]
   System.TimeoutException : Operation in ClientPingsMultipleTimes timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.Protocol.cs:586
  Stack Trace:
     at System.Threading.Tasks.TaskExtensions.OrTimeout[T](Task`1 task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber)
     at Microsoft.AspNetCore.SignalR.Client.Tests.HubConnectionTests.Protocol.ClientPingsMultipleTimes() in /_/test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.Protocol.cs:line 586
     at Microsoft.AspNetCore.SignalR.Client.Tests.HubConnectionTests.Protocol.ClientPingsMultipleTimes() in /_/test/Microsoft.AspNetCore.SignalR.Client.Tests/HubConnectionTests.Protocol.cs:line 592
  --- End of stack trace from previous location where exception was thrown ---
  Application startup exception: System.NotSupportedException: Duplicate definitions of 'OverloadedMethod'. Overloading is not supported.
     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DiscoverHubMethods() in /_/src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs:line 417
     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1..ctor(IServiceScopeFactory serviceScopeFactory, IHubContext`1 hubContext, IOptions`1 hubOptions, IOptions`1 globalHubOptions, ILogger`1 logger) in /_/src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubDispatcher.cs:line 38
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
     at Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions.UseConnectionHandler[TConnectionHandler](IConnectionBuilder connectionBuilder)
     at Microsoft.AspNetCore.SignalR.HubRouteBuilder.<>c__3`1.<MapHub>b__3_0(IConnectionBuilder builder) in /_/src/Microsoft.AspNetCore.SignalR/HubRouteBuilder.cs:line 58
     at Microsoft.AspNetCore.Http.Connections.ConnectionsRouteBuilder.MapConnections(PathString path, HttpConnectionDispatcherOptions options, Action`1 configure) in /_/src/Microsoft.AspNetCore.Http.Connections/ConnectionsRouteBuilder.cs:line 45
     at Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub[THub](PathString path, Action`1 configureOptions) in /_/src/Microsoft.AspNetCore.SignalR/HubRouteBuilder.cs:line 59
     at Microsoft.AspNetCore.SignalR.Tests.MapSignalRTests.<>c.<MapSignalRFailsForInvalidHub>b__0_1(HubRouteBuilder routes) in /_/test/Microsoft.AspNetCore.SignalR.Tests/MapSignalRTests.cs:line 18
     at Microsoft.AspNetCore.Builder.ConnectionsAppBuilderExtensions.UseConnections(IApplicationBuilder app, Action`1 configure) in /_/src/Microsoft.AspNetCore.Http.Connections/ConnectionsAppBuilderExtensions.cs:line 34
     at Microsoft.AspNetCore.Builder.SignalRAppBuilderExtensions.UseSignalR(IApplicationBuilder app, Action`1 configure) in /_/src/Microsoft.AspNetCore.SignalR/SignalRAppBuilderExtensions.cs:line 35
     at Microsoft.AspNetCore.SignalR.Tests.MapSignalRTests.<>c__DisplayClass9_0.<BuildWebHost>b__1(IApplicationBuilder app) in /_/test/Microsoft.AspNetCore.SignalR.Tests/MapSignalRTests.cs:line 139
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by anurse** [comment]
We can probably just fix this by increasing the timeout. Right now it only delays for `200` milliseconds. It makes sense that on a slow machine this might not be enough to get a ping message.

**Comment by JamesNK** [comment]
I already have a fix ready :)
