### ISSUE TITLE
Flaky test: Ping Automatically sends multiple pings

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2383]
This test [fails](http://aspnetci/viewLog.html?buildId=474619&buildTypeId=Lite_SignalR&tab=buildResultsDiv) occasionally with the following error:

```
FAIL signalr\tests\HubConnection.test.ts (28.872s)
[16:07:14] :	 [Step 4/7]     â—� HubConnection â€º ping â€º automatically sends multiple pings
[16:07:14] :	 [Step 4/7]   
[16:07:14] :	 [Step 4/7]       expect(received).toBeGreaterThanOrEqual(expected)
[16:07:14] :	 [Step 4/7]       
[16:07:14] :	 [Step 4/7]       Expected value to be greater than or equal:
[16:07:14] :	 [Step 4/7]         2
[16:07:14] :	 [Step 4/7]       Received:
[16:07:14] :	 [Step 4/7]         1
[16:07:14] :	 [Step 4/7]   
[16:07:14] :	 [Step 4/7]         61 | 
[16:07:14] :	 [Step 4/7]         62 |                 const numPings = connection.sentData.filter((s) => JSON.parse(s).type === MessageType.Ping).length;
[16:07:14] :	 [Step 4/7]       > 63 |                 expect(numPings).toBeGreaterThanOrEqual(2);
[16:07:14] :	 [Step 4/7]         64 |             } finally {
[16:07:14] :	 [Step 4/7]         65 |                 await hubConnection.stop();
[16:07:14] :	 [Step 4/7]         66 |             }
[16:07:14] :	 [Step 4/7]         
[16:07:14] :	 [Step 4/7]         at Object.<anonymous> (signalr/tests/HubConnection.test.ts:63:34)
[16:07:14] :	 [Step 4/7]         at step (node_modules/tslib/tslib.js:133:27)
[16:07:14] :	 [Step 4/7]         at Object.next (node_modules/tslib/tslib.js:114:57)
[16:07:14] :	 [Step 4/7]         at fulfilled (node_modules/tslib/tslib.js:104:62)
```

**Comment by anurse** [comment]
Ugh, I hate testing time-based features. We need to either increase this timeout or simply remove the test, it's the standard issue of parallel testing slowing down timers.

**Comment by anurse** [comment]
Let's start by just increasing the timeout, we understand well why it would flake out with a low timeout.

**Comment by anurse** [comment]
This was fixed in https://github.com/aspnet/SignalR/commit/f0f1df9b4afd16701db4f9d21a86ec9803c09fe1
