### ISSUE TITLE
Cannot read property 'Binary' when MessagePackHubProtocol is used

### ISSUE THREAD

**Issue by sharok** [aspnet/SignalR#2436]
* Versions of Client-Side NuGet/NPM Packages:

```
 "@aspnet/signalr": "1.0.0",
 "@aspnet/signalr-protocol-msgpack": "1.0.0",
```

* The Operating System on the Client (Windows/Linux/macOS): 
`Windows`

* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.):
`Chrome 67`

I have angular application and I want to use binary message encoding for my websocket,  when I write like this
 `.withHubProtocol(new signalR.protocols.msgpack.MessagePackHubProtocol())`

I got error:
```
Unhandled Promise rejection: Cannot read property 'Binary' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'Binary' of undefined
    at new MessagePackHubProtocol (signalr-protocol-msgpack.min.js:15)
    at new CoreModule (core.module.ts:101)
    at _createClass (core.js:9272)
    at _createProviderInstance$1 (core.js:9234)
    at initNgModule (core.js:9170)
    at new NgModuleRef_ (core.js:9899)
    at createNgModuleRef (core.js:9888)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:11719)
    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (core.js:12421)
    at core.js:4720 TypeError: Cannot read property 'Binary' of undefined
    at new MessagePackHubProtocol (http://localhost:4200/scripts.js:15606:32596)
    at new CoreModule (http://localhost:4200/main.js:405:120)
    at _createClass (http://localhost:4200/vendor.js:47068:20)
    at _createProviderInstance$1 (http://localhost:4200/vendor.js:47030:26)
    at initNgModule (http://localhost:4200/vendor.js:46966:32)
    at new NgModuleRef_ (http://localhost:4200/vendor.js:47695:9)
    at createNgModuleRef (http://localhost:4200/vendor.js:47684:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://localhost:4200/vendor.js:49515:12)
    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (http://localhost:4200/vendor.js:50217:25)
    at http://localhost:4200/vendor.js:42516:43
```

Also, I tried to use `MessagePackHubProtocol` from typescript  definitions directly:
 `.withHubProtocol(new MessagePackHubProtocol())`

But, I get the different error:
```
sdkERROR in ./node_modules/@aspnet/signalr-protocol-msgpack/dist/esm/MessagePackHubProtocol.js
Module not found: Error: Can't resolve 'buffer' in 'C:\Projects\folder\node_modules\@aspnet\signalr-protocol-msgpack\dist\esm'
ERROR in ./node_modules/msgpack5/node_modules/safe-buffer/index.js
Module not found: Error: Can't resolve 'buffer' in 'C:\Projects\folder\node_modules\msgpack5\node_modules\safe-buffer'
ERROR in ./node_modules/safe-buffer/index.js
Module not found: Error: Can't resolve 'buffer' in 'C:\Projects\folder\node_modules\safe-buffer'
i ｢wdm｣: Failed to compile.
```

**Comment by anurse** [comment]
How are you loading the SignalR script into the browser? Have you loaded `signalr.js` **before** `signalr.-protocol-msgpack.js`?

**Comment by sharok** [comment]
Yes, I forgot about it. Thanks.
