### ISSUE TITLE
NullReferenceException when disposing connection

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#244]
Not sure what the conditions are but I saw this in my console:
```
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/echo/negotiate
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 138.4393ms 200
fail: Microsoft.AspNetCore.Sockets.ConnectionManager[0]
      Failed disposing connection 150496f4-7486-4f7d-91b9-1322f927e24d
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Sockets.Internal.ConnectionState.<DisposeAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()
```

**Comment by BrennanConroy** [comment]
Oh yeah, I saw it too when debugging in VS https://github.com/aspnet/SignalR/pull/241/files#diff-56f70a1ad7b0f822fd88bf4ff8fee123R54

**Comment by davidfowl** [comment]
Hmm

**Comment by davidfowl** [comment]
@BrennanConroy can you look into this?

**Comment by davidfowl** [comment]
Seems like it's possible for DisposeAsync to be called without having ever set up the application or transport.

**Comment by davidfowl** [comment]
Yes, that must be it.

**Comment by BrennanConroy** [comment]
Fixed in https://github.com/aspnet/SignalR/pull/252
