### ISSUE TITLE
Flaky Test: CanStartConnectionFromClosedEvent

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2447]
```
Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(protocolName: "json", transportType: WebSockets, path: "/default")
RUNDOTNET : error Message:  [/home/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17067/KoreBuild.proj]
   System.Exception : 2 error(s) logged.
  Microsoft.AspNetCore.SignalR.Client.HubConnection - ErrorDuringClosedEvent - An exception was thrown in the handler for the Closed event.
  ===================
  System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
  Parameter name: index
     at Microsoft.AspNetCore.SignalR.Client.Internal.ConnectionLogScope.get_Item(Int32 index) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/ConnectionLogScope.cs:line 38
     at Microsoft.AspNetCore.SignalR.Client.Internal.ConnectionLogScope.GetEnumerator()+MoveNext() in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/ConnectionLogScope.cs:line 46
     at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
     at Microsoft.AspNetCore.SignalR.Tests.WrappingLoggerFactory.WrappingLogger.<>c__DisplayClass6_0.<GetConnectionId>b__0(Object scope, Object s) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/WrappingLoggerFactory.cs:line 107
     at Microsoft.Extensions.Logging.LoggerExternalScopeProvider.ForEachScope[TState](Action`2 callback, TState state)
     at Microsoft.AspNetCore.SignalR.Tests.WrappingLoggerFactory.WrappingLogger.GetConnectionId() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/WrappingLoggerFactory.cs:line 113
     at Microsoft.AspNetCore.SignalR.Tests.WrappingLoggerFactory.WrappingLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/WrappingLoggerFactory.cs:line 77
     at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
     at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
     at Microsoft.AspNetCore.SignalR.Client.HubConnection.RunClosedEvent(Func`2 closed, Exception closeException) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 959
  ===================
  Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests - 0 - System.TimeoutException from test
  ===================
  System.TimeoutException: Operation in CanStartConnectionFromClosedEvent timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:206
     at System.Threading.Tasks.TaskExtensions.OrTimeout[T](Task`1 task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber)
     at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(String protocolName, HttpTransportType transportType, String path) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 206
     at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(String protocolName, HttpTransportType transportType, String path) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 220
  ===================
  Stack Trace:
     at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifyNoErrorsScope.cs:line 63
     at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 66
     at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(String protocolName, HttpTransportType transportType, String path) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 222
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   | [0.001s] TestLifetime Information: Starting test CanStartConnectionFromClosedEvent-json-WebSockets-/default at 2018-06-07T16:27:10
   | [0.000s] TestLifetime Information: Starting test CanStartConnectionFromClosedEvent_json_WebSockets_default at 2018-06-07T16:27:10
   | [0.000s] ServerLogScope Information: Server log scope started.
   | [0.001s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:288).
   | [0.001s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
   | [0.001s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
   | [0.001s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:43836/default'.
   | [0.001s] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:43836/default/negotiate'.
   | [0.002s] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLECIDK7FVDF" started.
   | [0.002s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:43836/default/negotiate  0
   | [0.002s] SERVER Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Debug: AuthenticationScheme: Bearer was not authenticated.
   | [0.002s] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/default/negotiate'.
   | [0.002s] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: New connection axzVbyqgsM6MEAs-yf7x2A created.
   | [0.003s] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: axzVbyqgsM6MEAs-yf7x2A - Sending negotiation response.
   | [0.003s] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLECIDK7FVDF" completed keep alive response.
   | [0.003s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.0031ms 200 application/json
   | [0.008s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Established connection 'axzVbyqgsM6MEAs-yf7x2A' with the server.
   | [0.008s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Starting transport 'WebSockets' with Url: http://127.0.0.1:43836/default?id=axzVbyqgsM6MEAs-yf7x2A.
   | [0.008s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: axzVbyqgsM6MEAs-yf7x2A - Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:43836/default?id=axzVbyqgsM6MEAs-yf7x2A'.
   | [0.009s] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLECIDK7FVDG" started.
   | [0.009s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:43836/default?id=axzVbyqgsM6MEAs-yf7x2A  
   | [0.009s] SERVER Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Debug: AuthenticationScheme: Bearer was not authenticated.
   | [0.009s] SERVER Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/default'.
   | [0.010s] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: axzVbyqgsM6MEAs-yf7x2A - Establishing new connection.
   | [0.010s] SERVER Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Socket opened using Sub-Protocol: '(null)'.
   | [0.010s] SERVER Microsoft.AspNetCore.SignalR.HubConnectionHandler Debug: axzVbyqgsM6MEAs-yf7x2A - OnConnectedAsync started.
   | [0.010s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Transport 'WebSockets' started.
   | [0.010s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: axzVbyqgsM6MEAs-yf7x2A - HttpConnection Started.
   | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: axzVbyqgsM6MEAs-yf7x2A - Using HubProtocol 'json v1'.
   | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Sending Hub Handshake.
   | [0.011s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Received message from application. Payload size: 32.
   | [0.011s] SERVER Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver Debug: axzVbyqgsM6MEAs-yf7x2A - Found protocol implementation for requested protocol: json.
   | [0.011s] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Information: axzVbyqgsM6MEAs-yf7x2A - Completed connection handshake. Using HubProtocol 'json'.
   | [0.012s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Message received. Type: Text, size: 3, EndOfMessage: True.
   | [0.012s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Handshake with server complete.
   | [0.012s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Receive loop starting.
   | [0.012s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Sending PingMessage message.
   | [0.012s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Sending PingMessage message completed.
   | [0.012s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: axzVbyqgsM6MEAs-yf7x2A - HubConnection started.
   | [0.012s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Releasing Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:331).
   | [0.012s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Received message from application. Payload size: 11.
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Waiting on Connection Lock in InvokeCoreAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:442).
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.Internal.InvocationRequest.NonStreaming Trace: axzVbyqgsM6MEAs-yf7x2A - Invocation 1 created.
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Preparing blocking invocation '1' of 'Echo', with return type 'System.String' and 1 argument(s).
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Registering Invocation ID '1' for tracking.
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Issuing Invocation '1': System.String Echo(System.String).
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Sending InvocationMessage message '1'.
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Sending InvocationMessage message '1' completed.
   | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Releasing Connection Lock in InvokeCoreAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:455).
   | [0.013s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Received message from application. Payload size: 70.
   | [0.014s] SERVER Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher Debug: axzVbyqgsM6MEAs-yf7x2A - Received hub invocation: InvocationMessage { InvocationId: "1", Target: "Echo", Arguments: [ SignalR ] }.
   | [0.014s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Message received. Type: Text, size: 49, EndOfMessage: True.
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Resetting keep-alive timer, received a message from the server.
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Processing 49 byte message from server.
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Received Completion for Invocation 1.
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.Internal.InvocationRequest.NonStreaming Trace: axzVbyqgsM6MEAs-yf7x2A - Invocation 1 marked as completed.
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.Internal.InvocationRequest.NonStreaming Trace: axzVbyqgsM6MEAs-yf7x2A - Invocation 1 disposed.
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Stopping connection
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Waiting on Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:347).
   | [0.014s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Releasing Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:374).
   | [0.015s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Stopping HubConnection.
   | [0.015s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Terminating receive loop.
   | [0.015s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Waiting for the receive loop to terminate.
   | [0.015s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Waiting on Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:837).
   | [0.015s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Releasing Connection Lock in ReceiveLoop (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:846).
   | [0.015s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Disposing HttpConnection.
   | [0.015s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: axzVbyqgsM6MEAs-yf7x2A - Transport is stopping.
   | [0.015s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Send loop stopped.
   | [0.015s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Transport stopped.
   | [0.015s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: axzVbyqgsM6MEAs-yf7x2A - HttpConnection Disposed.
   | [0.015s] SERVER Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Waiting for the application to finish sending data.
   | [0.016s] SERVER Microsoft.AspNetCore.SignalR.HubConnectionHandler Debug: axzVbyqgsM6MEAs-yf7x2A - OnConnectedAsync ending.
   | [0.016s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Receive loop canceled.
   | [0.016s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - Canceling all outstanding invocations.
   | [0.016s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Receive loop stopped.
   | [0.016s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: axzVbyqgsM6MEAs-yf7x2A - Shutting down connection.
   | [0.016s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: axzVbyqgsM6MEAs-yf7x2A - HubConnection stopped.
   | [0.016s] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Information: Waiting for reconnect
   | [0.016s] SERVER Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport Debug: axzVbyqgsM6MEAs-yf7x2A - Socket closed.
   | [0.017s] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLECIDK7FVDG" reset.
   | [0.017s] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLECIDK7FVDG" sending FIN.
   | [0.017s] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLECIDK7FVDG" disconnecting.
   | [0.017s] SERVER Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: axzVbyqgsM6MEAs-yf7x2A - Removing connection axzVbyqgsM6MEAs-yf7x2A from the list of connections.
   | [0.017s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 8.0455ms 101 
RUNDOTNET : | [0.016s] Microsoft.AspNetCore.SignalR.Client.HubConnection error : An exception was thrown in the handler for the Closed event. [/home/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17067/KoreBuild.proj]
   | System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   | Parameter name: index
   |    at Microsoft.AspNetCore.SignalR.Client.Internal.ConnectionLogScope.get_Item(Int32 index) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/ConnectionLogScope.cs:line 38
   |    at Microsoft.AspNetCore.SignalR.Client.Internal.ConnectionLogScope.GetEnumerator()+MoveNext() in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/Internal/ConnectionLogScope.cs:line 46
   |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   |    at Microsoft.AspNetCore.SignalR.Tests.WrappingLoggerFactory.WrappingLogger.<>c__DisplayClass6_0.<GetConnectionId>b__0(Object scope, Object s) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/WrappingLoggerFactory.cs:line 107
   |    at Microsoft.Extensions.Logging.LoggerExternalScopeProvider.ForEachScope[TState](Action`2 callback, TState state)
   |    at Microsoft.AspNetCore.SignalR.Tests.WrappingLoggerFactory.WrappingLogger.GetConnectionId() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/WrappingLoggerFactory.cs:line 113
   |    at Microsoft.AspNetCore.SignalR.Tests.WrappingLoggerFactory.WrappingLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/WrappingLoggerFactory.cs:line 77
   |    at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   |    at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
   |    at Microsoft.AspNetCore.SignalR.Client.HubConnection.RunClosedEvent(Func`2 closed, Exception closeException) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 959
   | [0.015s] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLECIDK7FVDG" received FIN.
   | [0.019s] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLECIDK7FVDF" received FIN.
   | [0.019s] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLECIDK7FVDG" stopped.
   | [0.019s] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLECIDK7FVDF" disconnecting.
   | [0.019s] SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLECIDK7FVDF" sending FIN.
   | [0.019s] SERVER Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLECIDK7FVDF" stopped.
RUNDOTNET : | [5.020s] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests error : System.TimeoutException from test [/home/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17067/KoreBuild.proj]
   | System.TimeoutException: Operation in CanStartConnectionFromClosedEvent timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:206
   |    at System.Threading.Tasks.TaskExtensions.OrTimeout[T](Task`1 task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber)
   |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.CanStartConnectionFromClosedEvent(String protocolName, HttpTransportType transportType, String path) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 206
   | [5.021s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:347).
   | [5.021s] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StopAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:374).
   | [5.021s] ServerLogScope Information: Server log scope stopped.
   | [5.022s] TestLifetime Information: Finished test CanStartConnectionFromClosedEvent_json_WebSockets_default in 5.0212337s
   | [5.126s] TestLifetime Information: Finished test CanStartConnectionFromClosedEvent-json-WebSockets-/default in 5.1254671s
```

**Comment by BrennanConroy** [comment]
There is a race between https://github.com/aspnet/SignalR/blob/e41764c161574983c49362cfb29ce23eb5941b74/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs#L1219
and the scope being disposed
https://github.com/aspnet/SignalR/blob/e41764c161574983c49362cfb29ce23eb5941b74/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs#L156-L159
where if a log occurs then an `ArgumentOutOfRangeException` can occur

**Comment by anurse** [comment]
Just protect against `null` in the `ConnectionLogScope`.
