### ISSUE TITLE
Connection closing from C# client returning a string

### ISSUE THREAD

**Issue by samcov** [aspnet/SignalR#2483]
**Info**: Using NuGet Packages: Microsoft.AspNetCore.SignalR 1.0 for the hub, Microsoft.AspNetCore.SignalR.Client for the C# client, Using Kestrel on Windows, with Chrome as the browser. I am also using the DefaultContractResolver() in the c# client.

Mostly everything works, but this case proves to be a problem. At first I thought it was the json I was returning, but then I tried something very simple. I return a string to the hub, but once it gets big, it crashes(Note: When I return the exact same strings using the javascript client, there is no problem, only in the c# client)
```csharp
if (hconn != null)
{
     for(int i=0; i < 100; i++)// **at 100, it returns to the hub, at 100000, it crashes**
     {
         s += "Hello ! ";
     }
     await hconn.InvokeAsync("SendToClient", connectionid, callback, s);
}
```
**If it helps, here is the error I see in the console**
```csharp
fail: Microsoft.AspNetCore.SignalR.HubConnectionHandler[2]
      Error when processing requests.
System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_BackpressureDeadlock()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
   
   fail: Microsoft.AspNetCore.SignalR.HubConnectionHandler[2]
      Error when processing requests.
System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_BackpressureDeadlock()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```

**Comment by anurse** [comment]
This occurs if you try to write a very large single message. It is possible to increase this limit, but I would advise against it. Sending a very large single message is not recommended. Instead, you could stream large messages down to the client in fragments using the [Streaming Return Values](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.1) support. The default maximum message size is 32KB.

If you absolutely must return a large value, you can disable the limits by setting the `TransportMaxBufferSize` setting in your `.MapHub` call:

```csharp
// In Startup.Configure
app.UseSignalR(routes => {
    routes.MapHub<SomeHub>("/somehub", options => {
        // Set to 0 for no limit, or to some non-zero value (in bytes) to set a different buffer limit
        options.TransportMaxBufferSize = 0;
    });
});
```

**Comment by samcov** [comment]
I'm in total agreement with NOT increasing this limit, I just needed to know that I wasn't crazy :)

This is a special case, so I'll use the streaming return in that case, or modify how we're doing it.

Thanks for the reply... moving on!

**Comment by anurse** [comment]
The error message isn't really very clear, so I filed https://github.com/aspnet/SignalR/issues/2486 to clean that up.

**Comment by samcov** [comment]
Thanks, and do you know what the default buffer size is?

**Comment by samcov** [comment]
Don't bother, I found it(32K).

private const int DefaultPipeBufferSize = 32768;

**Comment by anurse** [comment]
> The default maximum message size is 32KB.

😄

**Comment by samcov** [comment]
BTW, is that a 2 way limit?

I can send > 32k **from the hub** to the JS Client, but I can't sent > 32k from the C# Client **to the hub**, the opposite flow.

**Comment by anurse** [comment]
It's not 2 way, due to some details of how Pipelines (the underlying buffering/streaming APIs we're using) handles backpressure. @davidfowl might have more context here. I believe we are not limited in the same way when writing messages out to the client.

**Comment by davidfowl** [comment]
We have to buffer incoming messages we don’t have to buffer outgoing messages written to the client. That’s why there’s a difference.

**Comment by samcov** [comment]
This is GREAT information because it allows me to design our system much better because I now know the limitations. Thanks guys!!!
