### ISSUE TITLE
Flaky JavaScript tests due to sending pings

### ISSUE THREAD

**Issue by anurse** [aspnet/SignalR#2537]
One of the JavaScript tests is flaky. I think it's because a ping timer is firing but the connection is closed.

```
13:08:04   PASS signalr\tests\JsonHubProtocol.test.ts (35.863s)
13:08:09   PASS signalr\tests\HubConnection.test.ts (43.478s)
13:08:20   PASS signalr\tests\HttpConnection.test.ts (52.72s)
13:08:20   PASS signalr\tests\HubConnectionBuilder.test.ts (17.735s)
13:08:30   PASS signalr\tests\ServerSentEventsTransport.test.ts (9.669s)
13:08:30   PASS signalr\tests\WebSocketTransport.test.ts (12.141s)
13:08:35   PASS signalr-protocol-msgpack\tests\MessagePackHubProtocol.test.ts (25.532s)
13:08:35   PASS signalr\tests\LongPollingTransport.test.ts (5.53s)
13:08:35   D:\j\workspace\windows-es-Co---c109db11\clients\ts\signalr\src\HttpConnection.ts:88
13:08:35               throw new Error("Cannot send data if the connection is not in the 'Connected' State.");
13:08:35               ^
13:08:35   
13:08:35   Error: Cannot send data if the connection is not in the 'Connected' State.
13:08:35       at HttpConnection.Object.<anonymous>.HttpConnection.send (D:\j\workspace\windows-es-Co---c109db11\clients\ts\signalr\src\HttpConnection.ts:88:19)
13:08:35       at HubConnection.Object.<anonymous>.HubConnection.sendMessage (D:\j\workspace\windows-es-Co---c109db11\clients\ts\signalr\src\HubConnection.ts:187:32)
13:08:35       at Timeout.<anonymous> (D:\j\workspace\windows-es-Co---c109db11\clients\ts\signalr\src\HubConnection.ts:381:71)
13:08:35       at ontimeout (timers.js:427:11)
13:08:35       at tryOnTimeout (timers.js:289:5)
13:08:35       at listOnTimeout (timers.js:252:5)
13:08:35       at Timer.processTimers (timers.js:212:10)
```

**Comment by anurse** [comment]
All we need to do here is catch the exception in the `setTimeout` handler so it doesn't escape. We don't care if sending a ping throws for this reason since the connection is shut down anyway.

https://github.com/aspnet/SignalR/blob/9f79c831598a807aa301b8a0413a535edb1c20f1/clients/ts/signalr/src/HubConnection.ts#L409

**Comment by anurse** [comment]
This hasn't shown up in a while. If it pops back up, we can revisit it.

**Comment by anurse** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
Fixed!
