### ISSUE TITLE
Compilation fails on macOS High Sierra: "TypeError: The argument 'path' must be a string or Uint8Array without null bytes."

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/SignalR#2670]
The latest builds of the ~~release/2.2~~ release/2.1 branch fail on our macOS High Sierra agents.

```
[04:27:22]  SignalR               |   /Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/signalr-protocol-msgpack/dist/cjs/browser-index.js → ./dist/browser/signalr-protocol-msgpack.js...
[04:27:22]  SignalR               |   [!] TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/signalr-protocol-msgpack/\u0000commonjs-e...
[04:27:22]  SignalR               |   TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/signalr-protocol-msgpack/\u0000commonjs-e...
[04:27:22]  SignalR               |       at Object.stat (fs.js:794:3)
[04:27:22]  SignalR               |       at isFile (/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/resolve/lib/async.js:22:12)
[04:27:22]  SignalR               |       at loadpkg (/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/resolve/lib/async.js:118:9)
[04:27:22]  SignalR               |       at load (/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/resolve/lib/async.js:85:18)
[04:27:22]  SignalR               |       at loadAsFile (/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/resolve/lib/async.js:77:9)
[04:27:22]  SignalR               |       at processDirs (/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/resolve/lib/async.js:186:9)
[04:27:22]  SignalR               |       at loadNodeModules (/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/resolve/lib/async.js:201:9)
[04:27:22]  SignalR               |       at resolve (/Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/resolve/lib/async.js:43:12)
[04:27:22]  SignalR               |       at /Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/SignalR/clients/ts/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:76:5
[04:27:22]  SignalR               |       at new Promise (<anonymous>)
```
http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=512264&_focus=8074

**Comment by anurse** [comment]
Sounds like a node version mismatch. What version of Node is running on the High Sierra agent?

**Comment by natemcmaster** [comment]
10.5

**Comment by natemcmaster** [comment]
It's just release/2.1. I was looking at the wrong thing when I filed the issue. I think @BrennanConroy's PR #2641 was supposed to address this.

**Comment by anurse** [comment]
Indeed it is.

**Comment by anurse** [comment]
I'll put this in 2.1.4 and we can resolve it with #2641

**Comment by BrennanConroy** [comment]
@Eilon for 2.1.4 consideration

**Comment by anurse** [comment]
> there isn't a great way to be sure that it works the exact same across all scenarios.

To be clear, we **do** use the WebPack output when running our Functional Tests. So our Functional Tests currently **pass** with the new output JavaScript produced by WebPack. So while there's no reasonable way to confirm that the code is identical (because WebPack inserts different boilerplate and rewrites some things a little differently), our Functional Tests do give us some coverage on this new build.

**Comment by Eilon** [comment]
Sorry for the delay, this is approved for 2.1.4, but let's not shipped the changed package (unless we end up doing a functional fix) because we're only doing this to fix the build.

**Comment by anurse** [comment]
FYI, we may want to consider #2692 for 2.1.4 which would result in shipping the package. Not directly relevant to this, but I just want to make it clear there's a possibility we'll be shipping this in 2.1.4 if that's approved.

**Comment by BrennanConroy** [comment]
Merged, should be fixed
