### ISSUE TITLE
Flaky test: StreamDoesNotStartIfTokenAlreadyCanceled

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2675]
This test [fails](http://aspnetci/viewLog.html?buildId=514205&buildTypeId=Releases_21Public_Win2012) occasionally with the following error:
```
System.Exception : 1 error(s) logged.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection - TransportThrewExceptionOnStop - The transport threw an exception while stopping.
===================
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.SendUtils.<SendMessages>d__0.MoveNext() in /_/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/SendUtils.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport.<ProcessAsync>d__18.MoveNext() in /_/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ServerSentEventsTransport.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport.<StopAsync>d__20.MoveNext() in /_/src/Microsoft.AspNetCore.Http.Connections.Client/Internal/ServerSentEventsTransport.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<DisposeAsyncCore>d__43.MoveNext() in /_/src/Microsoft.AspNetCore.Http.Connections.Client/HttpConnection.cs:line 256
===================
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifyNoErrorsScope.cs:line 63
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 66
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<StreamDoesNotStartIfTokenAlreadyCanceled>d__12.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 424
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [2018-07-25T01:11:07] TestLifetime Information: Starting test StreamDoesNotStartIfTokenAlreadyCanceled_json_ServerSentEvents_hubT
| [2018-07-25T01:11:07] ServerLogScope Information: Server log scope started.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncCore (/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:211).
| [2018-07-25T01:11:07] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:57032/hubT'.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:57032/hubT/negotiate'.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFHPDREK8JO" started.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:57032/hubT/negotiate  0
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Debug: AuthenticationScheme: Bearer was not authenticated.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Routing.RouteBase Debug: Request successfully matched the route with name '(null)' and template '/hubT/negotiate'.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: New connection pryDiUe2EYfvErXiZUI6_A created.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: Sending negotiation response.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFHPDREK8JO" completed keep alive response.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.9709ms 200 application/json
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Established connection 'pryDiUe2EYfvErXiZUI6_A' with the server.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Skipping transport WebSockets because it was disabled by the client.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'ServerSentEvents' with Url: http://127.0.0.1:57032/hubT?id=pryDiUe2EYfvErXiZUI6_A.
| [2018-07-25T01:11:07] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Information: Starting transport
...
```

**Comment by anurse** [comment]
It sounds like it's an unavoidable race. Just suppress it in the test then.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/pull/2739 Fixed
