### ISSUE TITLE
Flaky test: ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2681]
This test [fails](http://aspnetci/viewLog.html?buildId=515652&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.Exception : 1 error(s) logged.
SERVER Microsoft.AspNetCore.Server.Kestrel - ApplicationNeverCompleted - Connection id "0HLFII9ADGRCF" application never completed
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible-messagepack-WebSockets-/dynamic at 2018-07-26T00:54:33
| [0.002s] TestLifetime Information: Starting test ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible_messagepack_WebSockets_dynamic at 2018-07-26T00:54:33
| [0.002s] ServerLogScope Information: Server log scope started.
| [0.003s] SERVER Microsoft.AspNetCore.Server.Kestrel Critical: Connection id "0HLFII9ADGRCF" application never completed
| [0.004s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:64362/dynamic/negotiate  0
| [0.004s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.9174ms 200 application/json
| [0.005s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: pmhYnEBwumYuIS6T-1xqKQ - Starting transport. Transfer mode: Binary. Url: 'ws://127.0.0.1:64362/dynamic?id=pmhYnEBwumYuIS6T-1xqKQ'.
| [0.005s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:64362/dynamic?id=pmhYnEBwumYuIS6T-1xqKQ  
| [0.007s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: pmhYnEBwumYuIS6T-1xqKQ - HttpConnection Started.
| [0.007s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: pmhYnEBwumYuIS6T-1xqKQ - Using HubProtocol 'messagepack v1'.
| [0.008s] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Information: pmhYnEBwumYuIS6T-1xqKQ - Completed connection handshake. Using HubProtocol 'messagepack'.
| [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: pmhYnEBwumYuIS6T-1xqKQ - HubConnection started.
| [0.012s] SERVER Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher Error: pmhYnEBwumYuIS6T-1xqKQ - A streaming method returned a value that cannot be used to build enumerator StreamBroken.
| [0.012s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: pmhYnEBwumYuIS6T-1xqKQ - Transport is stopping.
| [0.012s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: pmhYnEBwumYuIS6T-1xqKQ - HttpConnection Disposed.
| [0.013s] ServerLogScope Information: Server log scope stopped.
| [0.013s] TestLifetime Information: Finished test ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible_messagepack_WebSockets_dynamic in 0.0109596s
| [0.117s] TestLifetime Information: Finished test ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible-messagepack-WebSockets-/dynamic in 0.1152771s
```

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by BrennanConroy** [comment]
Server was failing because of a bug in our test logger. There is a race between the logger being disposed by the test and the server still writing logs.

Fix is #TODO
