### ISSUE TITLE
Flaky test: ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2684]
This test [fails](http://aspnetci/viewLog.html?buildId=515720&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.TimeoutException : Operation in ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport timed out at /_/test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs:360
   at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber)
   at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport(String message) in /_/test/Microsoft.AspNetCore.SignalR.Tests/EndToEndTests.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
***** Text was not loaded fully because its' size exceeds 2 MB, see full log for the whole text *****
```

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by BrennanConroy** [comment]
The logs indicate it took 10 seconds for the `websocket.ConnectAsync` call to actually send an http request to the server.
I went through the last 5500 test runs where this test was present and none of them failed. So I'm going to chalk this up to a weird machine issue at the time.

@ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
Which item on the checklist is that?

**Comment by BrennanConroy** [comment]
If it fails again we can look at adding retries etc.

But I'm saying this is likely a glitch in the matrix and there is no reason we need to change the test.

**Comment by anurse** [comment]
Reviewed the logs with Brennan. It looks like we're going to need to invest in a bunch more tracing (capturing network traffic, perhaps capturing dumps) in order to identify this issue. It's not in our code, or at least not directly. The delay is between when we invoke `System.Net.WebSockets.WebSocket.ConnectAsync` and when the server receives the WebSocket request. We have no local repro to debug against. We could engage someone from corefx, but I don't think they'll be able to help without more data.

@Eilon @muratg please advise on priorities here. Adding the kind of traces we'd need here would be a significant work item and would likely bump other work.

**Comment by Eilon** [comment]
I'm OK with deprioritizing this given how rare it is, but I do want us to end up doing *something* for this, such as adding more diagnostic data. I'm concerned that there could be an underlying *product* bug here, though clearly one that wouldn't hit often.

**Comment by anurse** [comment]
> adding more diagnostic data

Ok, as I said above the diagnostic data we need now comes from either *inside* corefx or from network tracing. This is what will be a fairly significant effort. So we'll need to make this a properly costed work item.

**Comment by aspnet-hello** [comment]
SSEWontStartIfSuccessfulConnectionIsNotEstablished [failed with about the same error](http://aspnetci/viewLog.html?buildId=541323&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by BrennanConroy** [comment]
The latest bot comment is for the 2 flaky tests we resolved with https://github.com/aspnet/SignalR/pull/2880 so can be ignored

**Comment by aspnet-hello** [comment]
CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser [failed with about the same error](http://aspnetci/viewLog.html?buildId=544660&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by anurse** [comment]
The latest comment is unrelated Redis failures which were already resolved by https://github.com/aspnet/SignalR/issues/2894. Unfortunately it looks like RaaS is tagging any timeout failure as related to this issue... 

The original failure was deemed rare enough and fixing it was very high cost so we deprioritized this heavily, but if we leave it open it looks like RaaS is just going to ping it with every timeout failure. Thoughts @Eilon ?
