### ISSUE TITLE
Flaky test: NegotiationSkipsServerSentEventsWhenUsingBinaryProtocol

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#2725]
https://ci3.dot.net/job/aspnet_SignalR/job/release_2.2/job/windows-Configuration_Release_prtest/95/console

```
Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport - ErrorPolling - eXjr8LqvoszOSOcqNdsrXQ - Error while polling 'http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ'.
12:57:08   ===================
12:57:08   System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
12:57:08      at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
12:57:08      at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
12:57:08      at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
12:57:08      at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
12:57:08      at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
12:57:08      at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
12:57:08   --- End of stack trace from previous location where exception was thrown ---
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08      at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
12:57:08   --- End of stack trace from previous location where exception was thrown ---
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08      at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
12:57:08   --- End of stack trace from previous location where exception was thrown ---
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08      at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.<Poll>d__19.MoveNext()
12:57:08   ===================
12:57:08   Stack Trace:
12:57:08      at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose()
12:57:08      at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose()
12:57:08      at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<NegotiationSkipsServerSentEventsWhenUsingBinaryProtocol>d__30.MoveNext()
12:57:08   --- End of stack trace from previous location where exception was thrown ---
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08   --- End of stack trace from previous location where exception was thrown ---
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08   --- End of stack trace from previous location where exception was thrown ---
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08   Standard Output Messages:
12:57:08    | [0.001s] TestLifetime Information: Starting test NegotiationSkipsServerSentEventsWhenUsingBinaryProtocol at 2018-08-02T19:57:07
12:57:08    | [0.001s] TestLifetime Information: Starting test NegotiationSkipsServerSentEventsWhenUsingBinaryProtocol at 2018-08-02T19:57:07
12:57:08    | [0.001s] ServerLogScope Information: Server log scope started.
12:57:08    | [0.002s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:51611/default-nowebsockets/negotiate  0
12:57:08    | [0.003s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7099ms 200 application/json
12:57:08    | [0.004s] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: eXjr8LqvoszOSOcqNdsrXQ - Starting transport. Transfer mode: Binary.
12:57:08    | [0.004s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.005s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6157ms 200 application/octet-stream
12:57:08    | [0.005s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: eXjr8LqvoszOSOcqNdsrXQ - HttpConnection Started.
12:57:08    | [0.005s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: eXjr8LqvoszOSOcqNdsrXQ - Using HubProtocol 'messagepack v1'.
12:57:08    | [0.005s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.006s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  39
12:57:08    | [0.007s] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Information: eXjr8LqvoszOSOcqNdsrXQ - Completed connection handshake. Using HubProtocol 'messagepack'.
12:57:08    | [0.007s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7494ms 200 text/plain
12:57:08    | [0.007s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: eXjr8LqvoszOSOcqNdsrXQ - HubConnection started.
12:57:08    | [0.007s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.9418ms 200 application/octet-stream
12:57:08    | [0.007s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.007s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  3
12:57:08    | [0.008s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6955ms 200 application/octet-stream
12:57:08    | [0.008s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.9046ms 200 text/plain
12:57:08    | [0.008s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.009s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6541ms 200 application/octet-stream
12:57:08    | [0.009s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.010s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  30
12:57:08    | [0.010s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.64ms 200 application/octet-stream
12:57:08    | [0.011s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.9332ms 200 text/plain
12:57:08    | [0.011s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.012s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6778ms 200 application/octet-stream
12:57:08    | [0.012s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.013s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6847ms 200 application/octet-stream
12:57:08    | [0.013s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.014s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6507ms 200 application/octet-stream
12:57:08    | [0.014s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.015s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6531ms 200 application/octet-stream
12:57:08    | [0.015s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.016s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6426ms 200 application/octet-stream
12:57:08    | [0.016s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.017s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6386ms 200 application/octet-stream
12:57:08    | [0.017s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.018s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6164ms 200 application/octet-stream
12:57:08    | [0.018s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.018s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6423ms 200 application/octet-stream
12:57:08    | [0.019s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.020s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6204ms 200 application/octet-stream
12:57:08    | [0.020s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.020s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6163ms 200 application/octet-stream
12:57:08    | [0.021s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.021s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6084ms 200 application/octet-stream
12:57:08    | [0.021s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.022s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.8225ms 200 application/octet-stream
12:57:08    | [0.023s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.023s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5374ms 200 application/octet-stream
12:57:08    | [0.023s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.024s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5751ms 200 application/octet-stream
12:57:08    | [0.024s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.025s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5589ms 200 application/octet-stream
12:57:08    | [0.025s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.025s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6185ms 200 application/octet-stream
12:57:08    | [0.026s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.026s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5479ms 200 application/octet-stream
12:57:08    | [0.026s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.027s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6617ms 200 application/octet-stream
12:57:08    | [0.027s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.028s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.606ms 200 application/octet-stream
12:57:08    | [0.028s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.030s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.556ms 200 application/octet-stream
12:57:08    | [0.030s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.031s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7491ms 200 application/octet-stream
12:57:08    | [0.031s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.032s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7717ms 200 application/octet-stream
12:57:08    | [0.032s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.032s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5609ms 200 application/octet-stream
12:57:08    | [0.033s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.033s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6366ms 200 application/octet-stream
12:57:08    | [0.033s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.034s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6247ms 200 application/octet-stream
12:57:08    | [0.034s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.040s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 5.7581ms 200 application/octet-stream
12:57:08    | [0.040s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.041s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7095ms 200 application/octet-stream
12:57:08    | [0.041s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.042s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5918ms 200 application/octet-stream
12:57:08    | [0.042s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.043s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.7142ms 200 application/octet-stream
12:57:08    | [0.043s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.044s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5141ms 200 application/octet-stream
12:57:08    | [0.044s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.044s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5869ms 200 application/octet-stream
12:57:08    | [0.045s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.046s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.9368ms 200 application/octet-stream
12:57:08    | [0.046s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.047s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6458ms 200 application/octet-stream
12:57:08    | [0.047s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  
12:57:08    | [0.047s] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: eXjr8LqvoszOSOcqNdsrXQ - Transport is stopping.
12:57:08    | [0.047s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6077ms 200 application/octet-stream
12:57:08    | [0.048s] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Error: eXjr8LqvoszOSOcqNdsrXQ - Error while polling 'http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ'.
12:57:08    | System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
12:57:08    |    at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
12:57:08    |    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
12:57:08    |    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
12:57:08    |    at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
12:57:08    |    at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
12:57:08    |    at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
12:57:08    | --- End of stack trace from previous location where exception was thrown ---
12:57:08    |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08    |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08    |    at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
12:57:08    | --- End of stack trace from previous location where exception was thrown ---
12:57:08    |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08    |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08    |    at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
12:57:08    | --- End of stack trace from previous location where exception was thrown ---
12:57:08    |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:57:08    |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:57:08    |    at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.<Poll>d__19.MoveNext()
12:57:08    | [0.048s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 DELETE http://127.0.0.1:51611/default-nowebsockets?id=eXjr8LqvoszOSOcqNdsrXQ  0
12:57:08    | [0.049s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: eXjr8LqvoszOSOcqNdsrXQ - HttpConnection Disposed.
12:57:08    | [0.049s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.4403ms 202 text/plain
12:57:08    | [0.049s] ServerLogScope Information: Server log scope stopped.
12:57:08    | [0.049s] TestLifetime Information: Finished test NegotiationSkipsServerSentEventsWhenUsingBinaryProtocol in 0.0481985s
```

**Comment by BrennanConroy** [comment]
Probably will be fixed by https://github.com/aspnet/SignalR/pull/2731/files
