### ISSUE TITLE
Test failure: CheckFixedMessage

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#2733]
This test [fails](http://aspnetci/viewLog.html?buildId=523664&buildTypeId=Releases_22xPublic_Win2012) occasionally with the following error:
```
System.Exception : 1 error(s) logged.
Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport - ErrorPolling - pGXNG5FYJ8-vYtT1Cdzqig - Error while polling 'http://127.0.0.1:51024/hubT?id=pGXNG5FYJ8-vYtT1Cdzqig'.
===================
System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.<Poll>d__19.MoveNext()
===================
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose()
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<CheckFixedMessage>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test CheckFixedMessage-messagepack-LongPolling-/hubT at 2018-08-03T23:28:08
| [0.001s] TestLifetime Information: Starting test CheckFixedMessage_messagepack_LongPolling_hubT at 2018-08-03T23:28:08
| [0.001s] ServerLogScope Information: Server log scope started.
| [0.006s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:51024/hubT/negotiate  0
| [0.007s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6478ms 200 application/json
| [0.007s] Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport Information: pGXNG5FYJ8-vYtT1Cdzqig - Starting transport. Transfer mode: Binary.
| [0.007s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51024/hubT?id=pGXNG5FYJ8-vYtT1Cdzqig  
| [0.008s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5401ms 200 application/octet-stream
| [0.008s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: pGXNG5FYJ8-vYtT1Cdzqig - HttpConnection Started.
| [0.008s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: pGXNG5FYJ8-vYtT1Cdzqig - Using HubProtocol 'messagepack v1'.
| [0.008s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51024/hubT?id=pGXNG5FYJ8-vYtT1Cdzqig  
| [0.010s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:51024/hubT?id=pGXNG5FYJ8-vYtT1Cdzqig  39
| [0.010s] SERVER Microsoft.AspNetCore.SignalR.HubConnectionContext Information: pGXNG5FYJ8-vYtT1Cdzqig - Completed connection handshake. Using HubProtocol 'messagepack'.
| [0.010s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6989ms 200 text/plain
| [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: pGXNG5FYJ8-vYtT1Cdzqig - HubConnection started.
| [0.011s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.9261ms 200 application/octet-stream
| [0.011s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:51024/hubT?id=pGXNG5FYJ8-vYtT1Cdzqig  
| [0.011s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:51024/hubT?id=pGXNG5FYJ8-vYtT1Cdzqig  3
| [0.012s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.8262ms 200 application/octet-stream
| [0.012s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.8756ms 200 text/plain
| [0.012s] SERVER Microsoft.AspNetCore.Hosting.Internal.WebHost Information
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by BrennanConroy** [comment]
I think this will be fixed by https://github.com/aspnet/SignalR/pull/2731

**Comment by ryanbrandenburg** [comment]
CanSendAndReceiveMessage [failed with about the same error](http://aspnetci/viewLog.html?buildId=524441&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.
