### ISSUE TITLE
(Server shutdown) Writing is not allowed after writer was completed

### ISSUE THREAD

**Issue by benaadams** [aspnet/SignalR#2735]
When shutting down server always receive the following if a client is connected
```
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.Internal.Utf8BufferTextWriter.EnsureBuffer()
   at Microsoft.AspNetCore.Internal.Utf8BufferTextWriter.Write(Char value)
   at Newtonsoft.Json.JsonTextWriter.WriteStartObject()
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
```

In `OnDisconnectedAsync` I do remove the connection form Groups; so that might cause the issue?

However, it doesn't occur while the server is running and clients disconnect.

* NuGet Packages: `"Microsoft.AspNetCore.App" Version="2.1.1"`
* Versions of Client-Side NuGet/NPM Packages:
* JavaScript client: `"@aspnet/signalr": "^1.0.2"`
* Server Kestrel 
* Server Windows 10
* Client Windows 10
* Chrome Version 68.0.3440.84 (Official Build) (64-bit)

```
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HLFQ9QH9B610" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3234.9771ms 200 application/json; charset=utf-8
Application is shutting down...
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[5]
      Hosting shutdown
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[7]
      Waiting for the client to close the socket.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[6]
      Failed writing message.
System.InvalidOperationException: Writing is not allowed after writer was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoWritingAllowed()
   at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.Internal.Utf8BufferTextWriter.EnsureBuffer()
   at Microsoft.AspNetCore.Internal.Utf8BufferTextWriter.Write(Char value)
   at Newtonsoft.Json.JsonTextWriter.WriteStartObject()
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)
dbug : Microsoft.AspNetCore.SignalR.HubConnectionHandler[6]
      OnConnectedAsync ending.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[2]
      Socket closed.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[2]
      Removing connection TCWQ2FeuiEiErm-VaIHgmA from the list of connections.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 8007.4916ms 101
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLFQ9QH9B613" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLFQ9QH9B613" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLFQ9QH9B613" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLFQ9QH9B60U" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLFQ9QH9B60V" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLFQ9QH9B611" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLFQ9QH9B610" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLFQ9QH9B60V" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLFQ9QH9B612" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLFQ9QH9B614" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLFQ9QH9B611" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLFQ9QH9B60U" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLFQ9QH9B612" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLFQ9QH9B610" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLFQ9QH9B614" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLFQ9QH9B611" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLFQ9QH9B60U" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLFQ9QH9B614" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLFQ9QH9B60V" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLFQ9QH9B610" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLFQ9QH9B612" stopped.
```

**Comment by davidfowl** [comment]
This is likely because of this https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionManager.cs#L187.

We should just do a graceful shutdown here and call it a day.
