### ISSUE TITLE
 WPF Client is not connecting with AspnetCore and SignalR Core

### ISSUE THREAD

**Issue by aravindkoniki** [aspnet/SignalR#2868]
I'm using WPF with asp.net core as sever, for client & server communications we have implemented signalR framework.

It is connecting seamlessly when I'm running project through Visual studio / development environment. When I take setup for WPF application it throughs below exception shown in screen shot.

![image](https://user-images.githubusercontent.com/38941211/44625392-2a138900-a919-11e8-856a-3ae94b59c468.png)

I have corrected all the package versions, related to asp.net core, signalR core for client and server, all are under same version specified by Microsoft documentation.

[SignalR Versions](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1)

Versions I'm using

![image](https://user-images.githubusercontent.com/38941211/44625401-50d1bf80-a919-11e8-8a47-1943b166ad1a.png)

![image](https://user-images.githubusercontent.com/38941211/44625403-57f8cd80-a919-11e8-9128-4dcd8950ca42.png)

Complete Stack trace

**Unable to connect to the server with any of the available transports.	   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<SelectAndStartTransport>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsyncCore>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProMove.Client.Infrastructure.SignalR.Connector.<Connect>d__7.MoveNext()**

Can any one help me on this.

**Comment by anurse** [comment]
Can you collect client-side logs as described in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide)?

**Comment by aravindkoniki** [comment]
I'm using my own library to log the exceptions, that is the stack trace which i have posted, i cant integrate my logger in Microsoft.Extensions.Logging, please suggest me any other approach

**Comment by davidfowl** [comment]
Why can’t you integrate the logger?

**Comment by aravindkoniki** [comment]
I thought that my SignalR core client (WPF) is not connecting after installing into the machine, and logger will give only debug logs so i thought there is no point of enabling.

Anyways, i have enabled log, Deployed my .Net Core application, started my WPF client project from VS Studio to take log

------------------------------------------------------
Client log
-----------
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in Microsoft.AspNetCore.Http.Connections.Client.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in Microsoft.AspNetCore.SignalR.Client.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
'XXXXXX.Client.exe' (CLR v4.0.30319: XXXXXX.Client.exe): Loaded 'Microsoft.GeneratedCode'. 
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
----------------------------------------------------------------------------------
Server
------------
![image](https://user-images.githubusercontent.com/38941211/44773419-9c86a200-ab81-11e8-91fc-17df454b95a4.png)

**Comment by anurse** [comment]
That's just the standard VS debugger log. Can you get more detail (messages and stack traces) on the `HttpRequestException` exceptions you're seeing?

> logger will give only debug logs so i thought there is no point of enablin

This is precisely why we need the logs, because the debug logs give the full picture beyond the primary exception.

Since you're using a WPF application, can you enable [Debug Output Window](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide#debug-output-window-logging) logging in the client? We really need those logs to be able to understand what's going on.

Also, can you provide the environment details requested in the new issue template?

* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
* The Operating System on the Server (Windows/Linux/macOS):
* The Operating System on the Client (Windows/Linux/macOS):

**Comment by aravindkoniki** [comment]
I have found out the problem by following the link given by you, observed i have missed out some dependencies while preparing WPF deployment package with WIX. 

Thanks for your help and suggestions
