### ISSUE TITLE
Test failure: ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/SignalR#2886]
This test [fails](http://aspnetci/viewLog.html?buildId=541782&buildTypeId=Releases_21Public_Win2012) occasionally with the following error:
```
System.Exception : 1 error(s) logged.
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets - 0 - Unexpected exception in SocketConnection.StartAsync.
===================
System.AggregateException: An error occurred while writing to logger(s). ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.<ServerFixtureOnServerLogged>b__7_0(String loggerName) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 53
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.ServerFixtureOnServerLogged(LogRecord logRecord) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 53
   at Microsoft.AspNetCore.SignalR.Tests.LogSinkProvider.Log[TState](String categoryName, LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs:line 201
   at Microsoft.AspNetCore.SignalR.Tests.LogSinkProvider.LogSinkLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs:line 226
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>b__0(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketsTrace.ConnectionWriteFin(String connectionId)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.Shutdown()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<DoSend>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<StartAsync>d__21.MoveNext()
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.<ServerFixtureOnServerLogged>b__7_0(String loggerName) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 53
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.ServerFixtureOnServerLogged(LogRecord logRecord) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 53
   at Microsoft.AspNetCore.SignalR.Tests.LogSinkProvider.Log[TState](String categoryName, LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs:line 201
   at Microsoft.AspNetCore.SignalR.Tests.LogSinkProvider.LogSinkLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerFixture.cs:line 226
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
===================
   at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifyNoErrorsScope.cs:line 63
   at Microsoft.AspNetCore.SignalR.Tests.ServerLogScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/ServerLogScope.cs:line 66
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.<ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible>d__22.MoveNext() in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 766
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [2018-08-29T04:31:18] TestLifetime Information: Starting test ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible_json_LongPolling_dynamic
| [2018-08-29T04:31:18] ServerLogScope Information: Server log scope started.
| [2018-08-29T04:31:18] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:50231/dynamic/negotiate  0
| [2018-08-29T04:31:18] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Error: Unexpected exception in SocketConnection.StartAsync.
| System.AggregateException: An error occurred while writing to logger(s). ---> System.ObjectDisposedException: Cannot access a disposed object.
| Object na
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by anurse** [comment]
@BrennanConroy looks like maybe a glitch because Kestrel was running something off the main thread that logged after we disposed the logger factory at the end of the test. Maybe we just shouldn't dispose it? Or can we wait for shutdown?

**Comment by BrennanConroy** [comment]
This looks like https://github.com/aspnet/SignalR/pull/2742 which we fixed in 2.2, we should consider porting the fix to 2.1

**Comment by muratg** [comment]
@BrennanConroy We can port it to 2.1.5 (as long as it's test only code). I'll just need to send a notification to the shiproom. How flaky is this? Do we want to port it back?

**Comment by BrennanConroy** [comment]
Change is super small and in test only code. It makes potentially any functional test flaky.

**Comment by muratg** [comment]
OK feel free to create a PR with it, add "servicing-consider" label, and let me know. I'll inform the shiproom.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/aspnet/SignalR/commit/753c3da852028df97087c7e30ec40dc87892530b
