### ISSUE TITLE
Test failure: HubConnectionCanSendAndReceiveGroupMessages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/SignalR#3139]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=578572&buildTypeId=Releases_22xPublic_UbuntuUniverse) with the following error:

```
Microsoft.AspNetCore.SignalR.HubException : An unexpected error occurred invoking 'EchoGroup' on the server. RedisConnectionException: No connection is available to service this operation: PUBLISH Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.EchoHub:group:TestGroup_WebSockets_json_8926ab6f-70cf-49e9-9540-d33337219573; IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=5,Free=32762,Min=8,Max=32767), Local-CPU: n/a
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 462
   at System.Threading.Tasks.ForceAsyncAwaiter`1.GetResult() in /_/src/Common/ForceAsyncAwaiter.cs:line 64
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs:line 264
   at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 40
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.HubConnectionCanSendAndReceiveGroupMessages(HttpTransportType transportType, String protocolName) in /_/test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/RedisEndToEnd.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.003s] TestLifetime Information: Starting test HubConnectionCanSendAndReceiveGroupMessages-WebSockets-json at 2018-10-16T02:51:59
| [0.000s] TestLifetime Information: Starting test HubConnectionCanSendAndReceiveGroupMessages_WebSockets_json at 2018-10-16T02:51:59
| [0.369s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: SAWpiTG4uDvMXWfbyg2rRQ - Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:37537/echo?id=SAWpiTG4uDvMXWfbyg2rRQ'.
| [0.470s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: SAWpiTG4uDvMXWfbyg2rRQ - HttpConnection Started.
| [0.478s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: SAWpiTG4uDvMXWfbyg2rRQ - Using HubProtocol 'json v1'.
| [0.572s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: SAWpiTG4uDvMXWfbyg2rRQ - HubConnection started.
| [0.585s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: mrSZOGkNy-aHSAQDkthD2Q - Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:46667/echo?id=mrSZOGkNy-aHSAQDkthD2Q'.
| [0.589s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: mrSZOGkNy-aHSAQDkthD2Q - HttpConnection Started.
| [0.589s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: mrSZOGkNy-aHSAQDkthD2Q - Using HubProtocol 'json v1'.
| [0.591s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: mrSZOGkNy-aHSAQDkthD2Q - HubConnection started.
| [0.801s] TestLifetime Information: Finished test HubConnectionCanSendAndReceiveGroupMessages_WebSockets_json in 0.7998611s
| [0.832s] TestLifetime Information: Finished test HubConnectionCanSendAndReceiveGroupMessages-WebSockets-json in 0.8303514s
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @muratg

**Comment by anurse** [comment]
Another Redis functional test problem... @BrennanConroy :(

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 10 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=32141) on release/2.2 at 6:03:17 PM:
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages
- HubConnectionCanSendAndReceiveGroupMessages

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=580331&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2 at 7:21:49 PM:
- HubConnectionCanSendAndReceiveGroupMessages

**Comment by BrennanConroy** [comment]
Closing as we made some changes to the redis tests, RAAS will open a new issue if there is still flakiness.
