### ISSUE TITLE
Azure SignalR service and dotnet core non browser client

### ISSUE THREAD

**Issue by Havunen** [aspnet/SignalR#3192]
Hi,
I'm having an issue connecting non browser client to azure signalR service using dotnet core and nodejs client.

Client Setup
`NodeJS 10 + 1.1.0-preview3 ( with HTTPS work around )`

Server ( Azure )
```
- Microsoft.AspNetCore.All ( 2.1.5 )
- Microsoft.Azure.SignalR ( 1.0.2 )
```

## Local machine setup: this works
```C#
  services.AddCors(options => options.AddPolicy("CorsPolicy", builder =>
            {
          builder
             .AllowAnyMethod()
             .AllowAnyHeader()
             .AllowCredentials()
           .WithOrigins("http://localhost:3000");
}));
services.AddSignalR();
```

Configure...
```c#


            app.UseCors("CorsPolicy");
            app.UseSignalR((routes) =>
            {
                routes.MapHub<MonkeyHub>("/monkeyHub");
                routes.MapHub<GorillaHub>("/gorillaHub");
                routes.MapHub<MasterHub>("/masterHub");
            });
```

## Server ( Azure setup ) this fails

```c#
            services.AddCors(options => options.AddPolicy("CorsPolicy", builder =>
            {
                builder
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials()
                    .WithOrigins("http://localhost:3000");
            }));
services.AddSignalR().AddAzureSignalR(Configuration.GetConnectionString("SignalR"));
```

Configure...
```C#

            app.UseAzureSignalR((routes) =>
            {
                routes.MapHub<MonkeyHub>("/monkeyHub");
                routes.MapHub<GorillaHub>("/gorillaHub");
                routes.MapHub<MasterHub>("/masterHub");
            });
```

Here is log:
```
__COMPUTER_PATH__>node gorilla.js
Recreating connection
Connection starting...
ErrorEvent {
  target:
   WebSocket {
     _events:
      { open: [Function],
        error: [Function],
        message: [Function],
        close: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 2,
     protocol: '',
     _binaryType: 'nodebuffer',
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _closeCode: 1006,
     _extensions: {},
     _isServer: false,
     _receiver: null,
     _sender: null,
     _socket: null,
     url:
      'wss://__BASEURL__/client/?hub=__MYHUB__&asrs.op=%2F__MYHUB__&id=___ID___&access_token=___ACCESS_TOKEN___',
     _req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /client/?hub=__MYHUB__&asrs.op=%2F__MYHUB__&id=___ID___&access_token=___ACCESS_TOKEN___HTTP/1.1\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: __WEBSOCKET__KEY___==\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\nHost: ___MYURL___:443\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: undefined,
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         'URL'
        _ended: false,
        res: [IncomingMessage],
        aborted: 1540393424258,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: [HTTPParser],
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] } },
  type: 'error',
  message: 'Unexpected server response: 404',
  error:
   Error: Unexpected server response: 404
       at ClientRequest.req.on (__COMPUTER_PATH__\node_modules\ws\lib\websocket.js:535:5)
       at ClientRequest.emit (events.js:182:13)
       at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
       at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
       at TLSSocket.socketOnData (_http_client.js:441:20)
       at TLSSocket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at TLSSocket.Readable.push (_stream_readable.js:219:10)
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17) }
[2018-10-24T15:03:44.265Z] Error: Failed to start the transport 'WebSockets': null
[2018-10-24T15:03:44.529Z] Error: Failed to start the transport 'ServerSentEvents': Error: Error occurred
[2018-10-24T15:03:44.794Z] Error: Failed to start the transport 'LongPolling': Error: Not Found
[2018-10-24T15:03:44.796Z] Error: Failed to start the connection: Error: Unable to initialize any of the available transports.
Error: Unable to initialize any of the available transports.
    at HttpConnection.<anonymous> (__COMPUTER_PATH__\node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:335:35)
    at step (__COMPUTER_PATH__\node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:34:23)
    at Object.throw (__COMPUTER_PATH__\node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:15:53)
    at rejected (__COMPUTER_PATH__\node_modules\@aspnet\signalr\dist\cjs\HttpConnection.js:7:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Connecting browser client seems to work fine. I noticed SignalR browser client has Request cookie called `SIGNALRROUTE` with value of some random string. Is this correctly handled in non-browser client ? What else could be the difference here? Any pointers appreciated.

**Comment by Havunen** [comment]
Alright, my assumption was right. If I add the cookies into request headers routes are handled correctly. My solution was really hacky because I'm not familiar with SignalR codebase. Anyway cookies needs to be set here into the header:

`Cookie: value`

https://github.com/aspnet/SignalR/blob/63900a462bda5948da83f596167f777a06f22ece/clients/ts/signalr/src/NodeHttpClient.ts#L25-L29

**Comment by muratg** [comment]
@BrennanConroy Could you investigate using `request` here?  

(If it works, it may possibly help https://github.com/aspnet/SignalR/issues/3179 as well.
