### ISSUE TITLE
SignalR how to support the HTTPS protocol?

### ISSUE THREAD

**Issue by Mangoxx90** [aspnet/SignalR#3223]
SignalR how to support the HTTPS protocol in java?

**Comment by BrennanConroy** [comment]
By passing an Https url to the `HubConnectionBuilder`
```java
HubConnection connection = HubConnectionBuilder.create("https://example.com").build();
```

If that isn't working please give us more info about what isn't working.

**Comment by akira32** [comment]
@BrennanConroy Can I ask you a question?
The SignalRSamles run and the console message as below:

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:54035/'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Development
Content root path: C:\tmp\SignalRJava\SignalR-release-2.2\samples\SignalRSamples
Now listening on: http://localhost:5000
Now listening on: http://0.0.0.0:9001
Application started. Press Ctrl+C to shut down.
```

My Java project should use the URL of "http://localhost:5000" to connect SignalR Server？
HubConnection connection = HubConnectionBuilder.create("http://localhost:5000").build();

I try to use Chat.java in my JavaFX project and meet the exceptions as below:
Do you know how to solve this problem?

```
Enter the URL of the SignalR Chat you want to join
http://localhost:5000
Enter your name:A
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error reading NegotiateResponse
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91)
	at io.reactivex.Completable.blockingAwait(Completable.java:1187)
	at sample.Chat.main(Chat.java:33)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error reading NegotiateResponse
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.reactivex.internal.functions.Functions$FutureAction.run(Functions.java:161)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
	at io.reactivex.Completable.subscribe(Completable.java:2185)
	at io.reactivex.Completable.blockingAwait(Completable.java:1186)
	... 1 more
Caused by: java.lang.RuntimeException: Error reading NegotiateResponse
	at com.microsoft.signalr.NegotiateResponse.<init>(NegotiateResponse.java:76)
	at com.microsoft.signalr.HubConnection.lambda$handleNegotiate$2(HubConnection.java:202)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.microsoft.signalr.DefaultHttpClient$2.onResponse(DefaultHttpClient.java:115)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:379)
	at com.microsoft.signalr.NegotiateResponse.<init>(NegotiateResponse.java:23)
```

**Comment by akira32** [comment]
If we use "https://example.com", the SignalSamples (SignalR Server) should modify something or not?

**Comment by Mangoxx90** [comment]
> By passing an Https url to the `HubConnectionBuilder`
> 
> ```java
> HubConnection connection = HubConnectionBuilder.create("https://example.com").build();
> ```
> 
> If that isn't working please give us more info about what isn't working.

then HubConnection method how to register online and offline callback?

**Comment by BrennanConroy** [comment]
>If we use "https://example.com", the SignalSamples (SignalR Server) should modify something or not?

What do you mean? What should it modify.

**Comment by akira32** [comment]
@BrennanConroy , Should we modify the listen of the option if we use "https://example.com"?
 ```
       public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();

            var host = new WebHostBuilder()
                .UseConfiguration(config)
                .UseSetting(WebHostDefaults.PreventHostingStartupKey, "true")
                .ConfigureLogging(factory =>
                {
                    factory.AddConsole();
                })
                .UseKestrel(options =>
                {
                    // Default port
                    options.ListenLocalhost(5000);

					//options.Listen(IPAddress.IPv6Any, 5000);

					// Hub bound to TCP end point
					options.Listen(IPAddress.Any, 9001, builder =>
                    {
                        builder.UseHub<Chat>();
                    });
                })
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();

        }
```

**Comment by BrennanConroy** [comment]
>then HubConnection method how to register online and offline callback? How to post parameters?
and How to specify hubname?

There is no "online" callback, if `start` returns successfully then you are connected. You can register a callback to `onClosed` for when the connection has been closed. Take a look at the API docs https://docs.microsoft.com/java/api/com.microsoft.signalr?view=aspnet-signalr-java for all the methods.

If by 'post parameters' you mean send arguments, then use `send` or `invoke`.

**Comment by bradygaster** [comment]
As the team has pointed out, passing `https` is all you need to do to enable the SignalR client (in any language) to support the underlying https protocol. If your server side is also enabled with https, everything should work just fine. If your server is running at `localhost:5001` on an https endpoint, simply providing `https://localhost:5001` should result with a successful handshake. If it doesn't please provide a detailed log dump per the instructions in the issue guidance and we'll try to assess. 

However, it needs to be re-asserted that SignalR clients support https out of the box, so it should work as long as you have an https endpoint listening. If you want to use the open client once it is connected, as Brennan points out, you'd use the `send` or `invoke` methods to call methods on your server and to pass those methods arguments. 

If you'd like to see another example of this working in an Android client sample we have a new one incoming to the SignalR samples repository [here](https://github.com/aspnet/SignalR-samples/tree/bradygaster/githubmonitor/PullRequestR).

**Comment by Mangoxx90** [comment]
> As the team has pointed out, passing `https` is all you need to do to enable the SignalR client (in any language) to support the underlying https protocol. If your server side is also enabled with https, everything should work just fine. If your server is running at `localhost:5001` on an https endpoint, simply providing `https://localhost:5001` should result with a successful handshake. If it doesn't please provide a detailed log dump per the instructions in the issue guidance and we'll try to assess.
> 
> However, it needs to be re-asserted that SignalR clients support https out of the box, so it should work as long as you have an https endpoint listening. If you want to use the open client once it is connected, as Brennan points out, you'd use the `send` or `invoke` methods to call methods on your server and to pass those methods arguments.
> 
> If you'd like to see another example of this working in an Android client sample we have a new one incoming to the SignalR samples repository [here](https://github.com/aspnet/SignalR-samples/tree/bradygaster/githubmonitor/PullRequestR).


Use this demo will show error report:


11-06 17:04:45.808 12844-12872/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.pullrequestr, PID: 12844
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91)
        at io.reactivex.Completable.blockingAwait(Completable.java:1187)
        at com.example.pullrequestr.MainActivity$HubConnectionTask.doInBackground(MainActivity.java:64)
        at com.example.pullrequestr.MainActivity$HubConnectionTask.doInBackground(MainActivity.java:56)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.util.concurrent.ExecutionException: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:359)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1921)
        at io.reactivex.internal.functions.Functions$FutureAction.run(Functions.java:161)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
        at io.reactivex.Completable.subscribe(Completable.java:2185)
        at io.reactivex.Completable.blockingAwait(Completable.java:1186)
        at com.example.pullrequestr.MainActivity$HubConnectionTask.doInBackground(MainActivity.java:64) 
        at com.example.pullrequestr.MainActivity$HubConnectionTask.doInBackground(MainActivity.java:56) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Linux.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:59)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
        at java.net.InetAddress.getAllByName(InetAddress.java:787)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        	... 3 more

**Comment by BrennanConroy** [comment]
From your error:
>android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)

It looks like you've probably misconfigured the url your app is using. It also looks like you're using the PullRequestR sample Brady pointed at. 
The line you need to fix is https://github.com/aspnet/SignalR-samples/blob/515f5d0cdca88da6970929de5a1af4335548f452/PullRequestR/android/app/src/main/java/com/example/pullrequestr/MainActivity.java#L35 

And its worth noting that this sample is for use with Azure Functions. If you look at the README that goes along with the sample https://github.com/aspnet/SignalR-samples/blob/bradygaster/githubmonitor/PullRequestR/readme.md it will help describe how to use it.
