### ISSUE TITLE
Angular 7 can't build with package @aspnet/signalr@next (1.1.0 preview3-35497)

### ISSUE THREAD

**Issue by x3r10n** [aspnet/SignalR#3254]
the cli can't resolve the http and https module.

```
ERROR in ./node_modules/@aspnet/signalr/dist/esm/NodeHttpClient.js
Module not found: Error: Can't resolve 'http' in '/Users/patrick/Workspaces/temp/NGSignalr/signalR/node_modules/@aspnet/signalr/dist/esm'
ERROR in ./node_modules/@aspnet/signalr/node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'http' in '/Users/patrick/Workspaces/temp/NGSignalr/signalR/node_modules/@aspnet/signalr/node_modules/eventsource/lib'
ERROR in ./node_modules/@aspnet/signalr/node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'https' in '/Users/patrick/Workspaces/temp/NGSignalr/signalR/node_modules/@aspnet/signalr/node_modules/eventsource/lib'

```

**Comment by anurse** [comment]
@BrennanConroy Could be a WebPack thing. Angular shouldn't be using the `NodeHttpClient` at all...

**Comment by BrennanConroy** [comment]
When importing the SignalR library use:
```ts
import * as signalR from '@aspnet/signalr/dist/browser/signalr.js';
```

@anurse We should talk and see if we can make it so Angular loads that file by default.

**Comment by anurse** [comment]
@BrennanConroy it shouldn't have to, but we may need to change our config to make it work. Angular is using WebPack, which uses the Module version.

**Comment by rcanpahali** [comment]
Any solution for this issue? I'm also facing with this problem...

`NodeInvocationException: Prerendering failed because of error: Error: Cannot find module './NodeHttpClient'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at eval (webpack-internal:///./node_modules/@aspnet/signalr/dist/esm/DefaultHttpClient.js:26:28)
at Module../node_modules/@aspnet/signalr/dist/esm/DefaultHttpClient.js (C:\Users\can.pahali\source\WestCore.MvcSpa-Dev\ClientApp\dist\main-server.js:1923:1)
at __webpack_require__ (C:\Users\can.pahali\source\WestCore.MvcSpa-Dev\ClientApp\dist\main-server.js:26:30)
at eval (webpack-internal:///./node_modules/@aspnet/signalr/dist/esm/index.js:15:76)
at Module../node_modules/@aspnet/signalr/dist/esm/index.js (C:\Users\can.pahali\source\WestCore.MvcSpa-Dev\ClientApp\dist\main-server.js:2139:1)
at __webpack_require__ (C:\Users\can.pahali\source\WestCore.MvcSpa-Dev\ClientApp\dist\main-server.js:26:30)
Current directory is: C:\Users\can.pahali\source\WestCore.MvcSpa-Dev`

**Comment by BrennanConroy** [comment]
Have you tried using the 1.1.0 package?

**Comment by tomagb** [comment]
Yes, I've tried with 1.1.0 package and the issue didn't go away.

**Comment by BrennanConroy** [comment]
Could you provide a sample app? I can't reproduce the issue.

**Comment by tomagb** [comment]
Does this [SO help](https://stackoverflow.com/questions/53733316/signalr-on-webpack-and-typescript-cannot-find-module-nodehttpclient)?
I might need some time to strip the (NDA) app in order to post it.

**Comment by BrennanConroy** [comment]
Nope, that's the same app I have...
