### ISSUE TITLE
Test failure: HubConnectionCanSendAndReceiveGroupMessages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/SignalR#3256]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588061&buildTypeId=Releases_22xPublic_UbuntuUniverse) with the following error:

```
System.AggregateException : One or more errors occurred. (No process is associated with this object.) (The following constructor parameters did not have matching fixture data: RedisServerFixture`1 serverFixture)
---- System.InvalidOperationException : No process is associated with this object.
---- The following constructor parameters did not have matching fixture data: RedisServerFixture`1 serverFixture
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetWaitState()
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunProcessAndWait(String fileName, String arguments, String prefix, ILogger logger, TimeSpan timeout, String& output) in /_/test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/Docker.cs:line 139
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunProcessAndThrowIfFailed(String fileName, String arguments, String prefix, ILogger logger, TimeSpan timeout) in /_/test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/Docker.cs:line 120
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.Start(ILogger logger) in /_/test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/Docker.cs:line 89
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisServerFixture`1..ctor() in /_/test/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests/RedisServerFixture.cs:line 36
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC muratg

**Comment by muratg** [comment]
@BrennanConroy could you take a look?

**Comment by BrennanConroy** [comment]
This is because `docker pull` was downloading the redis image and timed out. We can either increase the timeout or find some other way to try and avoid this.

**Comment by muratg** [comment]
Sure. I'd consider retrying image pull as well.
