### ISSUE TITLE
in the android client, the string has a special character and can't deserialize

### ISSUE THREAD

**Issue by liugt34** [aspnet/SignalR#3262]
the server model class,
```
public class ChatMessage
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public Group Group { get; set; }
        public OnlineUser Sender { get; set; }
        public DateTime SendTime { get; set; } = DateTime.Now;
        public string Content { get; set; }
        public MessageType Type { get; set; }

        // either deleted or not
        public bool Enabled { get; set; } = true;
    }

```
and i send this object with the method 
`await this.Clients.All.SendAsync("Receive", chatMessage)`

in the web client ,it works well,can receive it as a json, but in the andoird client ,the received message 
has a special character, and when it convert it to a json, it has a wrong.

![image](https://user-images.githubusercontent.com/8056013/48039201-b7434b80-e1ae-11e8-9a3b-493c23acfc86.png)

any know what happend?

the received message is the following...
`{"type":1,"target":"Receive","arguments":[{"id":"27acfe47-da07-4470-8a7d-a2b6d919b5ab","group":{"id":"0d071038-d70b-4512-be78-586bfb3ecc00","name":"测试聊天项目1","createTime":"2018-11-05T15:17:26","projectId":"003438e6-2b29-4bbd-aa06-3057429f24da","userId":"5cbf3cff-4be0-4f81-b21a-34ccbb93e830","enabled":true},"sender":{"id":"5cbf3cff-4be0-4f81-b21a-34ccbb93e830","userName":"Tom","connectionId":"L4GC7H5iJBnOEVAlgPKt0w","companyName":"有限公司","email":"sss@qq.com","phone":"123321123321","avatar":"http://xxx/assets/images/default/avator.png","online":false,"enabled":true},"sendTime":"2018-11-05T17:49:04.2857586+08:00","content":"Hello,World!","type":0,"enabled":true}]}`

2018-11-06 10:56:57.939 23917-23947/com.archgl.spiderbim.signalrdemo E/HubConnection: Failed to bind arguments received in invocation 'null' of 'Receive'.
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: **### _**Expected a string but was BEGIN_OBJECT at line 1 column 44 path $.arguments[0]**_**
        at com.google.gson.Gson.fromJson(Gson.java:939)
        at com.microsoft.signalr.JsonHubProtocol.bindArguments(JsonHubProtocol.java:202)
        at com.microsoft.signalr.JsonHubProtocol.parseMessages(JsonHubProtocol.java:91)
        at com.microsoft.signalr.HubConnection.lambda$new$0(HubConnection.java:168)
        at com.microsoft.signalr.-$$Lambda$HubConnection$G63yw6AUTkfrLLvuFIXyM3tmsU4.invoke(Unknown Source:2)
        at com.microsoft.signalr.WebSocketTransport.onReceive(WebSocketTransport.java:76)
        at com.microsoft.signalr.WebSocketTransport.lambda$start$0(WebSocketTransport.java:53)
        at com.microsoft.signalr.-$$Lambda$WebSocketTransport$fNWE7JNd0a-15XX5_c3rxHw-FEs.invoke(Unknown Source:2)
        at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onMessage(OkHttpWebSocketWrapper.java:84)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 44 path $.arguments[0]
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.microsoft.signalr.JsonHubProtocol.bindArguments(JsonHubProtocol.java:202) 
        at com.microsoft.signalr.JsonHubProtocol.parseMessages(JsonHubProtocol.java:91) 
        at com.microsoft.signalr.HubConnection.lambda$new$0(HubConnection.java:168) 
        at com.microsoft.signalr.-$$Lambda$HubConnection$G63yw6AUTkfrLLvuFIXyM3tmsU4.invoke(Unknown Source:2) 
        at com.microsoft.signalr.WebSocketTransport.onReceive(WebSocketTransport.java:76) 
        at com.microsoft.signalr.WebSocketTransport.lambda$start$0(WebSocketTransport.java:53) 
        at com.microsoft.signalr.-$$Lambda$WebSocketTransport$fNWE7JNd0a-15XX5_c3rxHw-FEs.invoke(Unknown Source:2) 
        at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onMessage(OkHttpWebSocketWrapper.java:84) 
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322) 
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) 
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) 
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) 
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by BrennanConroy** [comment]
>when i convert it to a json

What do you mean? The client will parse the json for you into the type you pass into your "Receive" function on the client. You should never be getting the json and parsing it yourself.

**Comment by BrennanConroy** [comment]
Could you show your `hubConnection.on("Receive", ...)` code?

**Comment by liugt34** [comment]
@BrennanConroy   it has't run to the hubConnection.on("Receive", ...) code,,
when it run into the  JsonHubProtocol.java class 
![image](https://user-images.githubusercontent.com/8056013/48040675-e65cbb80-e1b4-11e8-85ca-4d0be5a4fb17.png)

it met a wrong  `Expected a string but was BEGIN_OBJECT at line 1 column 44 path $.arguments[0]`

**Comment by BrennanConroy** [comment]
I'm guessing your `.on(...)` code isn't registering a complex object that resembles the C# type `ChatMessage` and so when the json is being parsed it can't parse the complex object into the wrong type provided to the `.on(...)` call.

**Comment by liugt34** [comment]
@BrennanConroy 
thank u very much ,i find it !  it just a Date type not match.
