### ISSUE TITLE
[Java] Crash when close a connections

### ISSUE THREAD

**Issue by JMaroz** [aspnet/SignalR#3319]
After invoke close on hubconnections.stop the app crash when using the 1.0.0-preview3-35501.

`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference at com.microsoft.signalr.WebSocketTransport.lambda$start$1(WebSocketTransport.java:56)
        at com.microsoft.signalr.-$$Lambda$WebSocketTransport$AQhmDI2aQR6xOI_rRCG9Mm31O2o.accept(Unknown Source:6)
        at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:103)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:215)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

no problem with the 0.1.0-preview2-35174 version

**Comment by BrennanConroy** [comment]
This should be fixed in the nightly/final build via https://github.com/aspnet/SignalR/pull/3236
