### ISSUE TITLE
Cannot return public class with only internal constructors using MessagePack

### ISSUE THREAD

**Issue by emilmuller** [aspnet/SignalR#3342]
If a SignalR hub has a method which returns a type which is public, but has only internal constructors, it fails silently, yielding no error messages on the server side nor on the client side. No exceptions are thrown. Nothing in the debug output window.

Consider the following classes:

```
    public class ApiLogin
    {
        internal ApiLogin(...)
        {
            ...
        }

        public byte[] PrivateDetailsCiphertext { get; set; }
    }

    public class ApiLoginWithToken : ApiLogin
    {
        internal ApiLoginWithToken(...) : base(...)
        {
            ...
        }

        public byte[] Token { get; set; }
    }
```

And the following hub method:

`public ApiLoginWithToken LogIn(string username, string password) => new ApiLoginWithToken(...);`

Fails silently.

To get it working, I had to add a couple of public constructors.
Assuming this has to do with reflection. The MessagePack component shouldn't have to know about constructors to serialize an existing instance. In any case, an error message should be displayed somewhere :)

**Comment by BrennanConroy** [comment]
Sadly this looks like a restriction of the library we're using. See https://github.com/neuecc/MessagePack-CSharp/issues/40

Workaround is to use public constructors, or use Json where private/internal constructors are supported.

**Comment by BrennanConroy** [comment]
If you have logging enabled on the server then you'll get an error log looking like:
```
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'Send'.
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> System.IO.InvalidDataException: Deserializing object of the `t` type for 'argument' failed. ---> MessagePack.Internal.MessagePackDynamicObjectResolverException: can't find public constructor. type:SignalRSamples.Hubs.Chat+t
   at MessagePack.FormatterResolverExtensions.GetFormatterWithVerify[T](IFormatterResolver resolver)
   at MessagePack.MessagePackSerializer.Deserialize[T](ArraySegment`1 bytes, IFormatterResolver resolver)
   at lambda_method(Closure , ArraySegment`1 , IFormatterResolver )
   at MessagePack.MessagePackSerializer.NonGeneric.Deserialize(Type type, ArraySegment`1 bytes, IFormatterResolver resolver)
```

And the client will get an error thrown from the `invoke` call: `Error: Failed to invoke 'methodName' due to an error on the server.`
