### ISSUE TITLE
Investigate ungraceful WebSocket connection close on exit

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#347]
Currently on close with a WebSocket connection open you can get the following error:
```
fail: Microsoft.AspNetCore.Sockets.ConnectionManager[0]
      Failed disposing connection 2511b1b2-1dbb-44ee-805c-e6d629fca076
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FrameResponseStream'.
   at System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at System.IO.Pipelines.Pipe.System.IO.Pipelines.IWritableBufferAwaiter.GetResult()
   at Microsoft.Extensions.WebSockets.Internal.WebSocketConnection.<SendCoreLockAcquiredAsync>d__38`1.MoveNext() in C:\Github\SignalR\src\Microsoft.Extensions.WebSockets.Internal\WebSocketConnection.cs:line 695
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.WebSockets.Internal.WebSocketConnection.<CloseAsync>d__24.MoveNext() in C:\Github\SignalR\src\Microsoft.Extensions.WebSockets.Internal\WebSocketConnection.cs:line 214
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by davidfowl** [comment]
We don't have to, we already have `IHostedService` which is the equivalent.
