### ISSUE TITLE
Timed out poll connections kill the connection

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#4]
If a poll connection times out the server throws: 

```
System.InvalidOperationException occurred
  HResult=-2146233079
  Message=Concurrent reads are not supported.
  Source=System.Private.CoreLib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Channels.Channel.Channels.IReadableBufferAwaiter.GetResult()
       at Microsoft.AspNetCore.Sockets.LongPolling.<ProcessRequestAsync>d__3.MoveNext() in C:\source\NetworkingProtoype\src\Microsoft.AspNetCore.Sockets\LongPolling.cs:line 21
  InnerException: 
```

and kills the connection. The client restarts the poll only to get: 

GET http://localhost:5000/hubs/poll?id=87085e15-6bb5-492e-850b-f7965c7e9bbc&87085e15-6bb5-492e-850b-f7965c7e9bbc 500 (Internal Server Error)

**Comment by davidfowl** [comment]
Fixed
