### ISSUE TITLE
 Unexpected end of stream at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.

### ISSUE THREAD

**Issue by rrdlpl** [aspnet/SignalR#434]
I keep getting this log on my server and from the logs I can't figure out what I'm doing wrong nor how to reproduce it. I'd like if someone can help me to track this down.

 `OnError(b6ab1203-3e15-42fc-8f28-bcb27afde9bc, System.IO.IOException: Unexpected end of stream at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<EnsureDataAvailableOrReadAsync>d__38.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.ReadNextFrameAsync>d__37.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<ReceiveAsync>d__36.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Microsoft.AspNetCore.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Microsoft.AspNetCore.SignalR.WebSockets.WebSocketHandler.ProcessWebSocketRequestAsync>d__25.MoveNext())`

I'm using this version of signalr:

Microsoft.AspNetCore.SignalR.Server: 0.2.0-rtm-22752

**Comment by moozzyk** [comment]
As per https://github.com/aspnet/SignalR-Server/blob/dev/README.md this package is deprecated, not maintained and won't be shipped.

**Comment by rrdlpl** [comment]
@moozzyk could you give me please a link that explain how to do the migration from that version to the latest?

**Comment by moozzyk** [comment]
The new version is not production ready so there isn't any official guide. It also requires ASP.NET Core 2.x which has not shipped either. See more details here: https://github.com/aspnet/SignalR/issues/429
