### ISSUE TITLE
Client Cert authentication fails

### ISSUE THREAD

**Issue by willseward** [aspnet/SignalR#436]
WebServer: IIS, Client cert: required

Using this logic:

```csharp
var clientCertHandler = new HttpClientHandler();
if (!string.IsNullOrWhiteSpace(options.CertBundlePath))
{
        var certificate = new X509Certificate2(options.CertBundlePath, options.CertBundlePassword);
        clientCertHandler.ClientCertificates.Add(certificate);
}

. . .

await connection.StartAsync(transport, httpClient);
```

```text
[10:56:28 ERR] Failed to start connection. Error starting transport 'WebSocketsTransport': System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.Http.WinHttpException (0x80072F0C): A certificate is required to complete client authentication
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__20.MoveNext()
   at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport.<Connect>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.WebSocketsTransport.<StartAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.Connection.<StartTransport>d__36.MoveNext()
```

**Comment by berdon** [comment]
Make sure the client trusts the host's certificate and the host trusts the client's certificate otherwise it gets stripped from the request. Even with toggling ignoring certification validation this was the only way to get it to work 100% of the time.

**Comment by willseward** [comment]
@berdon 

Huh... I didn't know that. I'll take a look, thanks!

**Comment by muratg** [comment]
@willseward Did that work?

**Comment by willseward** [comment]
I believe so, but I don't recall and am unable to check.

**Comment by muratg** [comment]
Sounds good, closing this one.
