### ISSUE TITLE
FlakyTest: Microsoft.Extensions.WebSockets.Internal.Tests.WebSocketConnectionTests.AutomaticPingTransmission

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#474]
```
dotnet.exe : [xUnit.net 00:00:02.8367731]     Microsoft.Extensions.WebSockets.Internal.Tests.WebSocketConnectionTests.AutomaticPingTransmission [FAIL]
At C:\projects\signalr\.build\KoreBuild.ps1:10 char:5
+     & $cmd @args
+     ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([xUnit.net 00:0...smission [FAIL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[xUnit.net 00:00:02.8371956]       Assert.NotEqual() Failure
[xUnit.net 00:00:02.8372732]       Expected: Not 0
[xUnit.net 00:00:02.8373234]       Actual:   0
[xUnit.net 00:00:02.8383457]       Stack Trace:
[xUnit.net 00:00:02.8397540]            at Microsoft.Extensions.WebSockets.Internal.Tests.WebSocketConnectionTests.<AutomaticPingTransmission>d__5.MoveNext()
[xUnit.net 00:00:02.8398403]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.8399074]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.8399682]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.8400181]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.8400689]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.8401262]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.8401705]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.8402243]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.8402752]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Microsoft.Extensions.WebSockets.Internal.Tests.WebSocketConnectionTests.AutomaticPingTransmission
Error Message:
 Assert.NotEqual() Failure
Expected: Not 0
Actual:   0
Stack Trace:
```

Any ideas @anurse ?

**Comment by anurse** [comment]
It's a timing-based test. Maybe it's better to just remove it. It's testing the fact that our background process properly sends pings at regular intervals, but I think the xunit sync context messes with it sometimes (which we could work around, but meh...)

**Comment by davidfowl** [comment]
It isn't the sync context. Just tried it https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.862

**Comment by anurse** [comment]
Sure, that was just rampant speculation. The problem is that we kick off a Timer to drive the Pings but sometimes it just doesn't fire in a Unit Test scenario. There may be a product bug under there too, so it's worth investigating, but I wasn't able to identify anything obvious
