### ISSUE TITLE
WebServer taken down due to an exception from channels

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#5]
Not sure where the bug is. It is related to #4. I think there was a write when the connection was being killed due to XmlHttpRequest time out. It brought the entire server down. 

System.InvalidOperationException occurred
  HResult=-2146233079
  Message=No ongoing producing operation. Make sure Alloc() was called.
  Source=Channels
  StackTrace:
       at Channels.Channel.AdvanceWriter(Int32 bytesWritten)
       at Channels.DefaultWritableBufferExtensions.Write(WritableBuffer buffer, Span`1 source)
       at Channels.WritableChannelExtensions.WriteAsync(IWritableChannel channel, Span`1 source)
       at Channels.ChannelStream.Write(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
       at Microsoft.AspNetCore.SignalR.JsonNetInvocationAdapter.Write(Object value, Stream stream) in C:\source\NetworkingProtoype\src\Microsoft.AspNetCore.SignalR\JsonNetInvocationAdapter.cs:line 39
       at Microsoft.AspNetCore.SignalR.JsonNetInvocationAdapter.WriteInvocationDescriptorAsync(InvocationDescriptor invocationDescriptor, Stream stream) in C:\source\NetworkingProtoype\src\Microsoft.AspNetCore.SignalR\JsonNetInvocationAdapter.cs:line 31
       at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.InvokeAllWhere(String methodName, Object[] args, Func`2 include) in C:\source\NetworkingProtoype\src\Microsoft.AspNetCore.SignalR\DefaultHubLifetimeManager.cs:line 68
       at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.InvokeAllAsync(String methodName, Object[] args) in C:\source\NetworkingProtoype\src\Microsoft.AspNetCore.SignalR\DefaultHubLifetimeManager.cs:line 46
       at Microsoft.AspNetCore.SignalR.AllClientProxy`1.InvokeAsync(String method, Object[] args) in C:\source\NetworkingProtoype\src\Microsoft.AspNetCore.SignalR\Proxies.cs:line 53
       at SocketsSample.Hubs.Chat.<OnDisconnectedAsync>d__1.MoveNext() in C:\source\NetworkingProtoype\samples\SocketsSample\Hubs\Chat.cs:line 16
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  InnerException:

**Comment by moozzyk** [comment]
It turned out to be an unhandled exception thrown on a ThreadPool thread. Fixed in 217f707456e250326cec4e551880074623e75084
