### ISSUE TITLE
Fix and unskip flaky test: SSETransportStopsSendAndReceiveLoopsWhenTransportStopped 

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/SignalR#526]
We're skipping it for now to pass the CI, but we should give it an actual investigation.

**Comment by ryanbrandenburg** [comment]
Here's the callstack:
System.Data.SqlClient.SqlException : A connection was successfully established with the server, but then an error occurred during the login process. (provider: Named Pipes Provider, error: 0 - No process is on the other end of the pipe.)
---- System.ComponentModel.Win32Exception : No process is on the other end of the pipe
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__34.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\EntityFramework\src\EFCore.Relational\Storage\RelationalConnection.cs:line 382
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\EntityFramework\src\EFCore.SqlServer\Storage\Internal\SqlServerDatabaseCreator.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\EntityFramework\src\EFCore.SqlServer\Storage\Internal\SqlServerDatabaseCreator.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorEnsureDeletedTest.<EnsuredDeleted_noop_when_database_doesnt_exist_test>d__13.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\EntityFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorEnsureDeletedTest.<EnsuredDeletedAsync_noop_when_database_doesnt_exist>d__11.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\EntityFramework\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----

**Comment by BrennanConroy** [comment]
Yeah thats an EF test callstack...

**Comment by ryanbrandenburg** [comment]
Ohff, I clicked on the failing dev build instead of the failing Preview2 build. Here's the real one. Sorry about that.
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.TimeoutException): Operation in ServerClosesConnectionWithErrorIfHubCannotBeCreated timed out at C:\BuildAgent\work\33bdfc1cae7b2a38\.r\SignalR\test\Microsoft.AspNetCore.SignalR.Tests\EndToEndTests.cs:246
   at Microsoft.AspNetCore.SignalR.Tests.Common.TaskExtensions.<OrTimeout>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<ServerClosesConnectionWithErrorIfHubCannotBeCreated>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<<ServerClosesConnectionWithErrorIfHubCannotBeCreated_LongPolling>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| TestLifetime Information: Starting test ConnectionCanSendAndReceiveMessages_LongPolling
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Starting connection to http://localhost:3000/uncreatable
| Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Disposing Connection
| TestLifetime Information: Finished test ConnectionCanSendAndReceiveMessages_LongPolling in 9.9222497s
```

**Comment by BrennanConroy** [comment]
http://aspnetci/viewLog.html?buildId=232714&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe

**Comment by BrennanConroy** [comment]
I can't get the test to fail. Tried on the same machine that was failing before and it passes every time.

**Comment by ryanbrandenburg** [comment]
This test still fails: http://aspnetci/viewLog.html?buildId=290688&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe#testNameId-3458959110738482103

**Comment by Eilon** [comment]
@BrennanConroy - can you take another look at this?

**Comment by BrennanConroy** [comment]
Well this looks like a completely different test, but I can take a look.

```
System.TimeoutException : Operation in SSETransportStopsSendAndReceiveLoopsWhenTransportStopped timed out
at C:\BuildAgent\work\33bdfc1cae7b2a38\.r\SignalR\test\Microsoft.AspNetCore.SignalR.Client.Tests\ServerSentEventsTransportTests.cs:117
at Microsoft.AspNetCore.SignalR.Tests.Common.TaskExtensions.<OrTimeout>d__2.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\SignalR\test\Common\TaskExtensions.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Microsoft.AspNetCore.SignalR.Client.Tests.ServerSentEventsTransportTests.<SSETransportStopsSendAndReceiveLoopsWhenTransportStopped>d__1.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\SignalR\test\Microsoft.AspNetCore.SignalR.Client.Tests\ServerSentEventsTransportTests.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
---End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by BrennanConroy** [comment]
Punting to Preview1.

There is a bug fix in 2.1.0-* Runtime that allows us to fix this, but in 2.0.0 there is no reasonable fix.

We'll have a note somewhere for alpha1 about SSE possibly hanging when the client is constantly receiving messages.

**Comment by moozzyk** [comment]
https://github.com/dotnet/corefx/issues/22152 is the bug @BrennanConroy is referring to.

**Comment by davidfowl** [comment]
dotnet.exe : [xUnit.net 00:00:05.6291130]     Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.ServerClosesConnectionWithErrorIfHubCannotBeCreated_WebSocket [FAIL]
At C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15508\scripts\common.psm1:7 char:5
+     & $cmd @args
+     ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([xUnit.net 00:0...ebSocket [FAIL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[xUnit.net 00:00:05.6294235]       Assert.Throws() Failure
info: GlobalTestLog[0]
      Finished test ConnectionCanSendAndReceiveMessages_WebSockets in 0.0749788s
[xUnit.net 00:00:05.6294828]       Expected: typeof(System.InvalidOperationException)
[xUnit.net 00:00:05.6295216]       Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
[xUnit.net 00:00:05.6305419]       Stack Trace:
[xUnit.net 00:00:05.6323386]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:05.6324116]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:05.6324736]            at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<SendAsyncCore>d__51.MoveNext()
[xUnit.net 00:00:05.6325206]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.6325613]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:05.6326061]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:05.6326505]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:05.6326932]            at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<SendAsync>d__50.MoveNext()
[xUnit.net 00:00:05.6327316]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.6327722]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:05.6328139]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:05.6328576]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:05.6328989]            at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__19.MoveNext()
[xUnit.net 00:00:05.6329491]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.6329907]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:05.6330341]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:05.6330781]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:05.6331221]            at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__18.MoveNext()
[xUnit.net 00:00:05.6331616]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.6332190]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:05.6332636]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:05.6333060]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:05.6333634]         C:\projects\signalr\test\Common\TaskExtensions.cs(29,0): at Microsoft.AspNetCore.SignalR.Tests.Common.TaskExtensions.<OrTimeout>d__2.MoveNext()
[xUnit.net 00:00:05.6334461]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.6334935]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:05.6335381]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:05.6335832]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:05.6336316]         EndToEndTests.cs(318,0): at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<ServerClosesConnectionWithErrorIfHubCannotBeCreated>d__12.MoveNext()
[xUnit.net 00:00:05.6337143]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.6337552]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:05.6337993]         EndToEndTests.cs(324,0): at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<ServerClosesConnectionWithErrorIfHubCannotBeCreated>d__12.MoveNext()
[xUnit.net 00:00:05.6338788]         --- End of stack trace from previous location where exception was thrown ---
info[xUnit.net 00:00:05.6339376]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
: GlobalTestLog[0]
      Starting test ConnectionCanSendAndReceiveMessages_LongPolling

**Comment by Eilon** [comment]
@muratg / @BrennanConroy - anything to do here for preview1?

**Comment by BrennanConroy** [comment]
SSE test fixed via https://github.com/aspnet/SignalR/pull/1279

**Comment by BrennanConroy** [comment]
Turns out the test still hangs, reopening

**Comment by davidfowl** [comment]
@BrennanConroy can you update the title with the specific test that's flaky?

**Comment by moozzyk** [comment]
🎉
