### ISSUE TITLE
"No Channel" exception in long polling

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#57]
When running end to end tests I am working on I semi occasionally (25% of times) receive this:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/testhub/getid?formatType=json&format=text
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.2851ms 200
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/testhub/send?id=055127ed-e4f0-421d-96f7-eaf32a251ced&055127ed-e4f0-421d-96f7-eaf32a251ced application/x-www-form-urlencoded 120
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/testhub/poll?id=055127ed-e4f0-421d-96f7-eaf32a251ced&055127ed-e4f0-421d-96f7-eaf32a251ced
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL0PDKEHGN48": An unhandled exception was thrown by the application.
System.InvalidOperationException: No channel
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.ProcessSend(HttpContext context) in C:\source\SignalR-Core\src\Microsoft.AspNetCore.Sockets\HttpConnectionDispatcher.cs:line 214
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteAsync>d__4`1.MoveNext() in C:\source\SignalR-Core\src\Microsoft.AspNetCore.Sockets\HttpConnectionDispatcher.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3.1934ms 500
```

Notice that send was send before the first poll

**Comment by moozzyk** [comment]
The tests are WIP but you can repro the issue by running tests in [this branch](https://github.com/aspnet/SignalR/tree/pawelka/e2etests) - start the Tests server and navigate to connectionTests.html in the browser.

**Comment by davidfowl** [comment]
Yea send before poll would cause that.

**Comment by moozzyk** [comment]
Yes, the problem is that it can't be really controlled - even if the poll request is started first and send happens immediately after this there is no guarantee the server will receive poll first. Also with @BrennanConroy we were wondering if the same applies to ServerSentEvents.

**Comment by davidfowl** [comment]
We'll need to make the pipeline reader writer up front then. We also need to figure out how to handle the case where the client never connects. We might need a double handshake...

**Comment by moozzyk** [comment]
Can we create it on first poll __or__ send?

**Comment by davidfowl** [comment]
Yea we could do that, I dunno if that complicates the logic.

**Comment by moozzyk** [comment]
We can't create a channel on send because we don't know the format. To be able to do this we would have to require sending the format with send requests but this opens another can of worms where the format sent with send does not match the format sent with poll.

**Comment by mikaelm12** [comment]
Can this be marked as done now @anurse ?
