### ISSUE TITLE
Closing websocket in the browser causing failure on server

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#580]
Run the hubs sample in SocketSample and click connect then disconnect. This exception is thrown:

```
fail: Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport[11]
      06/23/2017 03:16:49: Connection Id 8b302138-d905-4238-a966-5f5cb37331f8: Error writing frame.
System.Net.WebSockets.WebSocketException (0x80004005): TODO, RESX: net_WebSockets_InvalidState; (CloseSent,Open, CloseReceived)
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport.<StartSending>d__8.MoveNext() in C:\Users\dfowler\Documents\GitHub\SignalR\src\Microsoft.AspNetCore.Sockets.Http\Internal\Transports\WebSocketsTransport.cs:line 180
```

**Comment by BrennanConroy** [comment]
That doesn't happen on the dev branch, but I tried your PR #579 and it happens there

**Comment by davidfowl** [comment]
Ahhhh I though I cleaned. I guess not.

**Comment by BrennanConroy** [comment]
Oh wait, its just a flaky error. I managed to repro it on dev

**Comment by davidfowl** [comment]
!!!

**Comment by davidfowl** [comment]
The fact that none of our tests catch that means we have a gap as well.

**Comment by muratg** [comment]
Assigning to @BrennanConroy for investigation.  Possible fix is catching the exception and ignoring it (if WebSocket is closed.)

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/SignalR/commit/e36da3007214db1b3c085972cd88be23c7a2a97e
