### ISSUE TITLE
Investigate flaky test on Appveyor

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/SignalR#608]
https://ci.appveyor.com/project/aspnetci/signalr/build/1.0.1152

```
[xUnit.net 00:00:10.2284656]       System.TimeoutException : Operation in ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport timed out at C:\projects\signalr\test\Microsoft.AspNetCore.SignalR.Tests\EndToEndTests.cs:187
[xUnit.net 00:00:10.2295264]       Stack Trace:
[xUnit.net 00:00:10.2314951]         C:\projects\signalr\test\Common\TaskExtensions.cs(29,0): at Microsoft.AspNetCore.SignalR.Tests.Common.TaskExtensions.<OrTimeout>d__2.MoveNext()
[xUnit.net 00:00:10.2315993]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.2316518]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.2317012]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.2317537]         EndToEndTests.cs(188,0): at Microsoft.AspNetCore.SignalR.Tests.EndToEndTests.<ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport>d__6.MoveNext()
[xUnit.net 00:00:10.2318408]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.2318896]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.2319337]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.2319740]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.2320187]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.2320644]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.2321107]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.2322715]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.2324379]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.2332843]       Output:
[xUnit.net 00:00:10.2334044]         | TestLifetime Information: Starting test ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport_4096032
[xUnit.net 00:00:10.2334576]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Starting connection to http://localhost:3000/echo
[xUnit.net 00:00:10.2335015]         | WebSocketsTransport Information: Starting WebSocketsTransport
[xUnit.net 00:00:10.2335520]         | WebSocketsTransport Information: Starting the send loop
[xUnit.net 00:00:10.2336076]         | WebSocketsTransport Information: Starting receive loop
[xUnit.net 00:00:10.2336500]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Started connection to http://localhost:3000/echo
[xUnit.net 00:00:10.2336876]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Sending 4096032 byte message
[xUnit.net 00:00:10.2337272]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Sent message
[xUnit.net 00:00:10.2337641]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Receiving message
[xUnit.net 00:00:10.2338125]         | WebSocketsTransport Information: Passing message to application. Payload size: 4096032
[xUnit.net 00:00:10.2338540]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Received 4096032 byte message
[xUnit.net 00:00:10.2338920]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Completed receive
[xUnit.net 00:00:10.2339310]         | Microsoft.AspNetCore.SignalR.Tests.EndToEndTests Information: Disposing Connection
[xUnit.net 00:00:10.2339673]         | Microsoft.AspNetCore.Sockets.Client.HttpConnection Information: Stopping client.
[xUnit.net 00:00:10.2340069]         | WebSocketsTransport Information: Transport WebSocketsTransport is stopping
[xUnit.net 00:00:10.2340437]         | WebSocketsTransport Information: Closing webSocket
[xUnit.net 00:00:10.2340822]         | WebSocketsTransport Information: Send loop stopped
[xUnit.net 00:00:10.2341204]         | WebSocketsTransport Information: Receive loop stopped
[xUnit.net 00:00:10.2341616]         | TestLifetime Information: Finished test ConnectionCanSendAndReceiveDifferentMessageSizesWebSocketsTransport_4096032 in 5.4759264s
Failed   
```

**Comment by mikaelm12** [comment]
Shouldn't we disable it for now while it's still flaky?

**Comment by ryanbrandenburg** [comment]
Looks like this is the same thing as #526 and #618. This also happened [here](http://aspnetci/viewLog.html?buildId=275675&buildTypeId=XPlat_Mac_MacUniverseCoreCLR&tab=buildResultsDiv), so it's not just an Appveyor issue.

**Comment by ryanbrandenburg** [comment]
Was this closed by [this commit](https://github.com/aspnet/SignalR/commit/b393200fd32a811340dfe20eeff75660d375c1bf)?

**Comment by BrennanConroy** [comment]
I think it was fixed by https://github.com/aspnet/SignalR/pull/695

**Comment by ryanbrandenburg** [comment]
Cool, thanks for digging into this one!
