### ISSUE TITLE
Investigate and fix flaky test

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#618]
https://github.com/aspnet/SignalR/pull/617#issuecomment-312037232

https://travis-ci.org/aspnet/SignalR/jobs/248434170

```
Starting test execution, please wait...
[xUnit.net 00:00:00.7235010]   Discovering: Microsoft.AspNetCore.Sockets.Tests
[xUnit.net 00:00:01.0884260]   Discovered:  Microsoft.AspNetCore.Sockets.Tests
[xUnit.net 00:00:01.1035850]   Starting:    Microsoft.AspNetCore.Sockets.Tests
[xUnit.net 00:00:07.1742160]     Microsoft.AspNetCore.Sockets.Tests.WebSocketsTests.TransportFailsWhenClientDisconnectsAbnormally [FAIL]
[xUnit.net 00:00:07.1758710]       System.TimeoutException : Operation in TransportFailsWhenClientDisconnectsAbnormally timed out at /Users/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs:126
[xUnit.net 00:00:07.1804480]       Stack Trace:
[xUnit.net 00:00:07.1826010]         /Users/travis/build/aspnet/SignalR/test/Common/TaskExtensions.cs(45,0): at Microsoft.AspNetCore.SignalR.Tests.Common.TaskExtensions.<OrTimeout>d__4`1.MoveNext()
[xUnit.net 00:00:07.1827170]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.1828220]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.1829270]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.1830330]         /Users/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs(126,0): at Microsoft.AspNetCore.Sockets.Tests.WebSocketsTests.<TransportFailsWhenClientDisconnectsAbnormally>d__2.MoveNext()
[xUnit.net 00:00:07.1831450]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.1832320]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.1833620]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.1834930]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.1835990]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.1837020]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:07.1838320]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:07.1839810]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:07.1840510]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Microsoft.AspNetCore.Sockets.Tests.WebSocketsTests.TransportFailsWhenClientDisconnectsAbnormally
Error Message:
 System.TimeoutException : Operation in TransportFailsWhenClientDisconnectsAbnormally timed out at /Users/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs:126
Stack Trace:
   at Microsoft.AspNetCore.SignalR.Tests.Common.TaskExtensions.<OrTimeout>d__4`1.MoveNext() in /Users/travis/build/aspnet/SignalR/test/Common/TaskExtensions.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Tests.WebSocketsTests.<TransportFailsWhenClientDisconnectsAbnormally>d__2.MoveNext() in /Users/travis/build/aspnet/SignalR/test/Microsoft.AspNetCore.Sockets.Tests/WebSocketsTests.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:15.4605030]   Finished:    Microsoft.AspNetCore.Sockets.Tests
```

**Comment by davidfowl** [comment]
I looked into this and it's a test issue.
