### ISSUE TITLE
Long polling transport on the client sends polls even if it is supposed to be closed

### ISSUE THREAD

**Issue by moozzyk** [aspnet/SignalR#66]
Enable logging when running functional tests and you often get this:

```
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[5]
      Hosting shutdown
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.1319ms 200
  Finished:    Microsoft.AspNetCore.SignalR.Client.FunctionalTests
fail: Microsoft.AspNetCore.Sockets.Client.LongPollingTransport[0]
      Error while polling 'http://test/hubs/poll?id=b9f56cdf-6b85-4977-a761-fe67de69f46f': System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'Microsoft.AspNetCore.TestHost.TestServer'.
         at Microsoft.AspNetCore.TestHost.TestServer.<Microsoft.AspNetCore.Hosting.Server.IServer.Start>b__20_0[TContext]()
         at Microsoft.AspNetCore.TestHost.TestServer.ApplicationWrapper`1.ProcessRequestAsync(TContext context)
         at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Microsoft.AspNetCore.Sockets.Client.LongPollingTransport.<Poll>d__16.MoveNext() in C:\source\SignalR-Core\src\Microsoft.AspNetCore.Sockets.Client\LongPollingTransport.cs:line 70
```

It won't fail the test because the test is already completed but

**Comment by mikaelm12** [comment]
Any ideas @anurse @davidfowl @BrennanConroy?
This is currently what is blocking https://github.com/aspnet/SignalR/pull/69

**Comment by BrennanConroy** [comment]
If the tests don't fail then this shouldn't be blocking the PR.

Anyways, I think the issue is we should be passing the `CancellationToken` into `Task.Factory.StartNew` here https://github.com/aspnet/Hosting/blob/4abb48e1aaa730062cef7f0f0fd08c9c5b72413d/src/Microsoft.AspNetCore.TestHost/ClientHandler.cs#L79

**Comment by davidfowl** [comment]
Does this still repro?

**Comment by moozzyk** [comment]
I have not seen this happening in a while. Closing.
