### ISSUE TITLE
Bizarre Null Reference Exception on Hub Invoke

### ISSUE THREAD

**Issue by brettclutch** [aspnet/SignalR#672]
I'm trying to get going on the bleeding edge SignalR (Cool that you guys are developing in open btw). After some wrestling with nuget feeds and .net standard.aspnet pre-release builds I thought I "got it". 

I'm trying to run the "SocketSample" code which is copied into my own blank ASP Core 2 project and running into the following null reference exception. Its a null reference unlike anything I've ever seen since I can't find what is null. Figured I'd report it.

![nullreferenceaspnet](https://user-images.githubusercontent.com/3532782/28399052-ed1ade60-6cc7-11e7-812f-5f7a136ce545.png)

I get this stack trace from Kestrel console window in debug mode:

```
fail: Microsoft.AspNetCore.SignalR.HubEndPoint[0]
      Error when invoking OnConnectedAsync on hub.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubProtocolWriteMessageExtensions.WriteToArray(IHubProtocol protocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.<WriteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketsSample.Hubs.Chat.<OnConnectedAsync>d__0.MoveNext() in C:\cmd\Athena\Athena.Server\Hubs\Chat.cs:line 14
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<HubOnConnectedAsync>d__10.MoveNext()
fail: Microsoft.AspNetCore.Sockets.ConnectionManager[2]
      07/19/2017 21:25:49: ConnectionId 3dc46861-76f9-4acc-b211-14e6e5052668: Failed disposing connection.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.HubProtocolWriteMessageExtensions.WriteToArray(IHubProtocol protocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.<WriteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketsSample.Hubs.Chat.<OnConnectedAsync>d__0.MoveNext() in C:\cmd\Athena\Athena.Server\Hubs\Chat.cs:line 14
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<HubOnConnectedAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<RunHubAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteApplication>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()
```

**Comment by mikaelm12** [comment]
Can you post a link to a repro repository?

**Comment by moozzyk** [comment]
+1 for a repro and the versions of SignalR dlls being used. 
[This line](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/Internal/Protocol/HubProtocolWriteMessageExtensions.cs#L16) seems to be the only one that can fail with NulReferenceException and this stack trace. It would happen if the protocol could not be resolved but the default resolver throws if it cannot resolve the protocol.

**Comment by brettclutch** [comment]
I feel this could be closed. I did more debugging and the problem was related to this: https://github.com/aspnet/SignalR/issues/477 

The exception was obfuscated since I had debug "Just My Code" enabled on this computer on accident which seems to have resulted in the bazaar null reference exception.

**Comment by moozzyk** [comment]
Still the NullReferenceException there should not happen. It feels like a bug is lurking somewhere.

**Comment by davidfowl** [comment]
Seems related to https://github.com/aspnet/SignalR/issues/905

**Comment by moozzyk** [comment]
#905 was fixed - closing.
