### ISSUE TITLE
Dependency Injection in Hubs

### ISSUE THREAD

**Issue by harisbotic** [aspnet/SignalR#68]
I wanted to access some repositories/services from within a hub, is that possible now? Will you implement this feature later?

**Comment by BrennanConroy** [comment]
This should be possible, give it a try.

**Comment by harisbotic** [comment]
```cs
public class Chat : Hub
{
        private IP2PRepository _p2pRepo;
        
        public Chat(IP2PRepository p2pRepo)
        {
            _p2pRepo = p2pRepo;
        }

        public override Task OnConnectedAsync()
        {
            System.Console.WriteLine("SOMEONE CONNECTED");
            return Task.CompletedTask;
        }

        public override Task OnDisconnectedAsync()
        {
            System.Console.WriteLine("SOMEONE DISCONNECTED");
            return Task.CompletedTask;
        }
}
```

and the Error in console is
```An unhandled exception was thrown by the application.
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()```

**Comment by BrennanConroy** [comment]
Oh yeah, I fixed that a few days ago. What version of Microsoft.AspNetCore.SignalR are you using?

**Comment by harisbotic** [comment]
Saw it just now...
Thank you, I fixed it

**Comment by harisbotic** [comment]
And now, I can't get of this error whenever someone tries to connect

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.SignalR.JsonNetInvocationAdapter.<>c__DisplayClass2_0.<ReadInvocationDescriptorAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<DispatchMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`2.<OnConnectedAsync>d__8.MoveNext()
```

**Comment by BrennanConroy** [comment]
Not related to this issue, look at #64 and #62

**Comment by moozzyk** [comment]
@harisbotic - hub method names are no longer fully qualified names but just method names.

**Comment by avijassra** [comment]
I am having the same issue. I am not able to use DI in SignalR (1.0.0-alpha2-final) with AspNetCore (2.0.0). Any pointers

**Comment by davidfowl** [comment]
Can you make a minimal repro of the issue on GitHub?

**Comment by avijassra** [comment]
@davidfowl , when i am trying to start the connection, i am getting this new error .... at this line

File -> https://github.com/avijassra/signalrDi/blob/v1-reboot/ClientApp/app/services/pubsub.service.ts#L16
this.connection = new HubConnection('chat');
//this.startedConnection = this.connection.start();

File -> https://github.com/avijassra/signalrDi/blob/v1-reboot/Startup.cs#L47
app.UseSignalR(routes =>
                routes.MapHub<signalrDi.Hubs.ChatHub>("chat"));

This is different issue then my DI issue as mentioned earlier .... thanks

**Comment by davidfowl** [comment]
@avijassra why not file a different bug then?

**Comment by avijassra** [comment]
@davidfowl Done

**Comment by avijassra** [comment]
Singleton not working in my app was a code issue and not SignalR issue. Thanks to @davidfowl for your time and help.
- Avi
