### ISSUE TITLE
Can't connect with Javascript client

### ISSUE THREAD

**Issue by windischb** [aspnet/SignalR#740]
Hi!

When i try to connect to the Server i'll always get this Error on Server side:
```
[12:16:22 ERR] Failed disposing connection 3c9724d3-5b78-4a2d-b58f-44867d823df9
System.FormatException: Invalid length: '{"protocol"'
   at Microsoft.AspNetCore.Sockets.Internal.Formatters.TextMessageParser.TryReadLength(ReadOnlySpan`1 buffer, Int32& index, Int32& length)
   at Microsoft.AspNetCore.Sockets.Internal.Formatters.TextMessageParser.TryParseMessage(ReadOnlyBuffer`1& buffer, ReadOnlyBuffer`1& payload)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.NegotiationProtocol.TryParseMessage(ReadOnlyBuffer`1 input, NegotiationMessage& negotiationMessage)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<ProcessNegotiate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteApplication>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()
```

On clientside:
![image](https://user-images.githubusercontent.com/6182311/29515082-2e7fb45e-866b-11e7-89e9-7b1d0016c763.png)

Any Ideas??

**Comment by davidfowl** [comment]
You updated the sever but not the client ?

**Comment by windischb** [comment]
The other way around... >.<
Client was newer as server...
Thanks for the hint!
