### ISSUE TITLE
Using languages other than English

### ISSUE THREAD

**Issue by scroogefi** [aspnet/SignalR#795]
Hi, 

I've created simple chat app using 
Microsoft.AspNetCore.All (2.1.0-preview1-26667)
Microsoft.AspNetCore.SignalR.Http (1.0.0-alpha1-26667)

And it works fine until I use not English symbols like ööö 
After that:

fail: Microsoft.AspNetCore.SignalR.HubEndPoint[0]
      Error when processing requests.
System.FormatException: Missing delimiter ';' after payload
   at Microsoft.AspNetCore.Sockets.Internal.Formatters.TextMessageParser.TryReadDelimiter(ReadOnlySpan`1 buffer, Char delimiter, String field)
   at Microsoft.AspNetCore.Sockets.Internal.Formatters.TextMessageParser.TryParseMessage(ReadOnlyBuffer`1& buffer, ReadOnlyBuffer`1& payload)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.TryParseMessages(ReadOnlyBuffer`1 input, IInvocationBinder binder, IList`1& messages)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<DispatchMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<RunHubAsync>d__11.MoveNext()
fail: Microsoft.AspNetCore.Sockets.ConnectionManager[2]
      08/30/2017 11:56:34: ConnectionId 9a77e996-9e10-4136-b794-554611d31e0e: Failed disposing connection.
System.FormatException: Missing delimiter ';' after payload
   at Microsoft.AspNetCore.Sockets.Internal.Formatters.TextMessageParser.TryReadDelimiter(ReadOnlySpan`1 buffer, Char delimiter, String field)
   at Microsoft.AspNetCore.Sockets.Internal.Formatters.TextMessageParser.TryParseMessage(ReadOnlyBuffer`1& buffer, ReadOnlyBuffer`1& payload)
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.JsonHubProtocol.TryParseMessages(ReadOnlyBuffer`1 input, IInvocationBinder binder, IList`1& messages)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<DispatchMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<RunHubAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<RunHubAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.HttpConnectionDispatcher.<ExecuteApplication>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<WaitOnTasks>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.DefaultConnectionContext.<DisposeAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.ConnectionManager.<DisposeAndRemoveAsync>d__14.MoveNext()

**Comment by davidfowl** [comment]
Try updating to build 26848, this is fixed now.

**Comment by scroogefi** [comment]
Thank you, just wanted to raise the flag in case if it is not found.
