### ISSUE TITLE
net core console signalr client fail

### ISSUE THREAD

**Issue by soyCracker** [aspnet/SignalR#883]
I have some problem with my project. My signalr server write in asp.net(not asp.net core)：
````
using Microsoft.AspNet.SignalR;

namespace iotAC_SignalR_Server
{
    public class BroadcastHub : Hub
    {
        public void broadcast(string command)
        {
            Clients.All.messageReceived(command);
        }
    }
}
-----------------------------------------------------------
using Microsoft.Owin;
using Owin;

[assembly: OwinStartup(typeof(iotAC_SignalR_Server.Startup))]

namespace iotAC_SignalR_Server
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.MapSignalR();
        }
    }
}
````
My UWP signalr client works fine,but my net core 2.0 console signalr client is failed.This client just needs to receive data but dosen't need to send data.  
code：
````
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;

namespace netcoreConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");          
            connet().Wait();
        }
        static async Task connet()
        {
            HubConnection connection = await ConnectAsync("http://iotac-signalr-server20170913.azurewebsites.net/");
            connection.On("messageReceived", Console.WriteLine);
        }
        public static async Task<HubConnection> ConnectAsync(string baseUrl)
        {
            // Keep trying to until we can start
            while (true)
            {
                var connection = new HubConnectionBuilder()
                                .WithUrl(baseUrl)
                                .WithConsoleLogger(LogLevel.Trace)
                                .Build();
                try
                {
                    await connection.StartAsync();
                    return connection;
                }
                catch (Exception)
                {
                    await Task.Delay(1000);
                }
            }
        }
    }
}
````
error：
````
Hello World!
dbug: Microsoft.AspNetCore.Sockets.Client.HttpConnection[0]
      09/15/2017 17:41:09: Starting connection.
dbug: Microsoft.AspNetCore.Sockets.Client.HttpConnection[7]
      09/15/2017 17:41:09: Establishing Connection at: http://iotac-signalr-server20170913.azurewebsites.net/.
fail: Microsoft.AspNetCore.Sockets.Client.HttpConnection[8]
      09/15/2017 17:41:09: Failed to start connection. Error getting negotiation response from 'http://iotac-signalr-server20170913.azurewebsites.net/'.
System.FormatException: Invalid negotiation response received.
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<ParseNegotiateResponse>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Sockets.Client.HttpConnection.<Negotiate>d__42.MoveNext()
````
Please help me, thank you very much.

**Comment by BrennanConroy** [comment]
> SignalR for ASP.NET Core is not compatible with previous versions of SignalR. This means that you cannot use the old server with the new clients or the old clients with the new server. Below are the features which have been removed or changed in the new version of SignalR.

https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/

**Comment by grahamehorner** [comment]
@BrennanConroy You just beat me to that 😉 🤔 Is it possible to run the different SignalR client/servers side by side or possibly doing a bridging api 🤔

**Comment by davidfowl** [comment]
@grahamehorner with enough work anything is possible but we have no plans to build to bridge between the 2 versions. There are fundamental differences between the 2 versions.

**Comment by moozzyk** [comment]
@davidfowl - can we close this?

**Comment by davidfowl** [comment]
Yep

**Comment by jagathprasanga** [comment]
Is there any library for Android(java) which is compatible with Asp.Net Core 2.0 SignalR.
Thanks.

**Comment by moozzyk** [comment]
We don't have a Java client at the moment. If you are feeling adventurous you may try using bare websocket to connect to the server. [Here](https://github.com/aspnet/SignalR-samples/commit/85c8d9335da66009459434ca468f27d96dc27cb8#diff-9846a0122aad889ad5a09abe1f60edd3) you can find what it would take to do that.
